### ISSUE TITLE
Insert Emoji via Keyboard

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#1]
Convert emoji shortnames (e.g. `:smile:`) to emoji while typing.

**Comment by Jintzo** [comment]
Like Slack? I think https://github.com/needim/wdt-emoji-bundle/ comes pretty close - implementing auto-search while typing should not be too hard

**Comment by dbrgn** [comment]
Emojione already provides a function to convert shortnames to inline images: https://github.com/Ranks/emojione/blob/master/lib/js/emojione.js#L240-L275 It just needs to be integrated into the compose area directive.

**Comment by fichtennadel** [comment]
6 months later and still missing `:-)` to be replaced. Any timeline available for this?

**Comment by dbrgn** [comment]
`:-)` will never be replaced, but shortcodes like `:smile:` will. Implementing this is definitely still planned, it's just that some of the developer resources have been dedicated to develop the voip call feature lately. So it'll be added sooner or later :)

In case a developer is very eager to see this, pull requests are welcome! The goal is for the feature to work similarly to the way it's implemented on Github, just with the difference that emoji are replaced immediately when pressing enter and not just on send.
