### ISSUE TITLE
Upgrade to AngularJS 1.7

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#100]
Release notes: https://angularjs.blogspot.ch/2016/12/angular-160-released.html

Migration guide: https://docs.angularjs.org/guide/migration#migrating-from-1-5-to-1-6

**Comment by ovalseven8** [comment]
Is not it a risk to use an old AngularJS version with unfixed security-related bugs?

**Comment by rugk** [comment]
Maybe have a look at https://blog.angularjs.org/2016/12/angular-160-released.html, "Previous Version Support":
> We continue to support Angular 1.2 with security patches as it is the last version of Angular to support Internet Explorer 8 and from now on Angular 1.5 will receive serious bug fixes and security patches.

So of course they provide security patches for older Angular versions.

**Comment by ovalseven8** [comment]
@dbrgn Closeable?

**Comment by ovalseven8** [comment]
Seems like Threema Web will need a complete re-write in the long-term:
http://www.codelord.net/2018/02/04/angularjs-1-dot-7-the-ultimate-version/

What's the plan for the future, @dbrgn?

**Comment by dbrgn** [comment]
In the long term, yes. But we have security updates for at least 3 years. A re-write depends on the priorities we'll choose.

**Comment by ovalseven8** [comment]
Well, I hope Threema will choose the priorities early enough. :smile:

**Comment by ovalseven8** [comment]
@dbrgn Is not this done now?

**Comment by dbrgn** [comment]
Yes, for some reason it was not closed by #522.
