### ISSUE TITLE
Costumizable notification intervalls

### ISSUE THREAD

**Issue by Rummelbooz** [threema-ch/threema-web#1006]
Hi,

I’m often annoyed by getting to many messages in a short period of time and hence my notifications escalating. Most common in groups. 

I would wish for some kind of notification delay or intervals. I’ll try to explain what I mean.

- First Message arrives -->Notification --> Timer of let’s say 10 seconds starts.
-- Further messages arrive while that timer counts down (10 s) --> I will get only ONE notification after that 10 s timer elapsed.
--- This will start the next timer of let’s say 30 seconds.
-- If no message arrives within that timer the next notification won’t be delayed.

The duration of the timers could be made customizable. This system would also avoid getting five notifications one after the other if someone sends five pics in a group. I think like four timers would be good (10s, 30s, 90s, 300s)

Maybe there are better ideas but that’s what I came up with. I hope I could make clear what I imagine.

**Comment by lgrahl** [comment]
I understand what you mean.

Receiving bundled images one after another can indeed be an annoying sequence of notifications. It is not a Threema Web specific issue though but rather something that concerns all apps and perhaps some level of the protocol, so I'll file an internal issue for that part in particular.

For general (text) messages, I'm not sure there should be such a mechanism. IMO, the underlying notification mechanism of the OS/browser to be "smart" enough to bundle notification that occur quickly one after another.

**Comment by Rummelbooz** [comment]
Sorry, I didn’t want to post it as Threema Web issue. That was a mistake. I was talking about the (Android) app. Maybe you can move my request. 

 

I use a Samsung Galaxy S7 with Android 8.0.0. I haven’t found such settings in the OS yet.

 

Von: Lennart Grahl <notifications@github.com> 
Gesendet: Mittwoch, 18. November 2020 14:10
An: threema-ch/threema-web <threema-web@noreply.github.com>
Cc: Rummelbooz <github@jaz.leimet.de>; Author <author@noreply.github.com>
Betreff: Re: [threema-ch/threema-web] Costumizable notification intervalls (#1006)

 

I understand what you mean.

Receiving bundled images one after another can indeed be an annoying sequence of notifications. It is not a Threema Web specific issue though but rather something that concerns all apps and perhaps some level of the protocol, so I'll file an internal issue for that part in particular.

For general (text) messages, I'm not sure there should be such a mechanism. IMO, the underlying notification mechanism of the OS/browser to be "smart" enough to bundle notification that occur quickly one after another.

**Comment by lgrahl** [comment]
Have filed an issue for it.
