### ISSUE TITLE
[Bug] threema.ch support contact form broken

### ISSUE THREAD

**Issue by rasenplanscher** [threema-ch/threema-web#1010]
This is not exactly the correct place for this issue, but I don't know a better one, I'm sorry.

## Bug Description

I cannot send the contact form at https://threema.ch/en/request/default?i_have_read_the_faq=1.
When trying in MS Edge (Windows 10), I get this on the console:
![image](https://user-images.githubusercontent.com/445565/103087258-270f2d00-45e7-11eb-92f3-940e0161cdf8.png)

The UI does not give any error message.

**Comment by dbrgn** [comment]
Thanks, forwarded to the responsible person!

**Comment by dbrgn** [comment]
@rasenplanscher note: We tested this in multiple versions of MS Edge and could not reproduce the issue. What version are you using?

**Comment by rasenplanscher** [comment]
Version 87.0.664.66 (Official build) (64-bit)

I just retried and made a screen capture of the process:
![threema](https://user-images.githubusercontent.com/445565/103106309-a1b26980-4634-11eb-95bd-7fa0f5f56ac6.gif)

This time it worked, while before it consistently failed. This is the original text I tried to post, so it's probably an issue with Unicode characters, note the vertical ellipsis before „menu“:
> I'd like to use ThreemaWeb in Rambox, and the header, footer, and padding are taking up too much space. Please use a focussed design, at least for small viewports. WhatsApp Web does that well: There's only the list of contacts and the message area.
> I don't need a header telling me this is Threema, I know that, so it can just go. Also, I frankly don't care about the footer items 99% of the time, so they can be safely hidden in the ⋮-menu.

Also note that the first error pops up on opening the app version `select`.
