### ISSUE TITLE
Device unreachable overlay sizing issue

### ISSUE THREAD

**Issue by isehuetdk** [threema-ch/threema-web#1028]
## Bug Description

The "Device Unreachable" overlay seems not to have the same size as the form and thus, the Reload Page button is active at a different position than the visible Reload Page button is visible. Seems like the whole div overlay is scaled differently than the md-dialog.

## Steps to Reproduce (for bugs)

![ThreemaWebbug](https://user-images.githubusercontent.com/57175079/105463790-de539e00-5c90-11eb-8738-542dc3284fa0.PNG)

## Potential Solution

Adjust size of md-dialog with class "_md md-threema-theme md-transition-in" to div overlay

## Your Environment

* Threema Web version: 2.3.8 Säntis
* Threema App version:
* Browser name and version: Edge Chromium 87.0.664.75
* Computer operating system and version: Windows 10 20H2
* Smartphone operating system and version:

**Comment by lgrahl** [comment]
Don't have an Edge browser at hand but since it's basically Chromium, I tried that and cannot reproduce it. Any addons that might interfere here? I suggest trying it again with a fresh browser profile.

**Comment by isehuetdk** [comment]
Has been a session from yesterday open on my device and was in that state this morning. Have put my mobile in airplane mode to test it and saw that the design of the "Device Unreachable" overlay is a bit different, having a Reload Page and Retry button. Cannot reproduce it - maybe the above overlay is only shown if the device has been unavailable for a longer time.

**Comment by lgrahl** [comment]
Might have been a one-off quirk from the browser (or AngularJS for that matter). Feel free to reopen if it happens again. :slightly_smiling_face:
