### ISSUE TITLE
Threema web wav file download

### ISSUE THREAD

**Issue by NXZAS8CA** [threema-ch/threema-web#1032]
## Bug Description
If i try to download a wav-file(18.34MB) from the Threema web connection, the connection keeps reloading and stops the download. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Threema Web version: 2.3.8
* Threema App version: 4.6.5(2604)
* Browser name and version: Firefox 85.0.1(64bit)

**Comment by threema-danilo** [comment]
Does this happen only for WAV files, or for all file types?

**Comment by NXZAS8CA** [comment]
for me it only occurs when i try to download a wav file.
I also tried docx, pdf and png, but they went fine

**Comment by threema-danilo** [comment]
We cannot reproduce the issue on our iOS devices. Does it also occur if the Threema app is open on your iPhone and the screen is unlocked?

**Comment by NXZAS8CA** [comment]
I tested it with my unlocked iPhone and open Threema app. Then the download works fine.
The icon changed to headphones and everytime i try it now it works fine

**Comment by threema-danilo** [comment]
Are you on a rather slow internet connection? When running in the background, iOS throttles the CPU for background processes and limits the time a process may run. After a certain time, the process is simply killed  by the system, if the download takes too long. By keeping the app in the foreground, you avoid both the CPU throttling and the time limits, thus it works.

I fear there's not much we can do here, this is one of the limitations by Apple that we can't get around. This is why we're working on a new solution to replace Threema Web: #996.
