### ISSUE TITLE
Writing a message in a group or distribution list appears as draft in the wrong place in the chat list

### ISSUE THREAD

**Issue by uwemock** [threema-ch/threema-web#1037]
## Bug Description

I select a group or distribution list from the chat list and start entering a message. "Draft" will appear in the chat list along with the first part of the text I have written - but it is shown in the wrong place. It shows up at some other group or distribution list, but not the one I had selected and that is shown in the top center of the window.

## Steps to Reproduce (for bugs)

![2021-10-02_threema_web_bug](https://user-images.githubusercontent.com/31033449/107512868-b8425f00-6ba7-11eb-9dd0-5fb25f9d8af8.png)

## Your Environment

* Threema Web version: 2.3.8
* Threema App version: 4.5
* Browser name and version: Happens on any browser
* Computer operating system and version: Kubuntu 20.04
* Smartphone operating system and version: Android 10

**Comment by threema-danilo** [comment]
I could finally reproduce this. Fix incoming.
