### ISSUE TITLE
Version in minimal ui option isn't displayed correctly

### ISSUE THREAD

**Issue by jwanner83** [threema-ch/threema-web#1038]
## Bug Description
After activating the minimal ui option, a new option is available in the dropdown to display the version popup. In this popup, the version is missing / isn't displayed.
![version-popup](https://user-images.githubusercontent.com/38656104/109414090-52c8dd80-79b1-11eb-81f9-774a402770f1.png)

## Steps to Reproduce (for bugs)
1. Activate the minimal UI option
2. Open the version popup
![grafik](https://user-images.githubusercontent.com/38656104/109413926-4ee88b80-79b0-11eb-907e-cf9a8b858e97.png)

## Potential Solution
Because I implemented the minimal ui option, I will have a look at this issue and fix it. 

## Your Environment
* Threema Web version: 2.9.3 
* Threema App version: 4.5 Android
* Browser name and version: Firefox 86.0

**Comment by threema-danilo** [comment]
@jwanner83 do you still plan to tackle this issue, or should we take a look?

**Comment by jwanner83** [comment]
Hey @threema-danilo I kinda forgot about this ticket, sorry. Because of my vacations, I won't be able to have a look at it till the 14. August. I wouldn't be mad, if you guys want to do it in the meantime. :)

**Comment by threema-danilo** [comment]
Fixed in #1076. The two dialogs were not using the same controller.

**Comment by jwanner83** [comment]
Thank you 🙏
