### ISSUE TITLE
Replying to a message shows repliers name in the quoted message instead of original writer

### ISSUE THREAD

**Issue by samuelT2** [threema-ch/threema-web#1041]
## Bug Description

Replying to a person does not show the persons name from the original post, but the repliers name.

## Steps to Reproduce (for bugs)

1. Reply to any message via "Quote"

![Screenshot 2021-03-03 005152](https://user-images.githubusercontent.com/10983143/109731750-2b922c00-7bbc-11eb-9a9d-f9d4938b0539.png)

## Your Environment

* Threema Web version: v2.3.9
* Threema App version: iOS version 4.6.5 (2604)
* Browser name and version: Chrome, v88.0.4324.190
* Computer operating system and version: Windows 10 Pro, 20H2
* Smartphone operating system and version: iPhone 8, iOS 14.4

**Comment by threema-jarem** [comment]
Thank you for your report!

This issue will be fixed with the upcoming version 4.6.7 of our iOS app.
