### ISSUE TITLE
Device unreachable. Not automatically reconnecting unlike WhatsApp Web and Signal Desktop

### ISSUE THREAD

**Issue by orschiro** [threema-ch/threema-web#1047]
Hey guys!

I have WhatsApp Web and Signal Desktop and both reconnect just fine. 

However, Threema doesn't.

At some point (after airplane modes, standby/hibernation, reconnection of wifi, etc), it just shows me the device unreachable message without reconnecting by itself which WhatsApp Web and Signal Desktop can without any issues.

Is this a specific problem just on my end or are more people affected here?

On my Android, all these three apps have the exact same settings regarding battery optimisation, internet access, etc.

Also no difference for them on my laptop. They all run inside the same browser, except for Signal Desktop obviously, which is a separate app.

Any insights are appreciated, thanks!

![Screenshot_2021-03-19_09-01-50](https://user-images.githubusercontent.com/170947/111749745-82715400-8892-11eb-9afa-74cf1b57651a.png)

**Comment by samuelT2** [comment]
Same for me (iOS user). Whereas I cannot recognize any pattern - it just disconnects from time to time (or shows a red bar on top instead of a green bar). F5, re-entering the pin and the app reloads. Bit annoying though.

**Comment by orschiro** [comment]
Thanks, Joel!

Bummer this didn't help at all.

Looked at the FAQ.

All these recommendations I already use on my Samsung Galaxy.

Battery optimisation is disabled and background data use enabled.

Guess I need to wait for the proper desktop client then...

**Comment by dbrgn** [comment]
Samsung is the worst 🙂

Did you already check out https://dontkillmyapp.com/? You could also try installing [their app](https://play.google.com/store/apps/details?id=com.urbandroid.dontkillmyapp) to diagnose whether backup activity works or not.

**Comment by orschiro** [comment]
@dbrgn good thinking!

Tried the app and the problem doesn't seem to come from my phone. 100% after 8 hours of testing:

```
DontKillMyApp Ergebnis

SM-A320FL (a3y17lte) by samsung, Android 8.0.0

TOTAL
100%

WORK
100%

MAIN
100%

ALARM
100%

DURATION
8:00:00
```

**Comment by dbrgn** [comment]
Are you familiar with the browser developer tools (F12)? You could also keep the network tab open. When Threema Web tries to wake up a device, you can observe the requests against the push server. If these are responded to with a HTTP 204 response code, that means that the push message was successfully delivered to the Google/FCM push server.

![2021-03-21-124205_343x58_scrot](https://user-images.githubusercontent.com/105168/111903535-066a3e00-8a43-11eb-9afb-bb8649e572c0.png)

**Comment by lgrahl** [comment]
I think we should take a step back here. There is no retry button which would indicate that the desktop/notebook has connectivity issues and not the smartphone. Therefore, I'd classify it as a support case and recommend sending a log to *SUPPORT (_Troubleshooting_, next to _About_ in the footer) once this happens.

**Comment by orschiro** [comment]
@lgrahl just submitted!

**Comment by lgrahl** [comment]
From the log you've sent, we can see that there were a dozen of automatic reconnections, so it does mostly work as one would expect it to. At the very end of the log, sending of the push fails (I'm assuming due to connectivity issues/no network connection on the notebook) and that tripped the state machine into something it could not recover from. Hence the *reload* dialog.

So, I can only refer to the usual hints:

- Keep your phone connected to a charger
- Ensure good network connectivity on both devices

I can understand that this is dissatisfying but we will not mess with the state machine any more since it would be too much work and we're strongly focusing on the replacement of Threema Web instead.

**Comment by orschiro** [comment]
Understood, looking forward to Threema Desktop then!
