### ISSUE TITLE
No mobile notifications while on Threema Web

### ISSUE THREAD

**Issue by ranguwud** [threema-ch/threema-web#107]
## Expected Behavior
New messages should be displayed on the mobile device as notification, as long as they are unread in Threema Web. If configured, also the status LED should indicate an unread message.

## Current Behavior
When logged into Threema Web, any incoming message will create a sound/vibration on the mobile device. A notification is very briefly shown on the mobile device, but vanishes immediately after, thus leaving no trace of the unread message without opening the app. The status LED remains dark. This is particularly impractical e.g. when leaving the computer for a break and only locking its screen but not logging off Threema Web.

## Possible Solution
Users think differently about the level on notification on the mobile device, so an option in the app to turn mobile notifications on or off while using Threema Web would be ideal.

## Steps to Reproduce (for bugs)
1. Open Threema Web and connect to mobile device.
2. Optional: Leave Threema Web unattended, e.g. by switching tab, leaving the browser or locking the screen.
3. Have a message sent to you.
4. Notice that the mobile device will vibrate/play a sound but that it won't show any notifications.

## Your Environment

* Threema Web version: 1.0.3
* Threema for Android version: 3.01.2000340
* Threema for Android source: Play Store
* Browser name and version: Firefox 51
* Operating system and version: Windows 7

**Comment by rugk** [comment]
Actually I am not experiencing the "current behaviour" you describe. (I cannot reproduce step 4) Threema displays notifications on both devices and these are only hidden when the message is read on one of the devices. And I think this is how it is supposed to be.

**Comment by ranguwud** [comment]
This discrepancy is quite weird then. I can reproduce "current behavior" on an entirely different computer with an entirely different mobile phone (one phone with Android 6, one with Android 5). Since apparently "expected behavior" is more or less what you already intend to do and since I briefly see a notification on the phone, might this mean that Threema Web just marks any message as read immediately, regardless of whether it is active or not? How could this be tested?

**Comment by rugk** [comment]
You should see whether the message is read in Threema Web, obviously. It's marked just as in the app.

**Comment by dbrgn** [comment]
Right now incoming messages are marked as unread in Threema Web if they're in the active conversation and if they're visible inside the conversation viewport. We don't do any checking whether the browser tab is active or whether the screen is locked. I'm not sure to which degree that is even possible, but we'll check it.

When having seen a message on Threema Web, that flag is first transferred to the phone. The phone marks the conversation as read, and then syncs that state back to Threema Web. There are no separate unread states in the app and on the web client.

@ranguwud is your feature request a duplicate of #21, or did you mean something different?

**Comment by ranguwud** [comment]
@dbrgn After some more more testing, I can confirm your description. The problem is indeed that the chat is still visible, but the Tab is not in focus. I think it **is** possible to do such checks, since WhatsApp seems to be able to do it as well. Since the error report has now changed quite a bit, I will close this issue and open a new one for clarity.
