### ISSUE TITLE
Protocol Error

### ISSUE THREAD

**Issue by nona00** [threema-ch/threema-web#1070]
## Bug Description

While using Threema Web, the connection is sometimes lost and Threema Web is unable to reconnect. Protocol error is shown.

## Steps to Reproduce (for bugs)

![threema](https://user-images.githubusercontent.com/3192606/120798404-9b0e1380-c53d-11eb-944b-2a53a8aae9f4.PNG)

1. issue sometimes appears while using threema web
2.
3.
4.

## Your Environment

* Threema Web version: 2.3.13
* Threema App version: 4.6.8 (2628)
* Browser name and version: Firefox 78.11.0esr (64-Bit)
* Computer operating system and version: Windows 10 20H2 (x64)
* Smartphone operating system and version: IOS 14.4.2

**Comment by lgrahl** [comment]
Please contact *SUPPORT for this.
