### ISSUE TITLE
[SUPPORT] Where is threema's backend?

### ISSUE THREAD

**Issue by jbis9051** [threema-ch/threema-web#1101]
I was wondering where the code for the Threema ID generation is? Or more generally where is the source code for the entire backend? I cannot seem to find it in any of the GitHub repositories. 

If the backend is not open-source, it very much should be for both security reasons and in spirit of Threema's [dedication to open source](https://threema.ch/en/open-source).

Firstly, much of the security discussed in the white the [Threema whitepaper](https://threema.ch/press-files/2_documentation/cryptography_whitepaper.pdf) relies on the security of the backend. While message encryption is not dependent on the server, many things such as the security of (hashed) emails and phone numbers of both the user and all of their contacts rely on how the server handles the data. The whitepaper even acknowledges this stating

> Due to the relatively low number of possible phone number combinations, it is theoretically 
possible to crack hashes of phone numbers by trying all possibilities. This is due to the nature 
of hashes and phone numbers and cannot be solved differently (using salts like for hashing 
passwords does not work for this kind of data matching). **Therefore, the servers treat phone 
number hashes with the same care as if they were raw/unhashed phone numbers. Specifically, 
they never store hashes uploaded during synchronization in persistent storage, but instead 
discard them as soon as the list of matching IDs has been returned to the client**.

How can we, as users, be sure our data is being handled properly without being able to view the source?

Furthermore, Threema ID generation specifically should open sourced. According to the white paper a Threema ID is an extremely low entropy random string

> The server stores the public key and assigns a new random Threema ID, consisting of 8 
characters out of A-Z/0-9

This translates to log2(36^8) or about 41 bits of entropy. Specific care must be taken to prevent duplicate IDs from being generated (as discussed [here](https://soatok.blog/2021/11/05/threema-three-strikes-youre-out/#threema-ids)). Threema has [responded](https://www.reddit.com/r/Threema/comments/qn870u/threema_three_strikes_youre_out/) stating

> While the key is generated on the end device, the Threema ID is assigned by the directory server, which ensures that the IDs remain unique. There are proper rate limits in place to avoid denial-of-service, the birthday problem is not an issue here.

However, yet again we have no way to verify these claims.

There are many other ways the security of the backend server can effect security as noted in the whitepaper.

While there are two public audits, **neither** of them actually audited the backend code. 

[2019 Audit](https://threema.ch/press-files/2_documentation/security_audit_report_threema_2019.pdf)

> The goal of this audit was a thorough third-party examination of the source code of the Threema apps 
on both iOS and Android for possible issues that could affect the security or the privacy of its users 
and to check the validity of Threema’s public claims stated in the Threema Cryptography Whitepaper1

[2020 Audit](https://threema.ch/press-files/2_documentation/security_audit_report_threema_2020.pdf)

> Penetration-Tests & Code Audits against Threema Mobile Apps for Android & iOS

It seems nobody has seen the backend code other than Threema themselves. This is quite odd for an open source project.

Threema's [website](https://threema.ch/en/open-source)  states:

> What’s better than trust? Transparency.

I agree. Please be transparent and open source the backend and Threema ID generation.

**Comment by lgrahl** [comment]
We can happily discuss this on Reddit. You can also directly contact the support. Or via Twitter. This isn't to brush off the question and there are many viable channels but the Threema Web issue tracker is definitely not the right place which I'm sure you will understand.

**Comment by jbis9051** [comment]
Fair enough. Thank you!
