### ISSUE TITLE
[Desktop] Update available notification cannot be associated with Threema

### ISSUE THREAD

**Issue by myphs** [threema-ch/threema-web#1102]
![grafik](https://user-images.githubusercontent.com/12158101/146661491-d24969c7-366e-416d-bd55-badd4d5fdcca.png)

You cannot know from which program this notification is coming. There should be a clear sign, that this is in fact a window created by Threema.

## Potential Solution

Add the logo to the window and put Threema somewhere.

**Comment by threema-jarem** [comment]
Thank you for your report!

We fixed this with version 1.1.0 of Threema for Desktop and this commit: https://github.com/threema-ch/threema-web-electron/commit/3586bce9e739d3ab84778fb8de6b300ee204bd74
