### ISSUE TITLE
Session closed by protocol error

### ISSUE THREAD

**Issue by thettenhausen** [threema-ch/threema-web#1108]
## Bug Description

When I open an existing session in Threema Web that had not yet experienced any errors like this I now get the following "popup" around 2 or 3 seconds after the session has restored itself:

**Session Closed
The session was stopped due to a protocol error.**

I cannot really find any specific thing I did, like send a big video file or anything.

## Steps to Reproduce (for bugs)

1. load https://web.threema.ch/
2. click on Reconnect
3. wait a bit or click around between chats

## Potential Solution

Forgetting the session "solved" this. Still reporting it since I only found very old bug reports like this from 2019 that indicated it should not happen after version 4.4.0, and well, here we are :)
So yes, I cannot exactly reproduce it, but the general problem might still exist somewhere in the code. 

As such: please feel free to close if uninteresting since I cannot reproduce it and/or because you are working on a successor to the current web app.

## Your Environment

* Threema Web version: 2.3.19 Säntis
* Threema App version: 4.6.15 (2685)
* Browser name and version: Firefox 96.0.3 / 64
* Computer operating system and version: Windows 10 / 64
* Smartphone operating system and version: iOS 15.2.1

**Comment by threema-danilo** [comment]
Version 4.7 of the iOS app went into beta yesterday, it improves various aspects related to Threema Web. If you're interested in beta testing, please send an e-mail to help@threema.ch with a link to this issue!
