### ISSUE TITLE
Cannot click on empty end of input

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#111]
## Expected Behavior

Allow me to click in the input field there.

## Current Behavior

I cannot click there, also the cursor is a usual pointer and no text cursor.

## Steps to Reproduce (for bugs)

![](https://i.imgbox.com/R4vtEq18.gif)

Text:
```
fdsfdsf
sdsad dsdddddddddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddfdfds
dsdssdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsdddddddddddddddddsdsad dsddddddddddddddddd
```

## Your Environment

* Threema Web version: 1.0.3
* Browser name and version: Firefox 51.0.1
* Operating system and version: Debian 8

**Comment by dbrgn** [comment]
Reproduced in Firefox 51. This only happens when the text is big enough for the scroll bar to appear though.

Bug does not occur in Chromium, only in Firefox.
