### ISSUE TITLE
inserting emojis from keyboard

### ISSUE THREAD

**Issue by codestumbler** [threema-ch/threema-web#1113]
On threema desktop it would be amazing to insert emojis from the keyboard. 
a suggestion is to open the emoji context menu with their identifier strings when hitting the colon key, with subsequent regex-ing. E.g. :wink+enter produces :wink: 
Thanks and keep up the good work!

**Comment by threema-danilo** [comment]
If you hover over an emoji in the selector, you can see its shortcode.

In the compose area, simply type that shortcode (e.g. `:smile:`) and it should get replaced. Does this cover your feature request?

**Comment by threema-danilo** [comment]
(We simply don't have autocompletion for this feature. That's tracked in #433.)

**Comment by codestumbler** [comment]
Sorry i didn´t see #433. Yeah, that covers it, thanks!
