### ISSUE TITLE
Firefox: PDFs are opened in same tab

### ISSUE THREAD

**Issue by threema-danilo** [threema-ch/threema-web#1118]
## Bug Description

In current versions of Firefox, when clicking on a PDF file, it is not downloaded, but instead opened in the same tab. This affects both current and old version of Threema Web, I suspect this was caused by a behavioral change in newer Firefox versions.

* Threema Web version: 2.3.19
* Browser name and version: Firefox 98.0.1

**Comment by lgrahl** [comment]
Happens on a lot of pages, so I'm not even sure we should do anything about it.

**Comment by lgrahl** [comment]
Found this so far: https://bugzilla.mozilla.org/show_bug.cgi?id=1759835

**Comment by threema-danilo** [comment]
A potential workaround is downloading PDF files using the media type `application/octet-stream`, one of our support staff said that this seems to help. It's a ugly hack for a problem in Firefox, but if it works it might be a valid workaround.

I'll take a closer look this afternoon. We're using a method that should *always* result in a download, so I suspect that Firefox is doing something wrong here. If I can confirm that, I'll comment on the Bugzilla ticket.

**Comment by lgrahl** [comment]
Found another longer discussion we might want to chime in: https://bugzilla.mozilla.org/show_bug.cgi?id=1756980#c5 (sigh, blaming bad UX while not even knowing the use case, like SPA with state in memory... come on)

**Comment by threema-danilo** [comment]
Ugh, so they _intentionally_ ignore the `download` attribute and `Content-Disposition: attachment`? https://bugzilla.mozilla.org/show_bug.cgi?id=1756980#c7

**Comment by lgrahl** [comment]
It may be worth investigating whether using [modern DOM APIs](https://github.com/eligrey/FileSaver.js#saving-file) results in the same issue. I don't think we need to use `file-saver` - our browser requirements are high enough.

**Comment by threema-danilo** [comment]
> We're using `file-saver` which uses `target=_blank`, so this would be the most fitting bug I guess: https://bugzilla.mozilla.org/show_bug.cgi?id=1759916

file-saver uses a lot of different approaches depending on the browser: https://github.com/eligrey/FileSaver.js/blob/master/src/FileSaver.js In our case (Firefox) an approach with `a.href = URL.createObjectURL(blob)` followed by `click(a)` is used.

Fun fact from bugzilla 1756980:

> This also happens on WhatsApp web now. PDF files are opened in the same tab, although pressing the back button does re-logins the users. But I think this shows that this behavior is not expected.

For now, I'll add the ugly `application/octet-stream` workaround hack for Firefox, which does seem to work.

**Comment by dbrgn** [comment]
For the record, the change was finally reverted in Firefox 103: https://bugzilla.mozilla.org/show_bug.cgi?id=1756980#c71
