### ISSUE TITLE
List myself in group members

### ISSUE THREAD

**Issue by glaseyer** [threema-ch/threema-web#1122]
in a group with 4 members, i only see 3. it took me e few secounds to figure out, the missing person was myself. even it is logic, i'm in the group wihtout showing it. it would be nice to be listed.
thank you

**Comment by threema-danilo** [comment]
When reporting a bug, please use the bug report template.

We need the following information:

* Threema Web version
* Threema App version
* Smartphone operating system (Android or iOS)

In the mobile app, are you listed as part of the group in the group details?

**Comment by glaseyer** [comment]
![tre](https://user-images.githubusercontent.com/51176282/163856820-1e8ea346-1e6e-4217-94ee-d087736416aa.png)

Windows & FireFox 99.0.1 , I'm not listed ❌ ->Atached Printscreen (Version 2.3.20 Säntis)

under IOS on ma Iphone, i'm listed as "ich" , German for me ✅

**Comment by threema-danilo** [comment]
This is an issue in the iOS app (which sends the list of members to Threema Web). The issue will be fixed in the next release of the app. Thanks for the report.
