### ISSUE TITLE
web app update - app closes

### ISSUE THREAD

**Issue by cybersteve79** [threema-ch/threema-web#1123]
I have just updated the web app and now it crashes immediately after I try and message someone. I have tried to delete the session from my phone and started a new one. I am on the latest update of Windows 11.

**Comment by threema-danilo** [comment]
I assume this is about the installed desktop application, and not the web version at https://web.threema.ch/?

In that case, please contact the support by contacting https://threema.id/*SUPPORT or by filling out the form at https://threema.ch/en/request/default?i_have_read_the_faq=1.

**Comment by cybersteve79** [comment]
Thanks
