### ISSUE TITLE
Threema Web does not display video thumbnail sometimes

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#113]
## Expected Behavior
Video gets displayed immediately.

## Current Behavior
Sent a video via Threema Android (was connected to Threema Web at the same time and had the chat open). Unfortunately, the video was not displayed on Threema Web. On the Android version everything has worked as expected.

**After** re-login with Threema Web it worked again.

[Screenshot](https://picload.org/image/rlaropoa/2017-02-28-215557_1366x768_scr.png)

## Your Environment
* Threema Web version: 1.0.3
* Threema for Android version: 3.01
* Threema for Android source: Play Store
* Browser name and version: Firefox 51.0.1
* Operating system and version: Lubuntu 16.04

**Comment by lgrahl** [comment]
I cannot reproduce this. May have been fixed a while ago.
