### ISSUE TITLE
Video sent as file instead of video

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#114]
## Expected Behavior
Threema Web should send video as video and not as file when "Send as file" is not checked.

## Current Behavior
On Threema Web I tried to send a video (.mp4) and **did not** check "Send as file". Nevertheless, the video was sent as file instead of a normal video.
Also in the Threema Android app, it got displayed as file instead of a video.

## Your Environment
* Threema Web version: 1.0.3
* Threema for Android version: 3.01
* Threema for Android source: Play Store
* Browser name and version: Firefox 51.0.1
* Operating system and version: Lubuntu 16.04

**Comment by dbrgn** [comment]
Closed in favor of #32.

**Comment by rugk** [comment]
What does such a "media bug" have to do with dates shown?

**Comment by dbrgn** [comment]
Oh, sorry! I closed the wrong issue :)

**Comment by ovalseven8** [comment]
It's not a feature but a bug, no? ;)

**Comment by dbrgn** [comment]
I'd say doing filetype detection on an uploaded file and sending it as video is a feature :)

**Comment by ovalseven8** [comment]
Well, it should already work, no? Why the option "Send as file" then?

**Comment by sillych** [comment]
It's a bug, will be fixed within the next app release
