### ISSUE TITLE
Build Instructions Don't Work for Windows 10

### ISSUE THREAD

**Issue by hugoender** [threema-ch/threema-web#1143]
## Bug Description

Build instructions on [Threema Github](https://github.com/threema-ch/threema-web-electron) do not work for Windows 10. 

If you try to use the `export` command, you get the following error: 'export' is not recognized as an internal or external command,
operable program or batch file.

If you ignore the export steps or use git-bash to allow you to use `export` the next issue you run into is that `npm run app:build:web` does not seem to create the `app/dependencies/threema-web/release` directory that it needs to create for the next step to work. So when you send `./tools/patches/post-patch-threema-web.sh` it gives the following error:  `./tools/patches/post-patch-threema-web.sh: line 10: cd: app/dependencies/threema-web/release/threema-web-2.4.1/: No such file or directory`

Please update the build instructions to include Windows specific instructions. 

## Steps to Reproduce (for bugs)

1. Open command prompt in Windows 10 and send `export DEV_ENV=development`. You will get the first error.
2. Switch to Git-Bash and then follow the remaining steps up until and including sending `npm run app:build:web`
3. Check for `app/dependencies/threema-web/release`  and notice that it's not there.
4. Move on to the next step and send `./tools/patches/post-patch-threema-web.sh` and get the second error stating the directory is missing.

## Your Environment

* Computer operating system and version: Windows 10

**Comment by hugoender** [comment]
Was able to use a Raspberry Pi to follow the steps up until and including `npm run app:build:web`. It worked fine on the Raspberry Pi and so I transferred the `release` directory it created to my windows machine and continued with the process. When I got to the last step and sent `npm run electron:package:$TARGET_PKG:consumer` I got the following Error:
![image](https://user-images.githubusercontent.com/6217175/179403908-062c57d1-29c3-4180-bec1-92f7733a95c5.png)

**Comment by threema-danilo** [comment]
We don't support Windows for building Threema Web. If you want to build Threema Web on Windows, use [WSL](https://docs.microsoft.com/en-us/windows/wsl/).

Also, your issue seems to be about Threema Desktop, not Threema Web?

Your issue might be that you forgot to clone recursively? Try `git submodule init` followed by `git submodule update`. If that doesn't help, please contact the support as suggested here: https://github.com/threema-ch/threema-web-electron#bug-reports-and-feature-requests

**Comment by hugoender** [comment]
This issue is indeed about Threema Desktop but the Desktop repo didn't have an Issues section and I didn't want to create yet another forum account so figured this was the next beset thing. Thank you for the suggestions. Will try WSL.

**Comment by hugoender** [comment]
Using Ubuntu WSL worked great! Thank you!
