### ISSUE TITLE
"Uncaught ReferenceError: WebAssembly is not defined" in Microsoft Edge

### ISSUE THREAD

**Issue by cluick** [threema-ch/threema-web#1148]
## Bug Description

After upgrading Microsoft Edge Browser to version 104.0.1293.63 (64-bit Windows) I cannot open Threema-Web any more. Before I used Threema Web in MS Edge for several months without problems. When I open https://web.threema.ch the following text is displayed:

> Error: Browser not supported
> You are using a browser without WebAssembly support. Please upgrade to the latest version of a [supported browser]> > >(https://threema.ch/faq/web_requirements).

The browser console shows error "Uncaught ReferenceError: WebAssembly is not defined" (complete log attached)

[web.threema.ch-1661248663912.log](https://github.com/threema-ch/threema-web/files/9401539/web.threema.ch-1661248663912.log)

I resetted the browser configuration and the browser cache but nothing helped.

## Steps to Reproduce (for bugs)

1. Update edge to version 104.0.1293.63

## Your Environment

* Threema Web version: n/a - I cannot open the page - no version number is displayed neither in the browser nor in the browser console
* Threema App version: 4.83 Build 3000755 Google Play
* Browser name and version: MS Edge 104.0.1293.63 64-bit 
* Computer operating system and version: Windows 10 Pro; 10.0.19044 Build 19044; 64 bit
* Smartphone operating system and version: Android 12

**Comment by threema-danilo** [comment]
Could it be the "Enable security mitigations for a more secure browser experience" setting?

- https://answers.microsoft.com/en-us/microsoftedge/forum/all/edge-970107269-this-browser-does-not-support/7aeaa4b7-43c0-4940-9551-fd3e80ea75e4
- https://github.com/microsoft/vscode/issues/137704

**Comment by cluick** [comment]
> Could it be the "Enable security mitigations for a more secure browser experience" setting?

Yeah, you are right. Disabling this option will make Threema-Web working again. Thank you! 🙏
