### ISSUE TITLE
Cannot send .webm video in video format

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#115]
## Expected Behavior
When sending a .webm file, it should be sent as normal video by default.

## Current Behavior
Cannot send a .webm file as a video, only as a file.

## Your Environment
* Threema Web version: 1.0.3
* Threema for Android version: 3.01
* Threema for Android source: Play Store
* Browser name and version: Firefox 51.0.1

**Comment by dbrgn** [comment]
Isn't this a duplicate of #114?

**Comment by ovalseven8** [comment]
No, because in #114 there is the choice between sending as "video" and "file".
Here I don't even have the choice and can only send as file.

**Comment by dbrgn** [comment]
I see. But they can both be summarized as "fix sending of videos" :)
