### ISSUE TITLE
Restore group images

### ISSUE THREAD

**Issue by xf-** [threema-ch/threema-web#116]
## Expected Behavior

Restoring a backup with media should include group images (set with group name).

## Current Behavior
After restoring a backup with lot of messages and media the group images (set with group name) are missing.

## Possible Solution
- Ignore age of group image and backup it.
- Allow sync, if i'm a member of the group.

## Steps to Reproduce (for bugs)

1. Create a group
2. "Spam" including media over couple of months
3. Create a Backup with media
4. Restore it
5. Group images are missing in active groups with many messages and media
6. Owner needs to set the image again.

## Your Environment
* Threema for Android version: Up2date
* Threema for Android source: Play Store

_I know this is not an issue of Threema-Web, but the support didn't understand the issue. Answer: I need to include media and images can't be restored. No reference to group images (set with name of the group). Maybe you could add a notice in internal issue tracker. THX 👍_

**Comment by dbrgn** [comment]
Thanks for the report. The best process in this case would be to let the support know that the problem hasn't been fixed, and to ask them to forward the report to a developer.

We have created an internal ticket for this problem though.
