### ISSUE TITLE
User Interface: Could not switch to "Minimal" user interface

### ISSUE THREAD

**Issue by wAmpIre** [threema-ch/threema-web#1163]
## Bug Description

Just got the update to 2.5.0 in my Firefox 102ESR. After Login the default user interface is in use. Switch to "Minimal" in "Settings" → "User interface" does... nothing, even after relogin/reload/cache clean.

## Steps to Reproduce (for bugs)

1. Login
2. Go to "Settings" → "User interface", change to "Minimal"
3. No change

Expected: Change user interface to minimal layout

## Your Environment

* Threema Web version: 2.5.0
* Threema App version: 5.0.2 Build 3000779 Google Play
* Browser name and version: Firefox 102.5.0esr
* Computer operating system and version: Debian Linux Testing
* Smartphone operating system and version: Oneplus 6, Lineage

**Comment by threema-danilo** [comment]
I cannot reproduce this issue in latest Firefox. The user interface setting is stored in local storage. Do you use some plugins that might block this?

Is there an error logged in the debug console (F12) when you change the UI setting?

**Comment by threema-danilo** [comment]
It's probably an issue with your Firefox profile that prevents use or persistence of local storage. To verify this, you could create a new profile: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles?redirectslug=profile-manager-create-and-remove-firefox-profiles&redirectlocale=en-US

There's not much we can do about this in Threema Web.
