### ISSUE TITLE
Big files won't upload

### ISSUE THREAD

**Issue by 64Yoshi64** [threema-ch/threema-web#1176]
## Bug Description

When trying to upload a big file (400MB) it won't work. Even when left for 30 minutes. It'll just keep loading, when with my speeds it should work way faster. (when uploading the same file from an android phone in the same network, it works flawlessly)

## Steps to Reproduce (for bugs)

![Screenshot 2023-06-26 222326](https://github.com/threema-ch/threema-web/assets/57725354/7e4c1605-9c2e-49f3-af7c-e96088efa70d)

1. Try to upload a big file
2. Wait
3. Nothing changes

## Your Environment

* Threema Web version: 2.5.1
* Threema App version: 5.0.5
* Browser name and version: Firefox 114.0.2 (64-bit)
* Computer operating system and version: Windows 11 22H2
* Smartphone operating system and version: Android 13

**Comment by threema-danilo** [comment]
The current file size limit for Threema is 100 MiB.

When trying to send larger files, this _should_ be prevented by the UI. I'll have to check if we can fix this easily.

**Comment by threema-danilo** [comment]
There was indeed a bug in the logic, the limits were not checked when using the Android app. This should get fixed with the next release (see #1179).

**Comment by 64Yoshi64** [comment]
Danka vielmol :)
