### ISSUE TITLE
Version 2.5.3's marking of read messages is incompatible with non-current Firefox versions

### ISSUE THREAD

**Issue by esrat** [threema-ch/threema-web#1191]
Hi,

the last update of Threema-Web did destroy the compatibility with non-current versions of the Android-app of Threema - within a non-current Firefox browser.
It does not send the correct information to mark the last messages as read when the user opens a chat, so they stay as "new" forever. Only when the user writes an answer, the new-messages-counter does disappear, at least in the Web-interface. But a newly received answer of the contact will not rise a "1" as indicator of this new message but a "n+1" where n is the number of messages which never were marked as read!
So, it's quite easy to reproduce.

It also completely confuses the Android app. The app will in fact keep the sum of all erroneously "unread" messages on the desktop-icon but within the app, the single chats will not show where those messages are!
The user has to manually look through all recent chats to restore a valid state of the Android app.

This bug was verified with the shop-version of Threema in:
- version 5.1.1 Build 909 and
- version 5.1.3 Build 919

The current workaround is to use version 2.5.2 of Threema-Web:
https://web.threema.ch/archive/2.5.2/

Additional information about the environment:
- browser: different versions of Firefox (e.g. ESR portable 91.2.0 and older)
- operating system of PC: different Windows-versions (e.g. Windows 7 professional 64 Bit, Windows 10 home 64 Bit)
- operating system of Smartphone: different versions of Android (e.g. Android 6.0.1)

**Comment by esrat** [comment]
From another test today, in which I could not reproduce the problem with the most current Firefox ESR (115.X), I came to the conclusion that this more likely a browser-problem!
I am still using a Firefox ESR 92 as my default browser and my friend an even older version. So I changed the topic of this bug report.

**Comment by threema-danilo** [comment]
The last release of Firefox ESR 91 is over 1.5 years old. You will be missing a lot of security updates and fixes.

Threema Web supports versions of Firefox currently supported by Mozilla (121, as well as the 115 ESR), in combination with the latest Android app. We _strongly_ recommend using an up to date web browser. Using outdated web browsers poses a big security risk.

The same counts for outdated operating systems that won't get security updates (Windows 7) as well as outdated Android versions that won't get security updates (Android 6).

**Comment by esrat** [comment]
I think, we all know the questionable practice of big and fast version-numbering. Only three weeks ago Firefox ESR 91 was the second to last "normal" version of this browser. So I do not consider it thaaat old.
There are people using Firefoxes as old as version 68 (not an example of this bug report) on a daily basis and won't update since the more modern versions won't be usable on their devices. For the same reason I will never get an Android update for my smartphone, because there is none available! (And I still won't throw it when all I want to do is chatting with friends.) --- Even today, you can use PCs and smartphones for more than two years. Just try it!

I accept that it is not practicable to keep applications backwards compatible forever. So I will keep running version 2.5.2 on FF ESR 92.
But it would have been helpful to mention this break in compatibility. (I did not find something within the change log, so I considered this being a bug.)
