### ISSUE TITLE
Support Firefox ESR

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#121]
## Expected Behavior

It would be good to officially support the extended support release (ESR) of Firefox, which is currently at version 45.

## Current Behavior

Firefox 45 is not supported so far because we didn't test it. However, I see no reasons why it shouldn't be possible. It seems to work fine.

## Possible Solution

After testing, simply set `BROWSER_MIN_VERSIONS.FF` from 47 to 45 in `src/app.ts`.

**Comment by dbrgn** [comment]
Pasting does not work in Firefox 45.

**Comment by rugk** [comment]
Should not this be fixed when you switch to feature detection?

**Comment by dbrgn** [comment]
As you see here:

> Pasting does not work in Firefox 45.

...there are some things that can't easily be detected. We need more testing before we can remove the warnings. Decreasing `BROWSER_MIN_VERSIONS.FF` would be an intermediate step.

**Comment by XS666** [comment]
Please fix this... I am using Firefox ESR on all my computers.

**Comment by dbrgn** [comment]
Blocked by #139.

@XS666 in the meantime, you can just ignore the warning. Most things should work.

**Comment by dbrgn** [comment]
Another blocker: Firefox ESR never notices if the WebRTC connection is lost. Connection is still reported as "up" in `about:webrtc`. Attempting to send data through the DC doesn't make a difference.

Steps to reproduce: Create a connection, kill the Threema app.

Not sure if this is something we can handle. If the bug persists, I don't see how we can support Firefox ESR.

**Comment by dbrgn** [comment]
Since the WebRTC connection bug persists, we will not be able to properly support Firefox 45. But the good news is that Firefox ESR 52 was released yesterday! https://www.mozilla.org/en-US/firefox/organizations/faq/

This means that we automatically support the current version of Firefox ESR, as of now. I would expect distributions like Debian to update their packages soon.
