### ISSUE TITLE
Desktop 2.0 beta cannot be finally be activated on WIN10 PC

### ISSUE THREAD

**Issue by ghost** [threema-ch/threema-web#1223]
## Steps to Reproduce (for bugs)
Repeat the installation and try to enter password

![2024-12-28](https://github.com/user-attachments/assets/30f620f7-dc9b-4264-b167-b62a53ad0ff5)

![2024-12-28](https://github.com/user-attachments/assets/e70a598a-1472-4ec7-8da0-c1a7e3a38ab3)

1.
2.
3.
4.

## Your Environment

* Threema Web version:
* Threema App version:
* Browser name and version:
* Computer operating system and version:
* Smartphone operating system and version:

**Comment by threema-danilo** [comment]
Hello, this is a very unspecific bug report, and it is also in the wrong issue tracker. As indicated in the [README for Threema 2.0 for desktop](https://github.com/threema-ch/threema-desktop/blob/stable/README.md), bug reports and support requests should go to the Threema Support, and not into the issue tracker for Threema Web.

(Your problem _might_ be that you're using the "Threema Work" app on desktop in combination with the "Threema" app for consumers on your mobile device. Make sure to use the right desktop app for your mobile app.)
