### ISSUE TITLE
When upload indicator disappears, show thumbnail immediately

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#123]
## Expected Behavior

When sending an image to a contact, as soon as the upload indicator disappears, the thumbnail should be visible.

## Current Behavior

Upload indicator appears, then disappears, and after a few seconds, the thumbnail is loaded.

## Possible Solution

- Send thumbnail together with "file sent" callback

**Comment by lgrahl** [comment]
The app always overrides the image since it may scale it, so I don't think this is feasible.
