### ISSUE TITLE
Show SaltyRTC connection status

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#13]
User story: As a Threema Web user I want to see how my Threema App and Web client are connected.

This includes:
1. Either using a direct connection (LAN) or routing over the server (TURN).
2. Whether my mobile data is used (fees or so…) or whether my LAN/WLAN is used.

It would be good to combine these two similar (but not exactly the same) pieces of information into one status symbol or so…
Number 1 is what security geeks or people experiencing reconnections/performance issues would like to see and 2 is what people in special situations (limited data plan, …) or people interested in this generally like to see.

-----

Appended from https://github.com/threema-ch/threema-web/issues/195:

User story: I, as a (heavy) Threema Web user, want to see what route the Threema Web connection uses (mobile data/WiFi, uses TURN?) in order to evaluate problems/slowness/security/high costs…

This helps to:
* avoid high costs when users have limited mobile data plans
* evaluate the security (TURN is probably not what I want to use)
* find reasons for slowness ("ah, mobile data and TURN, …") or disconnections ("oh, just switched to TURN")
* potentially debug things (when you can also see what TURN mode is used – in a submenu, of course)

### Potential solution
Display an icon in the "Threema Web" panel in the Threema app showing a basic connection status. And maybe add a context item ("Connection details" or the like) where advanced users can see a more detailed status. (maybe even with connection duration or so)

**Comment by lgrahl** [comment]
@dbrgn @sillych You should be able to retrieve this information from https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatestats

I disagree with *evaluation of security* though. There is nothing wrong with TURN-UDP without any further transport encryption in this use case.

**Comment by dbrgn** [comment]
> I disagree with evaluation of security though. There is nothing wrong with TURN-UDP without any further transport encryption in this use case.

I agree :)

**Comment by rugk** [comment]
Ah, yes. The only security difference I meant is: "using TURN servers as relay" vs "direct p2p"…
What turn mode does not matter – at least for security reasons…

**Comment by lgrahl** [comment]
Closing in favour of #829
