### ISSUE TITLE
Also hide tab glow and possibly desktop notification on read

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#131]
## Expected Behavior

When a message is read hide the desktop notification, if that's possible.
And when all messages are read, please also hide the tab glow, which is shown when a new message appears. Currently this glow is only hidden when you select the tab.

## Current Behavior

Once a message is received, then tab glow can only be hidden after clicking on the tab.

## Steps to Reproduce (for bugs)

1. Get a message.
2. Read it on your phone.

## Your Environment

* Threema Web version: 1.0.5

**Comment by dbrgn** [comment]
> please also hide the tab glow, which is shown when a new message appears

That is not possible as far as I know. The glowing occurs when the title text of the tab is changed.

**Comment by rugk** [comment]
And when you change it back, this does not revert the glow?

**Comment by dbrgn** [comment]
If we change it back, the wrong number of unread messages is in the title.

**Comment by rugk** [comment]
I don't think so. Only change it back when there are no unread messages anymore, so all message are read (0 unread).

**Comment by dbrgn** [comment]
> And when you change it back, this does not revert the glow?

According to my tests, no.
