### ISSUE TITLE
Send files larger than 15MiB

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#133]
## Expected Behavior

Files with size up to the limit specified by the app should be sendable through Threema Web.

## Current Behavior

Limited to 15 MiB.

## Possible Solution

https://github.com/saltyrtc/saltyrtc-task-webrtc-js/issues/9

**Comment by ovalseven8** [comment]
Duplicate of #7?

**Comment by dbrgn** [comment]
> Duplicate of #7?

Haha, thanks :) :+1:
