### ISSUE TITLE
Session password does not work to reconnect

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#14]
Steps to reproduce:

1. Go to https://web.threema.ch
2. Use a session password, I used `MH:cp-+{_;2p*}=E`
3. Everything works fine so far
4. Close session
5. Try to reconnect with the same password
6. Threema Web says I use the wrong password! :x:

For me, it worked with an easier password. Perhaps Threema has problems with special characters?

**Comment by dbrgn** [comment]
I cannot reproduce this, your mentioned password works fine for me.

Do you maybe use a browser plugins to fill the form? If yes, does it work when pasting in the password manually?

**Comment by ovalseven8** [comment]
Odd. I did some further testing and everything works fine now.

Perhaps I deleted some browser data by accident.
So, everything should be ok. :)
