### ISSUE TITLE
Emojis should be the same on App(s) and Webapp

### ISSUE THREAD

**Issue by FloThinksPi** [threema-ch/threema-web#146]
## Expected Behavior

Emojis should look the same on Webapp and App. This will prevent inconsistency in what was written since the user sees that his message at the App differs from the message he wrote on the Webapp.

## Current Behavior

Emojis look quite different and in my opinion often express different feelings. When sending someone a message at the Webapp and he is viewing it at the app, the original intention may not be expressed as intended by the writer. ( Dont know how this looks on Apple Devices )

App:
![App](https://cloud.githubusercontent.com/assets/5863788/23699451/75d72eee-03ef-11e7-94fa-17554482a444.png)
Webapp:
![Webapp](https://cloud.githubusercontent.com/assets/5863788/23699450/75d57be4-03ef-11e7-85bb-e7031bc276e6.png)

As you see e.g. the Sleeping emoji seems more sick on the Webapp, Poo is smiling at at the app and has a surprised face at the Webapp etc.

## Possible Solution

Use the same set of Emojis on Webapp and App.
(i personally like the Emojis on the Webapp more 😋  )

## Your Environment

* Threema Web version: 1.0.5
* Threema for Android version: 3.11.2000344
* Threema for Android source: Play Store
* Browser name and version: Chrome Version 56.0.2924.87 (64-bit)
* Operating system and version: Windows 10

**Comment by mimiks** [comment]
Emojis look different across operating systems and even across operating system versions. So the different expressions/feelings are a fact we will probably have to live with for the time being.

We may harmonize the built-in emoji sets at some time in the future. Unfortunately, the current EmojiOne set used in Threema Web works well on the big screen but does not look too good on small screens.

**Comment by dbrgn** [comment]
Also, we cannot include Apple emoji in Threema Web and distribute them under an open source license since the licensing situation is very unclear.

**Comment by rugk** [comment]
FYI in iOS it uses the Apple emoticons, of course. These are also used in the Threema app on Android.

**Comment by dbrgn** [comment]
What @mimiks said.
