### ISSUE TITLE
Threma 3.0 App is not available at Threema Shop

### ISSUE THREAD

**Issue by pgollor** [threema-ch/threema-web#15]
Sorry for posting this issue here, but the support system on threem.ch does not work.
The threema Android App Version 3 is not available at https://shop.threema.ch/download and my current App (from Threema Shop) say: `no update available`

Thanks for fixing this.

**Comment by sillych** [comment]
will be available in the next few hours... :tada: please be patient

**Comment by rugk** [comment]
> but the support system on threem.ch does not work.

Next time maybe try threem**a**.ch… :wink: Just kidding…
