### ISSUE TITLE
Closing the about dialog causes TypeError

### ISSUE THREAD

**Issue by IndianaDschones** [threema-ch/threema-web#153]
## Current Behavior

Closing the about dialog causes `TypeError: this.resumeFocusOnClose is not a function`

## Possible Solution

Override the `resumeFocusOnClose()`-function when creating the dialog.

## Steps to Reproduce (for bugs)

1. Open the about dialog (Overflow -> About)
2. Close it (X or Close). ~~It doesn´t matter how you close it (X, Close, clicking outside)~~ Clicking outside does not throw the error
3. The TypeError appears in the console

## Your Environment

* Threema Web version: 1.0.5

**Comment by dbrgn** [comment]
Looks like TypeScript doesn't prevent us from accidentally instantiating abstract classes :)
