### ISSUE TITLE
Markup behaves different than app

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#156]
## Expected Behavior

Markup should behave identical to the Android app.

## Current Behavior

The app does not apply formatting to multi line strings, web does.

Example:

```
*foo bar
baz cyberkrimi*
```

This is bold in web but not in the app.

## Possible Solution

We should probably do it like the app, since a user on a mobile will probably not use manual line breaks when creating formatted text.

The regex actually matches for `[^\r\n]`, but newslines are apparently still matched. Maybe this is due to the conversion of newlines to HTML, or simply a JavaScript idiosyncracy.

Adding tests for this would be good, to prevent regressions.

**Comment by IndianaDschones** [comment]
>  Maybe this is due to the conversion of newlines to HTML

@dbrgn You're absolutely right. You can also see that the preview text is formatted correctly (without escapeHtml filter) and the chat text isnt.

My debug log also confirms this:
`Before markify: *Ach*<br>*Ab<br>Jetzt*`
`After markify: <span class="text-bold">Ach</span><br><span class="text-bold">Ab<br>Jetzt</span>`

I self-assign me to solve this.
