### ISSUE TITLE
Add "delete all sessions" Button to Threema Web Menu

### ISSUE THREAD

**Issue by Buddabread** [threema-ch/threema-web#157]
## Expected Behavior
Would be nice to have a Method that is triggered by a Button which can remove any sessions (expect the active one) from the mobile Device (Android).

## Current Behavior
Often I'm lazy and start always a new Session by scanning the QR-Code of Threema-Web.
The Menu is now full of inactive Threema Web sessions, so every single one must be manually deleted to clean up the view.

## Possible Solution
Please implement a Method, represented through a Button or a Menu entry, which removes all inactive Sessions.

**Comment by dbrgn** [comment]
> Often I'm lazy and start always a new Session by scanning the QR-Code of Threema-Web.

If you don't enter a password, the sessions will disappear once you disable Threema Web in the app. Does that already solve your issue?

**Comment by Buddabread** [comment]
Restoring a session with password is just a few minutes after disconnect possible.

**Comment by dbrgn** [comment]
> Restoring a session with password is just a few minutes after disconnect possible.

What do you mean? Sessions should not expire, if you set a password for them.

**Comment by Buddabread** [comment]
I made following tests:

1. Open web.threema.ch
2. typed a password
3. open Threema on android 
4. start Threema web session, by hitting the + Button.
-----> Threema Web is working fine.
5. Restarting the Browser.

Now I have this view:

![threema-web](https://cloud.githubusercontent.com/assets/25779508/24866746/634d36ac-1e0b-11e7-94fc-1729894b4aad.JPG)


It seems that the restarting process of Firefox kills the Threema session, so I'm not able to reconnect it again.


Firefox: 52.0.2 (32-Bit)
Android: Version 3.13.346 Threema Shop

**Comment by dbrgn** [comment]
Try this: https://threema.ch/en/faq/web_browser_settings (or in German: https://threema.ch/de/faq/web_browser_settings).
