### ISSUE TITLE
™ (TM) is converted to Emoticon

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#158]
## Expected Behavior

When `™` is sent/pasted/shown just show it as a text. Only show it as an Emoji when it is an actual Emoji.

## Current Behavior

When `™` is sent/pasted/shown it is always converted to the Emoji…

## Possible Solution

Same as you did on the app, which also had this bug, but AFAIK it's now fixed…

## Steps to Reproduce (for bugs)

1. `™` sent/paste/view received message

## Your Environment

* Threema Web version: 1.0.5

**Comment by dbrgn** [comment]
As far as I know, the ™ sign and the :tm: emoji are the same codepoint: https://www.emojibase.com/emoji/2122/trademarksign As as long as we support pasting emoji, we cannot differentiate between "paste this characters using a regular text font" and "paste this character using an emoji font".

PS: At least on Android, pasting the `™` symbol results in the emoji too.

**Comment by rugk** [comment]
> At least on Android, pasting the ™ symbol results in the emoji too.

Ouh, have not noticed this. I thought it was fixed, once…

**Comment by dbrgn** [comment]
> Ouh, have not noticed this. I thought it was fixed, once…

How would you fix this, if it's the same codepoint and if pasting emoji is supported?

**Comment by rugk** [comment]
I've no idea…
