### ISSUE TITLE
Translate meta description

### ISSUE THREAD

**Issue by IndianaDschones** [threema-ch/threema-web#168]
The `meta description` added in #124 should also be translated.

I self assigne me.

**Comment by rugk** [comment]
BTW every time you say you self-assigned yourself, you actually did not do it. There is still no one assigned to this issue.

**Comment by dbrgn** [comment]
> BTW every time you say you self-assigned yourself, you actually did not do it. There is still no one assigned to this issue.

He can't, since he's not a project member. He's simply following the [contributors guideline](https://github.com/threema-ch/threema-web/blob/master/CONTRIBUTING.md#1-claim-an-issue).

@IndianaDschones thanks for the PR :)
