### ISSUE TITLE
Threema Web does not necessarily show number of unread messages

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#17]
Steps to reproduce:

1. Open https://web.threema.ch
2. Write a message to i.e. `ECHOECHO`
3. Switch to another (browser) tab *immediately*
4. You can see that the tab's title has changed from `Threema Web` to `Threema Web (1)`. However, because in this tab the chat with `ECHOECHO` is open, it will be marked as read. So, after about a second you read `Threema Web` again and you cannot see that you have unread messages. If the chat with `ECHOECHO` is not open, everything works as expected.

I am not sure if it's technically possible, but messages should only be marked as read when they are *really* read (in the sense of I look at the chat). Otherwise, I cannot see if I got any message.

**Comment by rugk** [comment]
@dbrgn not "bug"?

**Comment by luminatedhorizons** [comment]
Excellent description, thanks for that. Since in this scenario, incoming messages are marked as "read/seen" before even only the tab of Threema Web has been shown on the screen, I would maybe go as far to call this a "bug", no?

**Comment by dbrgn** [comment]
To repeat my comment from #108:

Related discussion: https://github.com/thenikso/angular-inview/issues/111
