### ISSUE TITLE
Feature: Browser notification when going disconnected and reconnect fails

### ISSUE THREAD

**Issue by fichtennadel** [threema-ch/threema-web#174]
It would be helpful, if threema web would show a (browser) notification, if it loses the connection to the app and can't reconnect automatically.

**Comment by rugk** [comment]
But please make it optional.

**Comment by sillych** [comment]
if a session disconnects and does not reconnect, its a bug and should be fixed. the notification does not solve the problem...

**Comment by fichtennadel** [comment]
I disagree. It's not necessarily a bug: network outage, app closed by Android, ...

The notification is not meant as a solution but as a ... notification, so the user knows something is wrong and a manual check or reconnect has to be done.

**Comment by sillych** [comment]
true!

**Comment by lgrahl** [comment]
Agree. Very useful if the device is left at home for example.

**Comment by fichtennadel** [comment]
Is this on some roadmap? 

It's currently really annoying that a connection loss is not notified in the browser. I have my phone muted in the office and if Threema web loses the connection, I don't get any notifications at all for new messages. 

With a notification from the browser for the connection loss, I could check and reconnect.

**Comment by lgrahl** [comment]
This will become moot with #498

**Comment by dbrgn** [comment]
You're right, let's focus our efforts on #498 instead.
