### ISSUE TITLE
Location link can not be clicked

### ISSUE THREAD

**Issue by IndianaDschones** [threema-ch/threema-web#181]
## Expected Behavior

Clicking on a location-link should work
## Current Behavior

Link is not reachable/can not be clicked.
## Solution

Hide the `in-view-indicator` on locations

I´ll solve this.

**Comment by IndianaDschones** [comment]
By the way: I think the POI-message looks strange. The "normal" textline is redundant.

![poi](https://cloud.githubusercontent.com/assets/6652142/24034845/420f6a76-0af3-11e7-8b8f-4bd31b8b427a.PNG)

I think it should look this way
![poi_new](https://cloud.githubusercontent.com/assets/6652142/24034891/58e04c7a-0af3-11e7-9382-baf746066cc7.PNG)

It could also contain the `location_on` symbol above or maybe in the grey circle like the other media messages.

What do you think? I could also include these changes if you want 😄

**Comment by dbrgn** [comment]
@IndianaDschones feel free to change the appearance of the location message. it hasn't received too much attention from us so far, it's almost the same as in the first prototype :)
