### ISSUE TITLE
rotate Plus Button 

### ISSUE THREAD

**Issue by N3dal** [threema-ch/threema-web#182]
To have a similar UI in the Webclient and the App it would be a nice little feature if the Plus button ( for adding contacts, chats, etc. ) is rotating into a "X" when the menü is opened, like it is in the App. ( + -> x ) 

![bildschirmfoto vom 2017-03-18 11-26-39](https://cloud.githubusercontent.com/assets/23279917/24071259/fc175d86-0bcd-11e7-81bb-453affbcd8a0.png)

**Comment by dbrgn** [comment]
Pull requests welcome.
