### ISSUE TITLE
Add github templates

### ISSUE THREAD

**Issue by xf-** [threema-ch/threema-web#19]
Add templates for
- CONTRIBUTING.md (linked on create issue and pr page e.g. include CLA information)
- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md

Small generator for issue and pr
https://www.talater.com/open-source-templates/#/

Example/GitHub
https://github.com/TalAter/open-source-templates/issues

GitHub feature info
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by rugk** [comment]
LOL the issue template is funny: Threema app source: Pirate Bay😂😂
Seriously Threema?😁
