### ISSUE TITLE
Adding Threema ID is not nice

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#192]
## Expected Behavior
1. Would not an overlay/popup be enough. Is really the whole big thing necessary?
2. <kbd>Enter</kbd> should continue…

## Current Behavior
A big empty space/area is taken for this tiny input field.

![grafik](https://cloud.githubusercontent.com/assets/11966684/24368260/0b87af6a-1320-11e7-9bae-6c20d7fd811b.png)

And I have to click on this tiny tick on the right top to continue, <kbd>Enter</kbd> not possible.

## Steps to Reproduce (for bugs)

1. Click on the button to add a new Threema ID:
2. Enter ID.

## Your Environment

* Threema Web version: 1.1.0

**Comment by dbrgn** [comment]
A modal dialog is tricky because it has a different context and needs to be closed when navigating away.

The current approach is more consistent with the rest of the navigation.

Pull requests with UI improvements are welcome.

**Comment by ovalseven8** [comment]
It really does not look nice.
