### ISSUE TITLE
Emoji skin color selector

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#196]
## Expected Behavior

Group the Emojis somehow, so 

## Current Behavior

All skin colours in one list…

## Possible Solution

Use some selector as EmojiOne does it (top right):
![diversity](https://d1j8pt39hxlh3d.cloudfront.net/thumb2.png)

Live example here: https://www.emojicopy.com/

Or Twitter:
![grafik](https://cloud.githubusercontent.com/assets/11966684/24853301/e7f4ec96-1dda-11e7-8509-5b9ff7fe256e.png)

**Comment by Kurisutian** [comment]
With the new Emoji One set introduced in Threema Web 1.3.0 this is more useful than ever. It is getting harder to scroll and find an emoji with the huge list including all colors the same time. This would really improve usability big time. ;)

**Comment by dbrgn** [comment]
Yes, a selector would be useful. Right now there are a few things with higher priority though.

If someone wants to give it a stab, the script that generates the emoji picker HTML is [here](https://github.com/threema-ch/threema-web/blob/master/tools/emojione/generate-emoji-picker.py).

Pull requests are welcome, although the concrete implementation (design approach) should probably be discussed first.
