### ISSUE TITLE
Laggy UI

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#20]
Threema Web is sometimes a bit laggy. I have got around 30 contacts and the UI sometimes is a bit slow.
I can especially see it when (fastly) opening the context menu of messages:

![lagy](https://cloud.githubusercontent.com/assets/11966684/22984539/f1ebaeb0-f3a5-11e6-9a71-884a9d8e2a8c.gif)

Personally I'd say in the beta (before the last RC) it was not so laggy…

**Comment by lgrahl** [comment]
Nah, it was already laggy in the beta. It gets worse when you scroll up to request older messages. The more messages, the more it lags. You can help by creating a CPU profile in the browser and attach it here.

**Comment by rugk** [comment]
In Firefox 53.0a2 (2017-02-14) `about:performance` also shows how it behaves:
![performance](https://cloud.githubusercontent.com/assets/11966684/22984884/16caf866-f3a7-11e6-9423-03271bbe072a.png)

**Comment by ovalseven8** [comment]
Can confirm that it is very laggy. Should be one of the top priorities.

**Comment by lgrahl** [comment]
Yes, it's a lot worse in Firefox.

**Comment by dbrgn** [comment]
> Yes, it's a lot worse in Firefox.

Yes, Chrome is much faster in this regard.

**Comment by rugk** [comment]
> You can help by creating a CPU profile in the browser and attach it here.

I've sent it to *SUPPORT…
What I did there was not even scrolling up but similar things as shown in the video. Typing text, sending some messages to ECHOECHO opening the context menu for some messages.

**Comment by ovalseven8** [comment]
@dbrgn: Do you have any ideas how to fix this issue? It's really so bad that using the Web Client is not fun at all. Especially with Firefox it's a pain, however even with Chrome the performance is not great.

**Comment by screendriver** [comment]
Maybe upgrading to Angular 2 should bring a performance boost 🤔

**Comment by dbrgn** [comment]
@ovalseven8 yes, mostly #40. I hope that should speed up things a lot. We'll tackle that issue once we fixed the low(er) hanging fruits.

@screendriver Angular 2 is a completely different framework. It would mean porting, not upgrading. When development on Threema Web was started, Angular 2 final wasn't released yet.

**Comment by ovalseven8** [comment]
For 1.0.6 I have the feeling that toggling between different chats got slower. Perhaps can some of you check too?

**Comment by rugk** [comment]
Try out 1.1.0, which was released today. :smiley:

**Comment by ovalseven8** [comment]
> Try out 1.1.0, which was released today. :smiley:

Oh, I mean 1.1.0 of course. :laughing:

**Comment by dbrgn** [comment]
Fun story: https://github.com/Microsoft/vscode/issues/22900 (was #1 on Hacker News yesterday). Seems that CSS animations really are quite inefficient.

We should probably replace the loading spinner with an old fashioned GIF.

**Comment by dbrgn** [comment]
Since the UI is much less laggy now, let's close this in favor of #39.

**Comment by ovalseven8** [comment]
Well, I don't really think it's much less laggy. But #40 will hopefully improve things!

**Comment by ovalseven8** [comment]
@dbrgn: You should probably re-open?

**Comment by ovalseven8** [comment]
It's still a real pain with Firefox. Threema should definitely focus on improving the performance and efficiency.

While it's a lot better with Chromium (that I don't use), I think the performance could also be better there when opening chats.

**Comment by lgrahl** [comment]
@ovalseven8 Sure but #39 covers that.

**Comment by ovalseven8** [comment]
Do not understand why this issue is not priority.

A swift application improves UX **dramatically** and at the moment it's really bad. Some time ago I tried Chrome just for Threema Web and once I was using it for around an hour (and chat history grew) it also got that slow because loading of chats is an issue also for Chrome then.
