### ISSUE TITLE
Connection stuck at 60% in Rambox/Fritz

### ISSUE THREAD

**Issue by Bebef** [threema-ch/threema-web#200]
All described in this issue affects Windows 10. I can't tell if other versions/OSes are affected as well.
ThreemaWeb worked in 1.0.5, doesn't work any more in 1.1.0

## Expected Behavior
Connection attempt should not get stuck at 60%

## Current Behavior
ThreemaWeb works for me in Chrome. However, in non-webbrowser clients like [Rambox](http://rambox.pro/) or [Franz](http://meetfranz.com/), the connection set-up always gets stuck at 60%

## Possible Solution
I have installed ThreemaWeb 1.0.5 on a self-hosted platform, **not** using any custom SaltyRTC or STUN / TURN servers. This made it work again.

## Steps to Reproduce (for bugs)
1. [Install Rambox](http://rambox.pro/#download)
2. In Rambox, add ThreemaWeb as _Custom Service (using all default options is OK)
3. Try to use ThreemaWeb the usual way
4. Connection attempt gets stuck at 60%

## Your Environment
* Threema Web version: 1.1.0
* Threema for Android version: 3.13.2000346
* Threema for Android source: Google Play
* Browser name and version: Google Chrome 57.0.2987.133 (64-bit) / Franz 4.0.4 64-bit / Rambox 0.5.3 64-bit
* Operating system and version: Windows 10 Pro Version 1607 Build 14393.576

**Comment by dbrgn** [comment]
Does that happen reproducibly, even after reloading the service in Rambox? Threema Web as a custom service mostly works fine for me.

**Comment by Bebef** [comment]
@dbrgn Happens reproducibly. Clearing caches etc. won't change anything.

If I find the time I'll install 1.0.5 for a test...

**Comment by dbrgn** [comment]
> However, I didn't get around to install and try ThreemaWeb 1.0.5 yet.

Does that mean that your instance is self-hosted? Or are you using https://web.threema.ch/?

**Comment by Bebef** [comment]
@dbrgn What I was saying was:
Using https://web.threema.ch/ with 1.0.5 installed everything worked.
Now that https://web.threema.ch/ uses 1.1.0 it doesn't work any longer.

My idea was to try a self hosted 1.0.5 to see if that would make it work again. Unfortunately that doesn't work anyway as I can't get it to build on my server.

**Comment by Bebef** [comment]
OK, I managed to install and can confirm:

It works on ThreemaWeb 1.0.5
It broke on ThreemaWeb 1.1.0 as running on https://web.threema.ch/

**Comment by dbrgn** [comment]
That shouldn't really make a difference with regard to WebRTC.

Could you try adding https://web.threema.ch/troubleshoot/ as a custom service?

**Comment by Bebef** [comment]
I've tried that, every check was OK (:white_check_mark: Yes)

**Comment by dbrgn** [comment]
Did you click on the TURN test button too?

I don't really know what the issue could be, since 1.1.0 works fine for me in Rambox. Do you use the latest version of Rambox?

**Comment by lgrahl** [comment]
Is it possible to get console output? I think that would clear things up a bit.

**Comment by Bebef** [comment]
Doing all that testing, I just re-tested everything again and again. Turns out it works for me too now. I don't know why it didn't before.

Maybe the issue is with EDGE vs. 3G connectivity. However, I can't reproduce the error any more. EDGE won't work well with any version, I suppose it just worked a tiny bit better with 1.0.5

Sorry for the trouble :(

**Comment by lgrahl** [comment]
I highly doubt you'll get a working connection with EDGE. So, yes, that could be the issue.

**Comment by lgrahl** [comment]
Off-topic, but:

@dbrgn Technically, it should be possible to store specific IP addresses (link-local IPv6 addresses `fe80:...` are especially interesting for this as they are permanent) from previous WebRTC candidate messages or explicit SaltyRTC messages for that purpose in the local storage. The app could accept incoming WebSocket connections and start directly with SaltyRTC client-to-client messages. Would you be interested in that? I think that would be pretty neat.

Link-local addresses are not gathered by existing WebRTC implementations, though (privacy). But we can work around that by gathering those addresses by ourselves (not in the browser but in all other implementations). I don't see a privacy concern here either as browser and app trust each other.

This would have to be a separate task (that would require task chaining) or part of the protocol itself.

**Comment by dbrgn** [comment]
Sounds like an interesting approach. Maybe in the future.

**Comment by Bebef** [comment]
@lgrahl Problem is that the company's WIFI is utterly broken, so I can't use that. The only way to use ThreemaWeb is to resort to the cellular network.
By the way, it seems that the issue with EDGE is troughput, as it just might work sometimes. 3G/4G works all the time (despite me not having 3G/4G reception most of the time).

**Comment by lgrahl** [comment]
@Bebef That's exactly the issue I want to tackle: Bad internet connectivity for either smartphone or PC but a direct route via USB/Bluetooth/WiFi AP for those two to communicate with one another. But as sad as it may be for you, I think that special case is pretty rare. However, I also believe it's a case where SaltyRTC and Threema can shine.

@dbrgn I'll take the two client implementations and do some tests with it - I'm pretty pumped. :)

**Comment by dbrgn** [comment]
@lgrahl If you're dealing with a laptop it's tricky though, since you'd need to simultaneously connect to the company wifi and to your smartphone. If you're only connected to your phone, you don't have internet.

**Comment by lgrahl** [comment]
That's not even the biggest problem. Turns out WebSocket browser implementations are unable to connect to link-local IPv6 addresses. But even if we circumvent that (by using all the other IP addresses) the WebSocket server would have to provide a valid TLS certificate because you cannot open an insecure WebSocket connection on a TLS-secured website. That makes it impossible.

As long as we don't find a solution with browser support I'll leave this as low priority (and then it would be IPv6 multicast-based).
