### ISSUE TITLE
Calnder .ics files not correctly labelled

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#202]
## Expected Behavior

As in the app something like "date invitation" or "calender file" or so…

## Current Behavior

In the web client they are shown as `mimeTypes.event_am`.

## Possible Solution

Is this a missing translation? If so, just fix that… :smile: 

## Your Environment

* Threema Web version: 1.1.0

**Comment by dbrgn** [comment]
Closed in favor of #90.

**Comment by dbrgn** [comment]
Fixed by #218
