### ISSUE TITLE
Stuck at 60% because TURN not working: some new information!

### ISSUE THREAD

**Issue by dances-with-clouds** [threema-ch/threema-web#209]
I am sorry I have to open yet another thread because of this problem, but [this](https://github.com/threema-ch/threema-web/issues/43) thread, that deals with the issue, has been closed. But the admins are free to move my posting there.

I can't give you a solution to this problem, but I can provide some new information that might help the experts to solve it:

I am using Firefox 53 64bit on Linux and the latest version of Threema on my phone, and I was suffering the same problem: the connection got stuck at 60%. 

After disabling each and every addon and re-enabling them one by one, I found out that in my case the addon "FoxyProxy" was the one that caused the trouble. Even if I chose "completely disable FP" within the addon's menu, which is supposed to set Firefox to use no proxy whatsoever, the connection could not be established. After I removed the addon from FF, the connection was established very quickly. Re-installing the addon caused the same problem again. Un-installing the addon again made the connection work again.

The addon must be changing some internal setting of Firefox, even if it is set use direct connection without any proxy. I am writing this article in the hope that it might be useful to find the real solution to this problem.

**Comment by rugk** [comment]
Even when an issue is closed, you can post there. If necessary, you can ask the admins to reopen the issue.

**Comment by dbrgn** [comment]
@dances-with-clouds thanks for letting us know. we'll add FoxyProxy to our internal list of problematic addons that our supporters use when diagnosing connectivity problems.
