### ISSUE TITLE
Battery drain still high after disconnection

### ISSUE THREAD

**Issue by Anke** [threema-ch/threema-web#213]
I know Threema uses up more power when synchronising with Threema Web, yet it seems this increased power consumption doen't cease after Threema is disconnected from Threema Web. Actually it looks as if it takes an Android restart for Threemas battery consumption to drop to a normal level. 

Can a solution be expected to this problem, like e.g an automatic Threema restarts when disconnecting from Threema Web?

My Environment: 
* Threema (Play Store), Firefox, Firefox Developer Edition, Windows 10 Pro - latest releases
* Android - version 4.3

**Comment by ontheair81** [comment]
Can not confirm this behavior. After disconnecting from Threema Web the power consumption of the app goes back to normal.
Tested on Android 6.0.1, Threema source: PlayStore.

**Comment by dbrgn** [comment]
@Anke are you on the latest version of the app?

**Comment by Anke** [comment]
Threema Version 3.13, dated 23.03.2017.

Today I haven't connected to Threema Web so far, but none-the-less chatted a lot - and Threema isn't listed in the battery statistics.

Yesterday, connected to Threema Web the drainage for Threema was 19%, right behind display with 49%. Hours after disconnecting from Threema Web the value was still 19%.

**Comment by sillych** [comment]
this should be fixed by now
