### ISSUE TITLE
Option to hide notifications when tab is in use

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#216]
In the Threema forum users mentioned that the notification is overlapping the input field.
As the position of the notification cannot be changed, maybe you can at least include an option to only show these notifications when the tab is currently _not_ focused, meaning that users do not see notifications when they are currently using Threema Web. (They do see incoming messages anyway in the chat window…)

Ref: https://threema-forum.de/thread-2908-post-30783.html#pid30783

**Comment by sillych** [comment]
notifications can be disabled generally if this is a problem for the users.
