### ISSUE TITLE
Changing own avatar

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#221]
It would be nice if one could also change/set ones profile picture in the web UI too, so one can use images on your computer('s hard drive) – similar to changing the picture of other contacts, which is already possible.

BTW: Maybe also display the profile picture somewhere in the UI…

**Comment by sillych** [comment]
capture photo from webcam would be nice too :camera_flash:

**Comment by dbrgn** [comment]
By the way, support for changing the profile picture and other profile information is already mostly implemented, but blocked by a few app protocol updates that we want to tackle *after* the Voip release.
