### ISSUE TITLE
Link strips surrounding spaces

### ISSUE THREAD

**Issue by xf-** [threema-ch/threema-web#229]
## Expected Behavior

Get message link:
Open issue https://github.com/threema-ch/threema-web/issues/new and submit your issue

## Current Behavior

Get message link:
Open issuehttps://github.com/threema-ch/threema-web/issues/newand submit your issue

## Possible Solution

Stop stripping spaces around links.

## Steps to Reproduce (for bugs)

1. Send a link (in group) with surrounding text and spaces

## Your Environment

* Threema Web version: 1.2.1 hosted by threema
* Threema for Android version: 3.14
* Browser name and version: Firefox 53

**Comment by dbrgn** [comment]
Oh, that is a regression caused by #219. Thanks for reporting!

**Comment by dbrgn** [comment]
I cannot reproduce this using Firefox 53. Can you specify the exact steps you did? Also, what operating system are you using?

**Comment by dbrgn** [comment]
Closing in favor of #236.
