### ISSUE TITLE
Alert if you write a message to yourself

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#232]
## Steps to Reproduce (for bugs)

1. Go to the member list of a group
2. Click on your own profile
3. Send a message to yourself
4. The alert warning pops up

Should probably not be allowed to write message to yourself.

![2017-05-19-203412_1366x768_scrot](https://cloud.githubusercontent.com/assets/8258609/26261772/cc1aa3f0-3cd2-11e7-9e7d-39fbf249ca3f.png)

## Your Environment
* Threema Web version: 1.2.1
* Threema for Android version: 3.14
* Threema for Android source: Play Store
* Browser name and version: Firefox 53.0.2
* Operating system and version: Lubuntu 16.04

**Comment by dbrgn** [comment]
This can be obsoleted by fixing #231.

**Comment by dbrgn** [comment]
Fixed in #235.
