### ISSUE TITLE
Error if you want to watch your own profile

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#233]
## Steps to Reproduce (for bugs)
1. Go to the member list of a group in Threema Web
2. Click on yourself so that the conversation view appears
3. Click on yourself again at the top of the conversation view
4. Following error:

![2017-05-19-203724_1366x768_scrot](https://cloud.githubusercontent.com/assets/8258609/26261955/7ba0226e-3cd3-11e7-8555-8b3afb84923f.png)

## Your Environment
* Threema Web version: 1.2.1
* Threema for Android version: 3.14
* Threema for Android source: Play Store
* Browser name and version: Firefox 53.0.2
* Operating system and version: Lubuntu 16.04

**Comment by dbrgn** [comment]
Fixed in #235.
