### ISSUE TITLE
Pasting removes space

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#236]
## Expected Behavior

`This is Threema Web on GitHub: https://github.com/threema-ch/threema-web` is send.

## Current Behavior

`This is Threema Web on GitHub:https://github.com/threema-ch/threema-web` is send.

The bad thing is, that this makes the link unclickable in the app. (in Threema Web is is still clickable, FYI)

## Possible Solution

Maybe caused by fixing https://github.com/threema-ch/threema-web/issues/134?

## Steps to Reproduce (for bugs)

1. First "write" something ending with (at least) one space. (Actually you can also paste it…) E.g.: `This is Threema Web on GitHub: ` (<-- Note that there is a space at the end, which is also stripped by GitHub here :cry: )
2. Now paste something else in there, e.g. a link. (`https://github.com/threema-ch/threema-web`)
3. Everything looks right, but now press enter.

## Your Environment

* Threema Web version: 1.2.1
* Browser name and version: Firefox 53.0.2

**Comment by dbrgn** [comment]
Thanks, in contrast to #236 I can reproduce this :) Yes, it's a regression introduced by #219.
