### ISSUE TITLE
Curser-focus on quotations

### ISSUE THREAD

**Issue by pydocker** [threema-ch/threema-web#251]
## Expected Behavior

When answering to a message with a quotation the focus of the cursor should be in the message-writing-field.

## Current Behavior

Currently the cursor-focus seems to be in the area above the typing-area, so if you start typing after clicking on quote the text does not appear as a message.

## Possible Solution

Set the default cursor-focus to the text-area

## Your Environment

* Threema Web version: 1.2.1
* Threema for Android version: 3.14.2
* Threema for Android source: Play Store
* Browser name and version: Google Chrome Version 58.0.3029.110 (64-bit)
* Operating system and version: Linux Mint 17.3 / different

**Comment by dbrgn** [comment]
Thanks for the report @pydocker. Should be easy to fix.
