### ISSUE TITLE
Emoji in group-chat name aren't shown when you send a file

### ISSUE THREAD

**Issue by pydocker** [threema-ch/threema-web#258]
## Expected Behavior

 If you have emojis in the group name they are shown in Threema-web now correctly (thanks for that fix!).
## Current Behavior

 If you send a file (e.g. a picture) there are still those squares, and the emojis aren't shown correctly

![threema_send_file_blackedout](https://user-images.githubusercontent.com/10495444/27432468-8ca74596-5750-11e7-87e9-736b288deaf9.png)

## Steps to Reproduce (for bugs)

1. Create a group with some emojis in the name
2. Try to send an image

## Your Environment

* Threema Web version: 1.3.1
* Threema for Android version: 3.14.2
* Threema for Android source: Play Store
* Browser name and version: Version 58.0.3029.110 (64-bit)
* Operating system and version: Linux Mint 17.3

**Comment by sillych** [comment]
Also in the own public nick name

**Comment by IndianaDschones** [comment]
@dbrgn @sillych This issue was fixed by #338 so you can close it 😉

**Comment by dbrgn** [comment]
Thanks for spotting :)
