### ISSUE TITLE
Emoji picker isn't working properly

### ISSUE THREAD

**Issue by nilsrie** [threema-ch/threema-web#261]
## Current Behavior
I can't see any Emojis in the picker box. If I click on one of the not visible it's being added to the text box and I can see it. (see screenshot)

## Steps to Reproduce (for bugs)

1. Click Emoji picker
2. Picker opens, but I can't see emojis
3. If I click on one of the not visible it's being added to the text box and I can see it 

![threema](https://user-images.githubusercontent.com/12841812/27573505-7c352500-5b12-11e7-91fe-07e06f119432.png)

## Your Environment
* Threema Web version: 1.3.1
* Threema for Android version: 3.14.2000352
* Threema for Android source: Play Store
* Browser name and version: Chrome 59.0.3071.115
* Operating system and version:Win 10

**Comment by nilsrie** [comment]
Thank you for your help!

Ctrl + F5 didn't help. I can open this link. https://web.threema.ch/libs/emojione/emojione-sprite-32-people.png

Afterwards it still isn't working on Threema Web. Deleting the browser cache doesn't help either.

**Comment by kaechele** [comment]
On my system (macOS) the browser tries to load HiDPI sprites (e.g. https://web.threema.ch/libs/emojione/emojione-sprite-32-diversity@2x.png) and doesn't fall back on the regular sprites when loading the 2x version fails with a 404 error. Maybe there is some foo that prevents the browser from falling back? This also only started appearing for me after updating to Chrome 59.
Not seeing this with Firefox.

**Comment by dbrgn** [comment]
@kaechele thanks a lot for that hint, you're right, the HiDPI versions of the sprites are missing.

A fix will follow soon.

**Comment by dbrgn** [comment]
@nilsrie @kaechele if you reload Threema Web this should now be fixed. could one of you confirm?

**Comment by nilsrie** [comment]
perfekt, jetzt klappt es!
