### ISSUE TITLE
Cursor hidden after smiley

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#262]
## Expected Behavior

The cursor should always be visible, so the user knows where it is. A suddenly hidden cursor is a bad UX as it heavily confuses the user. Personally; I always stopped typing when I saw that as I thought something was wrong.

## Current Behavior

![video-opt](https://user-images.githubusercontent.com/11966684/27638080-436e46a6-5c12-11e7-8f4e-4f85d96d7700.gif)
better webm version: [video.zip](https://github.com/threema-ch/threema-web/files/1108734/video.zip)

I think this has been introduced recently, with v1.2.0 or so…

## Steps to Reproduce (for bugs)

1. See video, write some text and add a smiley.

## Your Environment

* Threema Web version: 1.3.1
* Browser name and version: Firefox 54.0
* Operating system and version: Linux

**Comment by dbrgn** [comment]
This appears to be related to the scale transform. I filed a bug against Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1417012

Maybe I can come up with a workaround.
