### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#266]
Are the current builds 100% reproducible, i.e. can one SHA-256 the created ~ZIP~ tar.gz and it should always be the same when built with the same settings?

More information and why this is important: https://reproducible-builds.org/

current hash (v1.3.1) for a selfhosted version (i.e. only the option "self-hosted" changed in the settings, on an ARM device): `51fecf364f9be5361a202f1a9038f9ce205208a68da1cbb76706e0551c7561fe`

If not, then take this issue as a suggestion to make it reproducible.

**Comment by dbrgn** [comment]
It probably depends on the libraries used. Some of them have native components which will most probably build differently on different platforms.

**Comment by dbrgn** [comment]
This is not currently planned. If someone wants to investigate how to achieve this goal with npm based software distribution, feel free to create a proposal / pull request.

**Comment by rugk** [comment]
What about leaving this issue open (otherwise it looks as if you declined it) and tag it with "help wanted"? This are IMHO/AFAIK the usual things to do in such a situation.

**Comment by lgrahl** [comment]
Generally, I agree with you @rugk that it should be left open. Possibly, @dbrgn meant that you should create an issue and a PR towards npm or this will be one of those issues that remain open forever.

**Comment by dbrgn** [comment]
It's bad practice to leave open issues where we don't intend to fix the issue ourselves in the near future. It clogs the issue tracker. There was a good blogpost on this, but I can't find it now.

If someone is interested about an issue, he/she will use the search anyways, which will also turn up closed issues. And the comment in here clearly states that pull requests are welcome.

**Comment by rugk** [comment]
> It's bad practice to leave open issues where we don't intend to fix the issue ourselves in the near future. 

No, it's clearly not. Maybe you misunderstood the blog post.
Leaving this issue open is the whole purpose of the "help wanted" tag.
Open = Not fixed
Closed = Fixed/wontfix/don't like

> If someone is interested about an issue, he/she will use the search anyways, which will also turn up closed issues. 

No, one won't. A potential contributor may also just look at the open issue and look for nice tasks/what to do.

**Comment by dbrgn** [comment]
> No, it's clearly not. Maybe you misunderstood the blog post.

Thanks for stating that I have misunderstood a blogpost that you've never read.

> No, one won't. A potential contributor may also just look at the open issue and look for nice tasks/what to do.

If someone doesn't take the time to do that, he/she won't take the time to fix a bug either. Welcome to the realities of open source.

What if you would start providing a pull request with everything needed for reproducible builds?

**Comment by rugk** [comment]
> that you've never read.

Yeah, well… you never know… maybe give it to me to read. :smile: 

> If someone doesn't take the time to do that, he/she won't take the time to fix a bug either.

Maybe, but when the issue is closed, most contributors would instantly ignore it. (As it's either fixed or not wanted) Actually they – as GitHub suggests it in the UI more or less – only search through all open issues, so maybe a contributor will never notice a closed issue…

> What if you would start providing a pull request with everything needed for reproducible builds?

We first need to find out, what needs to be fixed/changed… Maybe begin with asserting that you cannot reproduce my hash provided in my first post here?
Also, when really looking into issues, I'd like these issues to be "open", as otherwise I have to assume you decline anything done in a closed issue.
