### ISSUE TITLE
Attach tar.gz archive to GitHub releases

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#267]
Just attach the finished (compiled) tar.gz to https://github.com/threema-ch/threema-web/releases (maybe with the self-hosting option set to "true"), so that it will be easier for people to self-host Threema Web.

This complements https://github.com/threema-ch/threema-web/issues/266.

**Comment by dbrgn** [comment]
https://github.com/threema-ch/threema-web/releases/tag/v1.4.0
