### ISSUE TITLE
License file as markdown

### ISSUE THREAD

**Issue by xf-** [threema-ch/threema-web#27]
APGL provides a markdown version. Better readable on github and same content:

https://www.gnu.org/licenses/agpl-3.0.html
c&p @
https://gist.github.com/xf-/821fd8e280776fc927368c61e41edf64
vs
https://github.com/threema-ch/threema-web/blob/master/LICENSE.txt

No PR because the owner should do this. Less proof reading for a long legal document.

**Comment by dbrgn** [comment]
We actually used a markdown version of the license initially, but Github does not recognize the license in that case, meaning that this nice feature in the repository overview:

![2017-02-15-204700_282x101_scrot](https://cloud.githubusercontent.com/assets/105168/22992434/009e3bc0-f3c0-11e6-8e59-e52bc0be84b6.png)

...doesn't work with Markdown files.

**Comment by xf-** [comment]
Is supported:
https://help.github.com/articles/licensing-a-repository/#determining-the-location-of-your-license

Test works fine:
https://github.com/xf-/test-licence-file
