### ISSUE TITLE
60% or 12% issue if you log in and log out several times

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#270]
I logged in -> successful
Logged out immediately -> successful
Logged in -> successful
Logged out immediately -> successful
Logged in -> unsuccessful (60 % issue)

Probably the Threema app had problems with closing/opening a session, no idea.
But I thought to open a issue because there is probably need for optimization.

EDIT: Tried again, this time the 12% issue

![2017-07-17-154146_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28270833-207d5b42-6b07-11e7-9738-980604d30391.png)

## Your Environment

* Threema Web version: 1.3.1
* Threema for Android version: 3.15
* Threema for Android source: Play Store

**Comment by ovalseven8** [comment]
Hey, perhaps it helps @dbrgn:
The 60% issue is solved when I press that one key on the smartphone so that the display gets on (don't know the word for this key). It's on the border.

**Comment by ovalseven8** [comment]
Hey, perhaps it helps @dbrgn:
The 60% issue is solved when I press that one key on the smartphone so that the display gets on (don't know the word for this key). It's on the border.

**Comment by rugk** [comment]
>  (don't know the word for this key). It's on the border.

So just the on/off key…

When you have a physical home button you may also press it… just wake up the phone out of standby.

**Comment by ovalseven8** [comment]
@dbrgn 
I've closed the issue because it's probably related to #106.

**Comment by dbrgn** [comment]
> I've closed the issue because it's probably related to #106.

Yes, the fact that it works when the display is on probably indicates that it's memory management related. Android has gotten quite agressive in that regard in the latest versions.
