### ISSUE TITLE
Make it possible to add new contact/group/list with 'Enter'

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#271]
When you want to add another Threema contact it would be much more pleasant if you could do that with simple 'Enter'.
To touch the mouse just to click that tick on the right upper corner is not that nice. :smile: 

![2017-07-17-195200_1366x768_scrot](https://user-images.githubusercontent.com/8258609/28282129-a5a642da-6b29-11e7-887c-0e8d91f00a88.png)

Same, by the way, with creating a new group or distribution list.

## Your Environment

* Threema Web version: 1.3.1

**Comment by IndianaDschones** [comment]
I´d like to work on this

**Comment by dbrgn** [comment]
Sure, go ahead!

For comparison, Telegram allows to configure this:

![2017-07-26-141527_437x159_scrot](https://user-images.githubusercontent.com/105168/28620374-f10aab96-720c-11e7-9435-cd062173fb12.png)

In contrast, WhatsApp Web also has the same send behavior as Threema, with no configuration option to change it.

**Comment by rugk** [comment]
@dbrgn I think you confused this issue with https://github.com/threema-ch/threema-web/issues/274…

**Comment by dbrgn** [comment]
@rugk yes I did, sorry :)
