### ISSUE TITLE
Battery icon can be selected

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#275]
## Expected Behavior

Not selectable, it makes no sense to mark this icon.

## Current Behavior

You can select the battery icon – even in the middle of the icon:
![grafik](https://user-images.githubusercontent.com/11966684/28477513-9b1dc116-6e54-11e7-8483-d446990abeaa.png)

## Possible Solution

```css
-webkit-touch-callout: none;
-webkit-user-select: none;
-khtml-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
```
https://stackoverflow.com/questions/2310734/how-to-make-html-text-unselectable#answer-6382492

## Steps to Reproduce (for bugs)

1. Select the battery icon as if it were text

## Your Environment

* Threema Web version: 1.4.0

**Comment by lgrahl** [comment]
If you already have the solution, why don't you just create a PR instead of opening this issue? No offence intended - just wondering.

**Comment by rugk** [comment]
Yeah, just wanted to let it confirmed, not that Angular has a better way for handling this.

**Comment by dbrgn** [comment]
> Yeah, just wanted to let it confirmed, not that Angular has a better way for handling this.

That CSS looks good, although you can probably drop all user-select prefixes except for `-moz` and `-webkit`.

http://caniuse.com/#search=user-select

The SASS file that this belongs in is located at `src/sass/components/_battery.scss`.

**Comment by rugk** [comment]
So we are excluding -ms- as it does not have data channels in WebRTC anyway, so it cannot be used with Threema Web? :smiley:

**Comment by dbrgn** [comment]
Yes :) If that changes someday, we should start using a sass mixin to manage prefixes anyways.
