### ISSUE TITLE
Sending of images takes very long

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#279]
Today I copied an image from the internet (~ 170kB) and pasted it in Threema Web. Until it was sent it took about one minute, perhaps even more.

Can you speed things up?

**Comment by lgrahl** [comment]
Was it a conversation that you just opened for the purpose of sending an image?

**Comment by ovalseven8** [comment]
Yes, the upload of the image took to long. 170kB should not take more than a few seconds, normally.

**Comment by lgrahl** [comment]
I understand that the upload took long. But I'm asking if you opened that conversation just for the purpose of sending an image. Basically, I'm testing here whether it could be that loading images from the conversation blocks sending the image until the conversation is fully loaded.

**Comment by ovalseven8** [comment]
There was nothing to load because there is no conversation history.

**Comment by lgrahl** [comment]
Okay. Can this problem be reproduced consistently?

**Comment by ovalseven8** [comment]
Just now everything it only took 3-5 seconds, so that's okay. So, it's not reproducible always.

**Comment by lgrahl** [comment]
Can you ensure a direct connection? (@dbrgn: Maybe it's time to add an icon for this purpose. It requires finding out the selected candidate pair which is somewhere hidden in `pc.getStats`... unfortunately)

**Comment by rugk** [comment]
> (@dbrgn: Maybe it's time to add an icon for this purpose. It requires finding out the selected candidate pair which is somewhere hidden in pc.getStats... unfortunately)

Tracked in https://github.com/threema-ch/threema-web/issues/13

**Comment by dbrgn** [comment]
Yeah, #13 is planned.
