### ISSUE TITLE
Support (optional) yarn 

### ISSUE THREAD

**Issue by xf-** [threema-ch/threema-web#28]
npm is really slow and "cloneCurrentTree: sill cloneCurrentTree Finishing" takes _forever_.

Initial yarn (v0.20.3):
80s

rm node_modules and install again with lock and cache:
7s

npm initial (has no cache or lock):
7m 24s

Moving forward it would be interesting to pin all dependencys and be able to provide a fast setup process. 

Cheat-sheet:
https://shift.infinite.red/npm-vs-yarn-cheat-sheet-8755b092e5cc

_Please not: yarn currently doesn't work out-of-box with this repository._

**Comment by dbrgn** [comment]
> Moving forward it would be interesting to pin all dependencys

That's already being done in the `npm-shrinkwrap.json` file.

> npm initial (has no cache or lock):
> 7m 24s

On my system, a clean npm install took 2m36s. And I feel that this is slower than usual, maybe the servers are currently on high load. But it's a one-time cost, developers don't usually run npm install every day.

Anyways, we don't currently plan to use yarn. We may reconsider this in the future, but not in the next few weeks probably.

**Comment by dbrgn** [comment]
Currently it takes 15 seconds to do a full "npm install" on my machine. It was probably just high server load.
