### ISSUE TITLE
Grammarly causes messages to be sent incompletely

### ISSUE THREAD

**Issue by Warzulg** [threema-ch/threema-web#280]
## Expected Behavior
Messages arrive exactly as they got typed before being sent.

## Current Behavior
Some messages arrive with some of the words missing. I'm writing "words", because only strings seperated by whitespaces are able to disappear upon sending. They also seem to be replaced with whitespaces in the final string that is being sent.
It also is no local issue, the messages arrive fucked up. When checking with "Echo Test" as well as when checking with real people.

It is VERY. FREQUENT. And seems to correlate to the "complexety" of the message (strings like "test test test test test" or "test bla test bla" seem to always arrive complete, for example)

## Possible Solution
???

## Steps to Reproduce (for bugs)
1. Sent message
2. Read message in chatlog
3. Realize that message has WORDS MISSING
4. ???
5. Profit.. or don't, cause in the worst case, the messages entire meaning was warped.

## Your Environment
* Threema Web version: 1.4.0
* Threema for Android version: 3.15.2000354
* Threema for Android source: Play Store
* Browser name and version: Google Chrome 59.0.3071.115 (64bit)
* Operating system and version: Windows 10 Home

**Comment by lgrahl** [comment]
Do you use *Grammarly*?

**Comment by Warzulg** [comment]
Disabled Grammarly - it WAS the issue. Thanks!

This is the first case of Grammarly interfering with a web app in this way - what exactly is the cause?

**Comment by lgrahl** [comment]
Haven't investigated this. Possibly a data race. Maybe @dbrgn knows more about the exact reasons.

**Comment by dbrgn** [comment]
Yes, I also assumed it's a data race (looks like Grammarly does strange things to input forms), but never debugged this so far.

**Comment by dbrgn** [comment]
(By the way, disabling Grammarly isn't a bad idea anyways, it's essentially a cloud based keylogger. See also: https://news.ycombinator.com/item?id=16315684)

**Comment by rugk** [comment]
Well, seems they fixed the issue.

**Comment by dbrgn** [comment]
Yes, but the concept of sending your keyboard input and documents to the cloud remains 😉

**Comment by dbrgn** [comment]
type-ahead-find also breaks text input, see #513.

**Comment by rugk** [comment]
Slightly off-topic, but also note [it may not be such a good idea to use Grammarly anyway due to privacy concerns](https://twitter.com/sebmck/status/1104132995026317312) (hint/tl;dr: it's a keylogger for your browser…).

**Comment by lgrahl** [comment]
Right. I don't think we should invest any time on debugging an extension whose privacy implications are in conflict with our goals.

**Comment by rugk** [comment]
Your decision…

> Someone even claimed it's banned on Facebook for that reason.

If that is true, however, you could possibly do the same, too… :thinking:

**Comment by lgrahl** [comment]
Also *wontfix* from my perspective. PRs are always welcome.
