### ISSUE TITLE
One particular chat never loads

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#284]
## Expected Behavior

When I sent a message, previous chat should load.

## Current Behavior

I somehow experienced a bug that in a group chat, I could write messages and they were displayed on my phone and thus sent as expected, but the previous chat before my own message did not load (in Threema Web). The circle was still there.

![loadingold](https://user-images.githubusercontent.com/11966684/28943534-6f7c36a0-789f-11e7-8d97-1a0a8cec78ba.png)

Also, when switching the chat, it showed this in the browser console:
```
22:53:06.990 [filters.bufferToUrl] Could not apply bufferToUrl filter: buffer is undefined  angular.js:14199:18
	consoleLog/< DOMAIN.EXAMPLE/node_modules/angular/angular.js:14199:18
	[87]</</< DOMAIN.EXAMPLE/dist/app.js:11456:13
	fn DOMAIN.EXAMPLE/node_modules/angular/angular.js:4:333
	regularInterceptedExpression DOMAIN.EXAMPLE/node_modules/angular/angular.js:16354:55
	interpolationFn DOMAIN.EXAMPLE/node_modules/angular/angular.js:12668:29
	attrInterpolatePreLinkFn DOMAIN.EXAMPLE/node_modules/angular/angular.js:10043:30
	bind/< DOMAIN.EXAMPLE/node_modules/angular/angular.js:1259:15
	invokeLinkFn DOMAIN.EXAMPLE/node_modules/angular/angular.js:10152:9
	nodeLinkFn DOMAIN.EXAMPLE/node_modules/angular/angular.js:9528:11
	compositeLinkFn DOMAIN.EXAMPLE/node_modules/angular/angular.js:8810:13
	publicLinkFn DOMAIN.EXAMPLE/node_modules/angular/angular.js:8690:30
	lazyCompilation DOMAIN.EXAMPLE/node_modules/angular/angular.js:9047:16
	boundTranscludeFn DOMAIN.EXAMPLE/node_modules/angular/angular.js:8827:16
	controllersBoundTransclude DOMAIN.EXAMPLE/node_modules/angular/angular.js:9601:20
	ngIfWatchAction DOMAIN.EXAMPLE/node_modules/angular/angular.js:27107:15
	$digest DOMAIN.EXAMPLE/node_modules/angular/angular.js:17836:23
	$apply DOMAIN.EXAMPLE/node_modules/angular/angular.js:18102:13
	timeout/timeoutId< DOMAIN.EXAMPLE/node_modules/angular/angular.js:19950:25
	completeOutstandingRequest DOMAIN.EXAMPLE/node_modules/angular/angular.js:6045:7
	Browser/self.defer/timeoutId< DOMAIN.EXAMPLE/node_modules/angular/angular.js:6324:7
22:53:06.991 [filters.bufferToUrl] Could not apply bufferToUrl filter: buffer is undefined  angular.js:14199:18
	consoleLog/< DOMAIN.EXAMPLE/node_modules/angular/angular.js:14199:18
	[87]</</< DOMAIN.EXAMPLE/dist/app.js:11456:13
	fn DOMAIN.EXAMPLE/node_modules/angular/angular.js:4:333
	regularInterceptedExpression DOMAIN.EXAMPLE/node_modules/angular/angular.js:16354:55
	expressionInputWatch DOMAIN.EXAMPLE/node_modules/angular/angular.js:16256:26
	$digest DOMAIN.EXAMPLE/node_modules/angular/angular.js:17828:34
	$apply DOMAIN.EXAMPLE/node_modules/angular/angular.js:18102:13
	timeout/timeoutId< DOMAIN.EXAMPLE/node_modules/angular/angular.js:19950:25
	completeOutstandingRequest DOMAIN.EXAMPLE/node_modules/angular/angular.js:6045:7
	Browser/self.defer/timeoutId< DOMAIN.EXAMPLE/node_modules/angular/angular.js:6324:7
```

## Possible Solution

Maybe related to https://github.com/threema-ch/threema-web/issues/247, maybe not. I first thought it is the same, but there are differences:
* here it did happen in the middle of nothing, after sending a message or so.
* the workarounds with switching a chat or clicking somewhere do not work
* when I switch the chat the new chat loads as expected, but when I switch back to the old ("buggy"/affected) one, it still shows me the image I added above (i.e. my message and loading gif before)

## Steps to Reproduce (for bugs)

1. No real idea what caused this exactly…

## Your Environment

* Threema Web version: 1.4.0-gh
* Browser name and version: Firefox 54.0.1
* Operating system and version: Linux

**Comment by dbrgn** [comment]
I think this trace is unrelated. And even if it's related, it's the symptom, not the cause.

I fear without any other information I can't do anything about it. I'd probably attribute it to #247.

**Comment by rugk** [comment]
Maybe it is not related.
Because now I experienced this again (v1.4.1) and this time I saw in the Threema app, that the Threema Web connection was not even active anymore, but the Threema Web client obviously has not detected this.
Anything you sent in this (broken) status get's discarded. That's bad…

**Comment by lgrahl** [comment]
>  the Threema Web connection was not even active anymore, but the Threema Web client obviously has not detected this

In that case you'd see *connection problems* at the top of the page. Let us know if that's the case and please provide a log next time it happens.

**Comment by rugk** [comment]
Thing I'd I do not see it, even when switching the chat. By in the app, there was no icon, so no connection established.
