### ISSUE TITLE
No translation

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#288]
My default language is German, but it's not translated.
Moreover: Why is not my current battery displayed when below 20 % (only hover)?

![2017-08-06-194932_1366x768_scrot](https://user-images.githubusercontent.com/8258609/29005674-916f3d00-7ae0-11e7-98b0-59afb2e6c86e.png)

**Comment by rugk** [comment]
> Moreover: Why is not my current battery displayed when below 20 % (only hover)?

They only have one icon they use… (Looks confusing, I know. Maybe open a new issue for that?)
