### ISSUE TITLE
`web.threema.ch` uses unreleased version

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#290]
Now `web.threema.ch` uses the version 1.4.1.

Unfortunately, this version is not released yet.

**Comment by dbrgn** [comment]
Oh, I forgot to push the changes. Unfortunately I don't have access to those commits this week. Will publish them next week.

It was just a version bump though, nothing significant.

**Comment by ovalseven8** [comment]
Not fixed yet.

**Comment by dbrgn** [comment]
@ovalseven8 yes it is? https://github.com/threema-ch/threema-web/commit/34a2c24c99f22c17644d7a87ac8d52551ae955cf you probably meant the git tag though. I'll push that later today.

**Comment by ovalseven8** [comment]
I see, thanks! :+1:
