### ISSUE TITLE
New beta: Threema Web is not really usable with mobile data

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#292]
I've just tested the new beta and Threema Web is not really usable when my smartphone uses the cellular network. Disconnections every few seconds, no data/chats are loaded etc.

I can't really provide more information. :/

## Your Environment
* Threema Web version: 1.4.1
* Threema for Android version: 3.19 (beta)

**Comment by lgrahl** [comment]
A few questions:

1. Does it improve the situation if the app is in the foreground?
2. Does the situation further improve if you also keep the display on?

**Comment by lgrahl** [comment]
@dbrgn Are there separate ICE server configurations for voice calls and Threema Web or have you unified them? If you have unified them, can you post the configuration?

**Comment by ovalseven8** [comment]
I don't know why but I cannot reconnect to my session (no matter if I use cellular or WLAN):
![screenshot_20170808-143655](https://user-images.githubusercontent.com/8258609/29072506-4303ea12-7c48-11e7-9fc8-1ecea2383739.png)

**Comment by lgrahl** [comment]
Any news on my questions though? :)

**Comment by ovalseven8** [comment]
>Does it improve the situation if the app is in the foreground?

No

>Does the situation further improve if you also keep the display on?

No

I could connect with cellular to Threema Web now but it disconnected soon and it's not possible to load any chats anymore. It disconnects, connects, soon disconnects again etc. Even if it's green (connected) it seems like it can't transfer the data (chats) because there is only the loading circle.

Then I activated WLAN on my smartphone. Now I have completely different problems, there is still the loading circle, but at least **my** messages are displayed. However (!) I don't get the replies from ECHO! On my smartphone it's displayed, but not at Threema Web:
![2017-08-09-151257_1366x768_scrot](https://user-images.githubusercontent.com/8258609/29123261-74f54a20-7d15-11e7-962a-8570c465dc00.png)

It seems like there also some problems if the smartphone is switching from cellular to WLAN with Threema Web. It's not handled smoothly.

Sorry, but it's very hard to describe everything. But there is definitely some work to do, it's not working nicely. :/

**Comment by rugk** [comment]
Seems you had the same issue, I also had: https://github.com/threema-ch/threema-web/issues/284

**Comment by lgrahl** [comment]
Pretty sure that specific problem with the loading circle is #247. You can work around it by opening another conversation and then opening the first conversation again.

Regarding the connectivity issues: Not sure what one can do about this if the connection just breaks again and again and it's not due to the app being killed (it's important that we rule this out first). If it works over WiFi, it could possible be your ISP that does deep packet inspection and doesn't like the STUN packets (because they want you to pay for audio calls and STUN is frequently used for VoIP).

However, I have another idea: Are you using Firefox? Can you try using Chromium/Chrome/Opera and test again?

**Comment by ovalseven8** [comment]
Using congstar - but not sure if that has something to do with this issue.

**Comment by ovalseven8** [comment]
@dbrgn Here you can find the browser log concerning the disconnects:
```
[PeerConnectionHelper] ICE connection state change: connected  angular.js:14199
[StateService] RTC connection state: connected => connecting  angular.js:14199
Sending client info request  angular.js:14199
Sending request/clientInfo message  angular.js:14199
Sending receiver request  angular.js:14199
Sending request/receiver message  angular.js:14199
Sending conversation request  angular.js:14199
Sending request/conversations message  angular.js:14199
Sending battery status request  angular.js:14199
Sending request/batteryStatus message  angular.js:14199
[StateService] RTC connection state: connecting => connected  angular.js:14199
[PeerConnectionHelper] ICE connection state change: disconnected  angular.js:14199
[StateService] RTC connection state: connected => connecting  angular.js:14199
[PeerConnectionHelper] ICE connection state change: connected  angular.js:14199
Sending client info request  angular.js:14199
Sending request/clientInfo message  angular.js:14199
Sending receiver request  angular.js:14199
Sending request/receiver message  angular.js:14199
Sending conversation request  angular.js:14199
Sending request/conversations message  angular.js:14199
Sending battery status request  angular.js:14199
Sending request/batteryStatus message  angular.js:14199
[StateService] RTC connection state: connecting => connected  angular.js:14199
[PeerConnectionHelper] ICE connection state change: disconnected  angular.js:14199
[StateService] RTC connection state: connected => connecting  angular.js:14199
[PeerConnectionHelper] ICE connection state change: connected  angular.js:14199
Sending client info request  angular.js:14199
Sending request/clientInfo message  angular.js:14199
Sending receiver request  angular.js:14199
Sending request/receiver message  angular.js:14199
Sending conversation request  angular.js:14199
Sending request/conversations message  angular.js:14199
Sending battery status request  angular.js:14199
Sending request/batteryStatus message  angular.js:14199
[StateService] RTC connection state: connecting => connected  angular.js:14199
[PeerConnectionHelper] ICE connection state change: disconnected  angular.js:14199
```

Moreover, in the security tab there is this note:
```
TURNS is not yet supported.  app.js:14354
Using more than two STUN/TURN servers slows down discovery  app.js:14354
```

**Comment by dbrgn** [comment]
I heard some stories that with Congstar media transfers in Threema are sometimes very slow. Not sure if it's really related to the provider or just random, but it *could* be that they're messing with connections (QoS stuff).

Can you try whether it works better with Chrome/Opera, as @lgrahl suggested?

**Comment by ovalseven8** [comment]
Okay, just tested with Chromium. It seems like the connection is more stable than in Firefox, but I also had one disconnection:
```
Initialize session by scanning QR code...
angular.js?v=1.4.1:14199 [VersionService] Using Threema Web version 1.4.1
saltyrtc-client.es5.js?v=1.4.1:984 [SaltyRTC.Initiator] Opened connection
saltyrtc-client.es5.js?v=1.4.1:2001 [SaltyRTC.Initiator] Task v0.webrtc.tasks.saltyrtc.org has been selected
angular.js?v=1.4.1:14199 [PeerConnectionHelper] Initialize WebRTC PeerConnection
saltyrtc-client.es5.js?v=1.4.1:1869 [SaltyRTC.Initiator] Peer handshake done
saltyrtc-task-webrtc.es5.js?v=1.4.1:746 [SaltyRTC.WebRTC.initiator] Handover to data channel finished
saltyrtc-client.es5.js?v=1.4.1:993 [SaltyRTC.Initiator] Closed WebSocket connection due to handover
saltyrtc-task-webrtc.es5.js?v=1.4.1:746 [SaltyRTC.WebRTC.initiator] Handover to data channel finished
angular.js?v=1.4.1:14199 [StatusController] Connection lost. Attempting to reconnect...
    (anonymous) @ angular.js?v=1.4.1:14199
    reconnect @ app.js?v=1.4.1:9178
    onStateChange @ app.js?v=1.4.1:9149
    (anonymous) @ app.js?v=1.4.1:9123
    $digest @ angular.js?v=1.4.1:17836
    $apply @ angular.js?v=1.4.1:18102
    (anonymous) @ angular.js?v=1.4.1:19950
    completeOutstandingRequest @ angular.js?v=1.4.1:6045
    (anonymous) @ angular.js?v=1.4.1:6324
    setTimeout (async)
    Browser.self.defer @ angular.js?v=1.4.1:6322
    timeout @ angular.js?v=1.4.1:19940
    setConnectionState @ app.js?v=1.4.1:14522
    (anonymous) @ app.js?v=1.4.1:14411
    $eval @ angular.js?v=1.4.1:17994
    $apply @ angular.js?v=1.4.1:18094
    pc.oniceconnectionstatechange @ app.js?v=1.4.1:14396
angular.js?v=1.4.1:14199 Disconnecting...
angular.js?v=1.4.1:14199 Secure data channel: Closed
    (anonymous) @ angular.js?v=1.4.1:14199
    _this2.secureDataChannel.onclose @ app.js?v=1.4.1:15528
saltyrtc-client.es5.js?v=1.4.1:984 [SaltyRTC.Initiator] Opened connection
```

**Comment by ovalseven8** [comment]
Very odd, I am just testing with Firefox again and the connection seems to be stable. :confused:

**Comment by ovalseven8** [comment]
Seems to be fixed -> https://threema-forum.de/thread-3355-post-32711.html#pid32711

Closing for now.

**Comment by lgrahl** [comment]
@ovalseven8 Okay, thanks, that would prove my theory.

> Even if it's green (connected) it seems like it can't transfer the data (chats) because there is only the loading circle.

@dbrgn I believe the issue is based on the `disconnected` -> `connected` behaviour where you currently treat this as if it were a reconnect (although it's not) and retransmit all initial data for some reason. However, that alone is not the whole issue. The secondary problem is the bug that only affects Firefox (as far as I can tell) where the initial conversation request is being discarded. These two issues together make it look like the conversation never loads.
