### ISSUE TITLE
Relax threema web reconnection timeouts - never reconnects session

### ISSUE THREAD

**Issue by mannp** [threema-ch/threema-web#307]
Love threema web, but it drives me mad too.

Its far too paranoid about reconnecting a session on a home network.

So its constantly losing connection and won't allow me to restart the session.

When I restart the session on my phone, its wanting to start a new session on the computer.

On a secured network, I'd prefer to relax the connection timeouts, so threema web can reconnect at will.

Thanks.

**Comment by dbrgn** [comment]
Are you using the Beta app (with calls)?

**Comment by mannp** [comment]
Yes I am, sorry about that, the latest build available on android.

**Comment by dbrgn** [comment]
We're having some issues in the beta version, sorry about that. There was a big refactoring involved, hence it's beta so we can test more (and the call feature of course) :slightly_smiling_face: The problems should hopefully be gone by the final release.

I'll close this for now, tracking issue is #184. If it's unbearable for you, the non-beta should be more stable.
