### ISSUE TITLE
Threema Web 1.5.0 - Stuck at 60%

### ISSUE THREAD

**Issue by fichtennadel** [threema-ch/threema-web#312]
## Expected Behavior
Threema Web Connecting

## Current Behavior
Stuck at 60%
Version 1.4.1 worked fine today, problems started with Threema Web 1.5.0

## Steps to Reproduce (for bugs)
1. Start Threema on Android
2. Start Threema Web
3. Reconnect Session
4. Stuck at 60%

I've reloaded the page, restarted the app, restarted the browser, still no luck.

## Your Environment
* Threema Web version: 1.5.0.
* Threema for Android version: 3.17.2000363
* Threema for Android source: Play Store
* Browser name and version: FF 55.0.3 64bit
* Operating system and version: Win7 64bit
* Behind Corporate FW

**Comment by dbrgn** [comment]
There were no connection related changes in version 1.5.0, so it should make no difference.

Can you try the test at https://web.threema.ch/troubleshoot/ (including the TURN test at the end)?

**Comment by fichtennadel** [comment]
Additional info: works ok in Chrome, so I can rule out netwiork or app issues.

I've also tried with FF in Safe Mode and with a new Threema session, did not work.

Seems to be a regression issue in 1.5.0 with FF.

**Comment by fichtennadel** [comment]
https://web.threema.ch/troubleshoot/ 

- FF: TURN fails (rest ok)
- Chrome: all ok

**Comment by fichtennadel** [comment]
uBlock update at the very same time - seems it has enabled WebRTC block and FF restart triggered it. 
Sorry for the confusion.

**Comment by dbrgn** [comment]
Good to hear that you could resolve the issue.

**Comment by lgrahl** [comment]
Might be yet another instance of an Android VPN tool having issues with WebRTC. Do you remember the other one that also used the VPN API, @dbrgn? Can't find it any more.

**Comment by dbrgn** [comment]
DNS66.

**Comment by lgrahl** [comment]
For reference: https://github.com/julian-klode/dns66/issues/193
