### ISSUE TITLE
Playback of Audio Messages fails in Opera

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#314]
The player looks like this:

![screenshot](https://tmp.dbrgn.ch/screenshots/20170830150755-cukn36ku.png)

Audio cannot be played.

I checked whether ogg files are supported in general. That works fine. It probably has to do with the fact that it's loaded through a data URL. Although these seem to work in principle even in Opera: http://iandevlin.com/html5/data-uri/audio.php

**Comment by lgrahl** [comment]
Works fine for me (Opera 48.0.2685.7).

**Comment by sillych** [comment]
Works fine for me (Opera 47.0.2631.80).

**Comment by dbrgn** [comment]
Same problem again, but this time in Chromium Snapshot (77). It works in Chromium 75 though, so I assume it's a codec problem...

**Comment by dbrgn** [comment]
Same issue with Vivaldi on Windows 10, according to a user.
