### ISSUE TITLE
Incorrect representation of Emojis

### ISSUE THREAD

**Issue by TheClownDE** [threema-ch/threema-web#317]
I just noticed a big difference in the Emojis in the ThreemaWeb and the App, some examples given below:

![screenshot_20170831-121727](https://user-images.githubusercontent.com/17886517/29941248-cfc3c89a-8e46-11e7-94a1-796303d665b5.png)
![screenshot_20170831_121854](https://user-images.githubusercontent.com/17886517/29941259-dde5b85c-8e46-11e7-9cab-3e1e2ab4afcd.png)

Furthermore, those Icons can not be send from the App, even though they show up.

I found this thread [#146](https://github.com/threema-ch/threema-web/issues/146), but I think this problem is more than just taste!

**Comment by rugk** [comment]
The dancing emoji (💃) and the princess (👸) are correct in your screenshot in both. (They are just from different Emoji sets, see the issue https://github.com/threema-ch/threema-web/issues/146, you already mentioned)
Except of these ones all of the others use emojis use [ZWJ Sequences](https://blog.emojipedia.org/emoji-zwj-sequences-three-letters-many-possibilities/) to combine/modify one or two emojis.
Thus the app does not support these new combinations and displays them as two emojis, which, at least, often allow one to conclude what is meant.
However, of course, missing support for them is not nice, and it is indeed an issue.

**Comment by TheClownDE** [comment]
Thanks for the explanation, I had never heard of ZWJ Sequences before!

But there are also single emojis (I guess they are) that are not selectable from the App, e.g. :man_facepalming: or this that a sequence ?

**Comment by rugk** [comment]
Yes, these are Unicode 9 (IIRC) emojis, which are only supported in the web version.

**Comment by dbrgn** [comment]
The app will be updated with emojis from the newer unicode standards eventually.
