### ISSUE TITLE
No character limit for image description

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#318]
When I write a normal message there is a character limit (maximally 3500 chars per message). However, when I send an image, the image description can contain as many chars as you like.

Perhaps needs also app update, don't know.

**Comment by dbrgn** [comment]
Text is embedded in the text message itself, which should not get too large, so there's a limit. Image captions are embedded in the image, which is transferred via the server, thus not slowing down the message delivery itself, so there's no problem with long captions.

The Android app limits the caption length though, so we'll have to discuss whether we want to mirror that behavior in Threema Web.

**Comment by ovalseven8** [comment]
> The Android app limits the caption length though, so we'll have to discuss whether we want to mirror that behavior in Threema Web.

I think we should. ;-)
![2017-09-02-231658_1920x1080_scrot](https://user-images.githubusercontent.com/8258609/29998844-353db664-9035-11e7-8cc2-13642b1acf6c.png)

**Comment by dbrgn** [comment]
Yep, but that's another issue (#319). The text could be cut off after a certain number of characters in the preview.
