### ISSUE TITLE
Latest beta: Reconnection to session does not work anymore

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#324]
## Steps to Reproduce (for bugs)
1. Go to https://web.threema.ch
2. Scan QR code (with password!)
3. Now I am connected
4. Close session
5. Try to reconnect

Reconnection does not work. Also, in the app it shows that I've never used this session (what is not true because I was already connected). Moreover, in the app the loading circle does not disappear even if I close the app and start again.

Because of that it's also not possible to close the session within the app in step 4.

![screenshot_20170907-123924](https://user-images.githubusercontent.com/8258609/30159783-23d72412-93ca-11e7-88d1-347a66de0d86.png)

## Your Environment
* Threema Web version: 1.5.0
* Threema for Android version: 3.19.2000368
* Threema for Android source: Play Store

**Comment by ovalseven8** [comment]
The version `3.19.2000369` fixed it for me. Did you work on that?

**Comment by dbrgn** [comment]
If by "Close session" you mean closing manually through the app, then yes, that should be fixed in the current app version (released today).
