### ISSUE TITLE
Gray icon in Threema web menu in the app

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#328]
Why not display the gray icon by default or why is there a difference?

When I start Threema after a reboot, the "Threema Web" menu looks like this:
![screenshot_20170907-224317](https://user-images.githubusercontent.com/8258609/30184549-b90c6af2-941e-11e7-8267-5102805c8ea4.png)

When I was already connected to the session since the device booted, there is this gray icon:
![screenshot_20170907-224356](https://user-images.githubusercontent.com/8258609/30184565-c86fa194-941e-11e7-80e2-9161ad8e03b7.png)

**Comment by dbrgn** [comment]
The difference is a bit technical. A grey icon means that a session is or was instantiated in the app but disconnected. No icon means that no session is instantiated.

We may drop that grey icon in a future release.

**Comment by ovalseven8** [comment]
Okay, makes sense.
