### ISSUE TITLE
npm nativefier with Threema Web - Can't send message

### ISSUE THREAD

**Issue by stenosis** [threema-ch/threema-web#33]
When using Threema Web over npm's nativefier, I can't send any messages over it.
Pressing on the send msg icon as well as pressing Enter on the keyboard won't send the typed message. 
Sending files (also with a attached message) works on the other hand.
Nativefier wrapps web apps with the electron framework in an OS executable.

npm nativefier: https://github.com/jiahaog/nativefier
System: Linux 64bit

Steps to reproduce:

npm install nativefier -g
nativefier --name "Threema" "web.threema.ch"

**Comment by dbrgn** [comment]
That's probably something you have to report to the nativefier project. We don't currently support environments outside the browser.

**Comment by stenosis** [comment]
Technically it's a Chromium browser build with Electron and this is the error message from the js console when pressing send: 

TypeError: composeDiv[0].childNodes[Symbol.iterator] is not a function
    at submitText (app.js?v=1.0.1:8222)
    at sendText (app.js?v=1.0.1:8262)
    at app.js?v=1.0.1:8279
    at angular.js?v=1.0.1:19942
    at completeOutstandingRequest (angular.js?v=1.0.1:6045)
    at angular.js?v=1.0.1:6324

But I'll also try to contact the guys at the nativefier projekt. :-) Thanks

**Comment by dbrgn** [comment]
Looks like the embedded Chromium does not support ES2015 iterators yet.

**Comment by stenosis** [comment]
Based on your ES6 hint I just found out that it's possible to determine the embedded electron/chromium version inside the builded nativfier app by using the -e flag on the building process. And when using the latest version the send-button works like charm. (-:

P.S.: nativefier -n "Threema" -e "1.6.0" "web.threema.ch"

**Comment by dbrgn** [comment]
@stenosis that's great to hear.
