### ISSUE TITLE
Attachment Button Behaviour

### ISSUE THREAD

**Issue by sillych** [threema-ch/threema-web#330]
## Expected Behavior
Sending files via attachment button should support sending multiple files at once

## Current Behavior
Sending more than one file at once is working only in "drag'n drop" mode, selecting files via "attachment" button send only the first selected file

## Steps to Reproduce (for bugs)
1. Open a conversation
2. Click the "attachment" button
3. Select more then one file
4. Submit...

## Your Environment
* Threema Web version: master branch
* Threema for Android version: 3.2-beta
* Threema for Android source: Pirate Bay
* Browser name and version: Google Chrome 
* Operating system and version: Xubuntu 16.04 LTS

**Comment by rugk** [comment]
Haha, that Threema app source.😎
