### ISSUE TITLE
Development Server binds on OpenVPN interface

### ISSUE THREAD

**Issue by jbtronics** [threema-ch/threema-web#34]
Hello,

I tried to run Threema-Web on a server (Ubuntu 16.04) on which a OpenVPN server runs, too and Threema binds to the tun0 interface (in my case 10.8.0.1) instead of localhost or the eth0 iface (in my case with the ip 192.168.1.0).
Maybe a option to determine which interface should be used, so you can select one which you want to use.

**Comment by dbrgn** [comment]
What do you mean with "Threema binds to the tun0 interface"? What web server do you use?

Did you follow the instructions at https://github.com/threema-ch/threema-web/blob/master/docs/self_hosting.md?

**Comment by rugk** [comment]
> Did you follow the instructions at https://github.com/threema-ch/threema-web/blob/master/docs/self_hosting.md?

In which case nothing should bind anywhere as these are static files. And I really recommend to only host those static files…
