### ISSUE TITLE
Show notification when battery is (nearly) dead

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#348]
Followup of https://github.com/threema-ch/threema-web/issues/268 / https://github.com/threema-ch/threema-web/pull/340

**Reason:** I just again had the issue that I was chatting, got connection issues, (fortunately copied my text out of Threema Web), the connection was lost and then I saw that my battery was dead.

The thing is, you just do not notice [a tiny icon/text](https://github.com/threema-ch/threema-web/pull/340#issue-257349055) there. It needs to make you aware that you really have a problem if you do want to continue to use Threema Web. It needs a **warning**.
You also don't notice the indicators of the phone itself, as it may be laying somewhere else and you are less likely to take it up if you are already using Threema Web.

IMHO the best implementation would be:
* a browser notification, as the user will see this, even when not using the browser/doing something else

IMHO the notification should be triggered:
* at 15%, "a serious warning"
* at 5% when it is nearly dead

**Comment by dbrgn** [comment]
Are you already using the version with the pulsing icon?

**Comment by rugk** [comment]
v1.5.0-gh

**Comment by dbrgn** [comment]
Yes, I agree about the desktop notification. That would be a good addition.
