### ISSUE TITLE
Don't display empty battery notification when charging

### ISSUE THREAD

**Issue by Elsensee** [threema-ch/threema-web#359]
## Expected Behavior
A push notification for empty battery should only be displayed when the battery is empty AND the device is not charging.

## Current Behavior
A push notification for empty battery is displayed if the battery is empty no matter if it is plugged or not.

## Steps to Reproduce (for bugs)
1. Use your phone until its battery is below 19%
2. Plug your phone to the charger and open Threema Web

## Your Environment

* Threema Web version: 1.6.1
* Threema for Android version: 3.21.2000380
* Threema for Android source: Play Store
* Browser name and version: Chrome 62
* Operating system and version: Ubuntu 17.04

**Comment by dbrgn** [comment]
Thanks, that somehow slipped through :)
