### ISSUE TITLE
Mark chats feature missing

### ISSUE THREAD

**Issue by ozzi-** [threema-ch/threema-web#361]
The new "mark chats" feature is missing on Threema web.
This includes the indicator and the ability to mark / unmark chats.
It is not a "must have" feature, but it would be quite nice.

**Comment by rugk** [comment]
Preferably, it should be synchronized with the app.

**Comment by rugk** [comment]
BTW, it is already synchronized since https://github.com/threema-ch/threema-web/pull/362 has been merged, as it seems, but the UI in the web client to mark/unmark (star/unstar) is still missing.

**Comment by dbrgn** [comment]
Right now the synchronization is only one-way. Support for the message type that updates the conversation (browser -> app) will be implemented in protocol v2 (together with the ios release).

**Comment by dbrgn** [comment]
Implemented in beta branch.
