### ISSUE TITLE
Missing bottom border if starred or unread

### ISSUE THREAD

**Issue by sillych** [threema-ch/threema-web#366]
If a conversation is starred or unread, the bottom border (divider) is missing

Default:
![2017-10-27-141740_377x93_scrot](https://user-images.githubusercontent.com/3036773/32103706-e704a5f8-bb21-11e7-99a8-9e1276f4cc3a.png)

Starred
![2017-10-27-141725_382x103_scrot](https://user-images.githubusercontent.com/3036773/32103726-f2600104-bb21-11e7-8701-403736169d4a.png)

**Comment by ovalseven8** [comment]
The border is also missing when you hover over the conversations and if the conversation is selected.

**Comment by dbrgn** [comment]
Hm, I thought I fixed that already in #362... I'll take a look next week :)
