### ISSUE TITLE
Feature: Show image preview when pasting from clipboard

### ISSUE THREAD

**Issue by simmac** [threema-ch/threema-web#367]
## Expected Behavior
When pasting an image from the clipboard, show a thumbnail preview of the image in the confirmation dialog.
I usually paste screenshots into Threema Web that I just took, but sometimes I forget that I changed the screenshot settings to save the screenshot to disk instead of storing it in the clipboard and something else is pasted into Threema Web.

## Current Behavior
The dialog just shows the name of the receiver, provides a field for a caption and a checkbox whether the image should be sent as a file.

## Possible Solution
Show a thumbnail in the dialog, directly over the caption field.

**Comment by dbrgn** [comment]
Duplicate of #112. I agree that this would be useful :)
