### ISSUE TITLE
Stuck at 99%

### ISSUE THREAD

**Issue by simonschaufi** [threema-ch/threema-web#38]
I tried to connect with Firefox 51 and Srware Iron 55 (Google Chrome Fork) and both are stuck at 99% with Loading initial data...

I waited for about 3 minutes and nothing happened.

What is initial data?

**Comment by dbrgn** [comment]
Does it work after reloading the page and trying again?

**Comment by simonschaufi** [comment]
Nop. I restarted Threema App also and got to 100% somehow but still the loading circle is displayed.

**Comment by max-m** [comment]
I had it stuck at 66% on my first try because I turned my phone’s screen off<sup>*</sup> and on again during the initial sync.

On my second try, while making sure I don’t turn the screen off, it worked flawlessly.
Afterwards I deleted the still loading session on my phone.

*) Which also locks my phone

**Comment by dbrgn** [comment]
@simonschaufi what exact Android version are you using? This might be a bug in the msgpack library: https://github.com/msgpack/msgpack-java/issues/405

Maybe you could record a message log (Threema > Settings > Troubleshooting > "Log to File") during the connection attempt and then send it to us through support (https://threema.ch/en/support or a Threema message to *SUPPORT). Reference this conversation in the support request.

**Comment by CptHermi** [comment]
sorry, doesn't matter whether cell or wlan
everytime stuck at 60%
Firefox 51.0.1 (32-Bit)
Moto X Force Android 6.0.1

**Comment by dbrgn** [comment]
@CptHermi that's a different issue. See https://github.com/threema-ch/threema-web/issues/43.

**Comment by Anke** [comment]
[Cross-reference](https://github.com/threema-ch/threema-web/issues/12#issuecomment-280063172) to my 99% loading issue...

**Comment by simonschaufi** [comment]
Android 4.4.2
Kernel: 3.4.0
Message log sent to *support

**Comment by dbrgn** [comment]
Signal works very differently. This is a bug in one of the libraries we use (msgpack-java) that only happens on Android 4. It will be fixed in the next release of the app.

**Comment by merlin2004** [comment]
Same here with S4 mini. Android 4.2.2. 
Yesterday: worked well. Today: worked well until 03:00 pm (approx.)
At the moment it works again. :-)

**Comment by lgrahl** [comment]
Probably not related but it's stuck at 99% so I'm posting here: [web.threema.ch-1487761270145.txt](https://github.com/threema-ch/threema-web/files/793148/web.threema.ch-1487761270145.txt)
`TypeError: Cannot read property 'avatar' of undefined`

**Comment by Anke** [comment]
Just tried it out for the first time since the update, and it's working quite well and reasonably fast. Thank you, great work!

**Comment by dbrgn** [comment]
Actually this fix didn't make it into the first App update, but good to hear that it works for you @Anke!

**Comment by lgrahl** [comment]
You probably didn't want to close with that commit.

**Comment by merlin2004** [comment]
Worked for me too. And it's really fast. Thanks guys!

**Comment by dbrgn** [comment]
Threema Web 1.0.3 was just published. :sparkles: This should fix some of the "stuck at 99%" problems.

**Comment by simonschaufi** [comment]
I hope a new Threema version will also be released soon that fixes the "bad position" bug.

**Comment by dbrgn** [comment]
This should now be fixed with the Threema for Android 3.1 release! ✨
