### ISSUE TITLE
Sending pictures to distribution lists won't work

### ISSUE THREAD

**Issue by Kurisutian** [threema-ch/threema-web#394]
## Expected Behavior
When sending pictures to a distribution list created in the threema app, the pictures should be send to all members of this list.

## Current Behavior
Sending pictures through the web client to distribution lists is not working. 

## Steps to Reproduce (for bugs)
1. Create a distribution list on threema
2. Log in to the web client
3. Send a picture to the newly created distribution list through the web client

## Your Environment
* Threema Web version: 1.7.0
* Threema for Android version: 3.3.2000391
* Threema for Android source: Play Store
* Browser name and version: Chromium 62.0.3202.94
* Operating system and version: Manjaro Linux 17.0.6

**Comment by IndianaDschones** [comment]
@dbrgn Was/is there a technical reason to not allow sending images/files/etc to distribution lists?

If not I woult create a PR with the idential feature-level check in `sendMessage` as it exist for groups.

**Comment by dbrgn** [comment]
I'm not aware of any. Maybe @sillych knows more?

**Comment by mimiks** [comment]
The same applies to files.
Note that videos to distribution lists are not currently supported.

**Comment by dbrgn** [comment]
This is finally fixed in the Android app, will be released with the next version.
