### ISSUE TITLE
Message is not sent

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#395]
Yesterday, I just wanted to write a short message to someone. So I connected to Threema Web, wrote the message and closed the session.

Today I saw on my smartphone that the message has not been sent. There is still the "Message sending" icon (![messagestatus_sending](https://user-images.githubusercontent.com/8258609/33941427-e3353724-e012-11e7-8845-77727ad58aff.png)).

Because of that I had to send the message again today and everything worked fine. Unfortunately, the original message is still not sent. Here you can see the screenshot:

![screenshot_20171213-142733](https://user-images.githubusercontent.com/8258609/33941469-1022cb3e-e013-11e7-9cad-07dfbd4ec43c.png)

Unfortunately, I can not provide logs at the moment. But there is definitely a bug somewhere. The original message is on my smartphone, so perhaps it's a bug on the app's side.

## Your Environment
* Threema Web version: 1.7.0
* Threema for Android version: 3.3
* Threema for Android source: Play Store
* Browser name: Firefox

**Comment by dbrgn** [comment]
Yeah, that's definitely on the app side.

**Comment by sillych** [comment]
Please enable the message log (Threema > Settings > Troubleshooting > "Log to File"). Try to reproduce the bug again and send us the file /sdcard/Threema/message_log.txt (doesn't contain any unencrypted or otherwise readable message contents). Using the log, we can better retrace what happened.

**Comment by ovalseven8** [comment]
I've sent the relevant logs to ***SUPPORT**. Did you receive those, @sillych?

**Comment by sillych** [comment]
@ovalseven8 yes thank you

**Comment by ovalseven8** [comment]
It's actually not resolved. However, @threema-ch could not find the reason for this behaviour.
However, I also did not encounter this problem again. So I think it's fine to close.
