### ISSUE TITLE
Feature Request: selective status updates depending on user

### ISSUE THREAD

**Issue by signpainter** [threema-ch/threema-web#398]
## Expected Behavior
In addition to disabling notifications about typing or having read a message, it should be possible to override those settings for single chats. So that one is able to share those status with specific persons but not with others.

**Comment by rugk** [comment]
That's more a general suggestion for Threema (not only for Threema Web), is not it? If so, please report it at https://threema.ch/en/feedback instead.

**Comment by signpainter** [comment]
Thanks. Mentioned it there.
