### ISSUE TITLE
Show/Hide Inactive Contacts

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#4]
Add an option to enable/disable display of inactive contacts.

No app/protocol update is necessary, the flag is already sent with a contact.

**Comment by IndianaDschones** [comment]
You can show/hide inactive contacts. But it´s buggy:

## Current Behavior
Contacts only hide/show if you toggle the "Show inactive IDs" setting in the Android app.

## Possible Solution
Sync the contact list correctly on initial loading.

**There is also a difference to the app:**
Also chats with inactive contacts disappear. The app only "highlights" them as inactive (grey color).

## Steps to Reproduce (for bugs)

1. Open the Android app
2. Settings -> Appearance -> Show inactive IDs
3. Toggle this setting untill the checkbox is unchecked. Even if the box was unchecked, you have to uncheck it again (tap two times). Then they also disappear in the web session.

## Your Environment


* Threema Web version: 1.0.4
* Threema for Android version: 3.02
* Threema for Android source: Play Store
* Browser name and version: Firefox 51.0.1 (64-bit)

**Comment by IndianaDschones** [comment]
@dbrgn You mean an option in the Threema Web settings to toggle the visibility?

I ask because the app already has this option but the initial state is not applied in Threema Web, see my issue above.

**Comment by dbrgn** [comment]
> @dbrgn You mean an option in the Threema Web settings to toggle the visibility?

Yes. The `ContactReceiver` type already contains a field `state` (see `src/threema.d.ts`), if I'm not mistaken that field can be used to determine whether a contact is inactive or not.

But I'd have to check the implementation again on how the checkbox in the app is handled.

**Comment by dbrgn** [comment]
Fixed in 61d1ada18fc22143aa3f52a5b7397fc5874c9669.
