### ISSUE TITLE
Building Threema Web on macOS fails

### ISSUE THREAD

**Issue by joelfischerr** [threema-ch/threema-web#405]
## Expected Behavior
The self_hosting.md should allow building Threema Web in macOS.

## Current Behavior
macOS and Linux have some slight differences in how things work in bash. These differences make it impossible to build Threema Web on macOS.

## Possible Solution
Change the package.sh to allow it to distinguish between macOS and Linux and change the following things:
- Use `ditto` instead of `install -D` because `install -D` doesn’t work on macOS
- On macOS the version number could sometimes contain a single leading whitespace, add another sed to remove all whitespaces in the version number
- `sed` does not behave in the same way on macOS as it does on Linux, change `sed` to `gnu-sed` when adding the version number (`gnu-sed` can be installed from homebrew)
- Add Note about how to build on macOS to self_hosting.md
- Misc. add `.DS_Store` to `.gitignore`

## Steps to Reproduce (for bugs)
1. call `npm run build` on macOS, it will fail.

## Your Environment

* Threema Web version: 1.7.0
* Operating system and version: macOS 10.13.3 High Sierra

**Comment by joelfischerr** [comment]
I'm currently working on it and might have a pull-request ready today or within the next week.

**Comment by ovalseven8** [comment]
Closable.
