### ISSUE TITLE
FR: Add reload/reconnect button to the connecting screen

### ISSUE THREAD

**Issue by Anke** [threema-ch/threema-web#409]
It would be nice to have a reload button on the screen that says "Verbindung wird aufgebaut" (connecting). 
Whenever I temporarily leave my desk (and the WLAN net) ThreemaWeb tries to connect but doesn't prevail (stopping at 12% or so). When I'm back at the desk a minute later I'm missing a reconnect button. Instead I have to close and reopen ThreemaWeb or hit the start session function on my phone, or both.

**Comment by lgrahl** [comment]
Resolved a while ago.
