### ISSUE TITLE
Message input edit line is not automatically focused when clicking on a contact

### ISSUE THREAD

**Issue by wschlich** [threema-ch/threema-web#41]
When clicking on a contact in Threema Web, the message input edit line is not automatically focused (like it is in WhatsApp Web), thus forcing the user to move the mouse to the input edit line and clicking into it (which sucks usability-wise).
The expected behaviour is to be able to start typing right away after clicking on a contact.

**Comment by rugk** [comment]
When I reported this in the Beta Threema said "that's the same as it's done in the Threema app, so it is by-design".
Nevertheless I'd think this change would be very good to improve the UX.

**Comment by wschlich** [comment]
@rugk : When I open Threema on Android, the message input edit line *is* automatically focused. The keyboard is not automatically shown, but the focus is there ;-)

**Comment by sillych** [comment]
we surrender :smile:

**Comment by rugk** [comment]
😂
It's a good choice.😎

**Comment by wschlich** [comment]
Whoohoo! Thank you, @sillych \\0 0// \0/
