### ISSUE TITLE
Mention: Cursor hidden after input

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#421]
## Expected Behavior

Do not hide cursor

## Current Behavior

Very similar to https://github.com/threema-ch/threema-web/issues/262 the cursor is hidden after writing `@` thing.

![webmention](https://user-images.githubusercontent.com/11966684/35965869-7543cf9c-0cbc-11e8-97c7-ef0cef7d1239.gif)

## Your Environment

* Threema Web version: 1.8.1 (beta)
* Browser name and version: Firefox 58

**Comment by dbrgn** [comment]
Close, same reason as in #422.
