### ISSUE TITLE
Starting message with mention makes it impossible to write text before that

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#422]
## Expected Behavior

It should always let me add text before the mention.

## Current Behavior

At the end of the gif, you can see that I cannot use the left key to move to the position before the mention. When adding the mention later, this is, however, possible.

## STR

1. Begin with `@Someone` and add mention.
2. Try to use the left key on you keyboard to move before that mention.

![webmention](https://user-images.githubusercontent.com/11966684/35965869-7543cf9c-0cbc-11e8-97c7-ef0cef7d1239.gif)

## Your Environment

* Threema Web version: 1.8.1 (beta)
* Browser name and version: Firefox 58

**Comment by dbrgn** [comment]
I'll close this in favor of #420
