### ISSUE TITLE
Autocomplete mention

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#423]
## Expected Behavior

When adding a space after a name, it should automatically show that as a mention.

## Current Behavior

I have to click on the name to "really" select it.

## Steps to Reproduce (for bugs)

1. Write `@Ich<space>`.

## Your Environment

* Threema Web version: 1.8.1 (beta)
* Browser name and version: Firefox 58

**Comment by dbrgn** [comment]
That way there would be no way to actually write "@Ich" without making it a mention. I don't think we will implement that change.

**Comment by rugk** [comment]
On GitHub it is done like that, too. Why should one write `@someone` without making a mention, altogether?

**Comment by dbrgn** [comment]
My post is actually a good example. I had no intention of mentioning (and thus notifying) @ich, sorry about that! :)

If you want to quickly mentoin someone, just type @ and the name, and then press enter. Then the mention will be inserted automatically.
