### ISSUE TITLE
Can't click on own mention in Threema Web

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#449]
## Expected Behavior
Threema support says it should be possible to click on own mention (?).

## Current Behavior
Does not work in Threema Web. Also in the app there is a bug (one has to wait ~7 seconds until you're at your own profile). I've already reported the bug in the app to the Threema support.

![bildschirmfoto_2018-02-23_14-21-47](https://user-images.githubusercontent.com/8258609/36596184-23f0f292-18a5-11e8-98b7-66de8a1d613d.png)

**Comment by ovalseven8** [comment]
By the way: Best solution would be to completely delete @Ich/@Me mentions in Threema because they are extremely confusing sometimes. I wrote already a detailed problem description to the Threema support. Let's see if they change the current behaviour.

**Comment by dbrgn** [comment]
The own profile is not (yet!) implemented in Threema Web (#221), so there's no place we can link to.

Reporting bugs in the app is the way to go :slightly_smiling_face:
