### ISSUE TITLE
Data between multiple tabs are not synced

### ISSUE THREAD

**Issue by meyerjo** [threema-ch/threema-web#45]
It is possible to open Threema web in multiple tabs, however new messages are only synced with one of the threema web instances.

**Comment by dbrgn** [comment]
This should be possible, as long as each session is independent (meaning that you scan a QR code for both sessions). I just tested it and it works fine.

**Comment by lgrahl** [comment]
What you might have seen is that a tab/window is not synchronising when it's not active.
