### ISSUE TITLE
Most recently opened chat is marked as active when you reconnect to session

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#451]
Two bugs:

- When you hover over most recently opened chat -> No pointer as cursor
- Most recently opened chat in Threema Web is marked as active - although not open (`background-color: #F6F6F6;`) - even if we do not hover over that area

![bildschirmfoto_2018-02-25_21-32-09](https://user-images.githubusercontent.com/8258609/36646165-5f7c614a-1a74-11e8-84db-5b0b9e4814a6.png)

## Steps to Reproduce
1. Reconnect to session
2. Click on some random chat
3. Close session
4. Reconnect to session
5. Last recently chat that was open in Threema Web (see 2) is marked as active and no pointer as cursor when you hover over it

## Your Environment
* Threema Web version: 1.8.2
* Threema for Android version: 3.14
* Threema for Android source: Play Store

**Comment by IndianaDschones** [comment]
I don´t think your first bug is a real bug :wink: Because you view the "active" conversation ther is no need to show a pointer and thus indicate the chat can be opened multiple times or sth.

**Comment by ovalseven8** [comment]
> I don´t think your first bug is a real bug wink Because you view the "active" conversation ther is no need to show a pointer and thus indicate the chat can be opened multiple times or sth.

You're right. It's the right behaviour, the problem is that the conversation is "active".

**Comment by IndianaDschones** [comment]
My PR #469 should fix this by setting all conversations as inactive when leaving/deleting the session 😃
