### ISSUE TITLE
URL should never be interpreted by markupprocessor

### ISSUE THREAD

**Issue by mist** [threema-ch/threema-web#453]
## Expected Behavior

When I post `example.com/_link_/` it should be shown as this and linked as this.

## Current Behavior
Currently it is shown as  `example.com`_`link`_`/` (but without the spaces) with only the `example.com` interpreted as link.

## Possible Solution
Don't try to interpret markup when a link is recognized

## Steps to Reproduce (for bugs)

1. Send a message containing `example.com/_link_/` to anybody.

## Your Environment

* A friend can reproduce this bug with probably different environment.
* The Bug also exists in the app itself I realized while testing.

* Threema Web version: 1.8.2
* Threema for Android version: 3.4.2000406
* Threema for Android source: Play Store
* Browser name and version: Firefox 58.0.1
* Operating system and version: Debian/testing

**Comment by dbrgn** [comment]
Implemented in beta branch.
