### ISSUE TITLE
Bug while converting emoji shortnames 

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#454]
## Expected Behavior
`:smile:` -> :smile: 

## Current Behavior
If you use the blank key after you wrote `:smile:` very quickly, you get ::smile: as result (notice the leading colon). If you wait a few deciseconds after you wrote `:smile:` everything is okay.

Can you reproduce?

* Threema Web version: 1.8.2
* Browser name and version: Firefox 58.0.2

**Comment by dbrgn** [comment]
Probably a race condition because the cursor position was advanced already before calculating the offsets.
