### ISSUE TITLE
Emoji style changes while switching between chats

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#455]
## Expected Behavior
Keep to one emoji style

## Current Behavior
Different emoji style

## Steps to Reproduce (for bugs)
1. Reconnect to Threema Web session
2. Go to a random chat
3. Write `Hey, how are you :smile:`
![screenshot-2018-3-2 threema web](https://user-images.githubusercontent.com/8258609/36895326-cfeae008-1e0e-11e8-8884-02946123a698.png)
4. Go to another chat
5. `Hey, how are you :smile:` is now saved as draft
![screenshot-2018-3-2 threema web 1](https://user-images.githubusercontent.com/8258609/36895345-d9ea8d92-1e0e-11e8-93d9-9b1515b5e958.png)
6. Now, style changed (no default EmojiOne character)
7. When you change back to chat, still no EmojiOne character
![bildschirmfoto_2018-03-02_11-45-58](https://user-images.githubusercontent.com/8258609/36895512-65f1e29a-1e0f-11e8-86c6-9aa58b94e9f2.png)
Also note: Cursor is at the beginning. It's better to have it at the end of the sentence!
8. When you send the message, it changes again
![screenshot-2018-3-2 threema web 3](https://user-images.githubusercontent.com/8258609/36895420-1bd63b7a-1e0f-11e8-872c-c98e421d2d1c.png)

## Your Environment
* Threema Web version: 1.8.2
* Threema for Android version: 3.14
* Browser name and version: Firefox 58.0.2

**Comment by dbrgn** [comment]
That's a bug, emojis are apparently not rendered in drafts. They should.

**Comment by rugk** [comment]
> Also note: Cursor is at the beginning. It's better to have it at the end of the sentence!

Maybe open a new issue for that.
