### ISSUE TITLE
Parsing bug in Threema Web

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#458]
## Current Behavior
Flawed input parsing. Perhaps related to #453.

## Steps to Reproduce (for bugs)
1. Write `<_< >_>`
2. Sent/Received is: ` << >>`

![screenshot-2018-3-2 1 threema web](https://user-images.githubusercontent.com/8258609/36911094-d387df8e-1e42-11e8-8cfa-d757a90a6a94.png)

* Threema Web version: 1.8.2
* Threema for Android version: 3.4
* Browser name and version: Firefox 58.0.2

**Comment by dbrgn** [comment]
Fixed in beta branch.
