### ISSUE TITLE
Missing audio notification

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#459]
## Expected Behavior
Play audio notification.

## Current Behavior
Threema Web does not play audio notification under weird circumstances?

I could imagine it has something to do with #451.

## Steps to Reproduce (for bugs)
(Make sure that audio notification is enabled in the web application)
1. Delete the whole chat with ECHOECHO in the app
2. Reconnect to Threema Web session
3. Write `Hi` to ECHOECHO in the Android app
4. You'll hear audio notification in the web application (as expected)
5. Delete whole chat with ECHOECHO in the app
6. Write `Hi` to ECHOECHO again
7. You won't hear any audio notification in the web application

Can you reproduce?

## Your Environment
* Threema Web version: 1.8.2
* Threema for Android version: 3.4
* Threema for Android source: Play Store

**Comment by ovalseven8** [comment]
Well, I will close for now. I'm pretty sure it's #451. What do you mean, @dbrgn?

**Comment by dbrgn** [comment]
Sounds like a plausible explanation.
