### ISSUE TITLE
Inconsistent error messages if you want to send message to blocked contact

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#462]
## Expected Behavior
Consistent error message. I'd prefer the second screenshot.

## Current Behavior
Inconsistent error message.

## Steps to Reproduce (for bugs)
1. Connect to Threema Web
2. Block a contact in the smartphone app
3. Try to write a message to the blocked contact in Threema Web
4. You'll see this error message:
![bildschirmfoto_2018-03-02_18-26-25](https://user-images.githubusercontent.com/8258609/36913129-3b47bd96-1e49-11e8-9b44-1f1efcc038c5.png)
5. Close Threema Web session and reconnect
6. Now try to write a message to the blocked contact again
7. You'll see this error message:
![bildschirmfoto_2018-03-02_18-25-03](https://user-images.githubusercontent.com/8258609/36913167-5dcffc16-1e49-11e8-9d62-0622a0b203a4.png)

## Your Environment
* Threema Web version: 1.8.2
* Threema for Android version: 3.4
* Browser name and version: Firefox 58.0.2

**Comment by IndianaDschones** [comment]
I´ll solve this issue and open a PR in a few minutes.

IMHO the compose area should be hidden for blocked contacts. Like it is hidden for deleted group chats.

@sillych This should also be done in the Threema Apps. In addition the "blocked icon" should also be shown in the Apps.
