### ISSUE TITLE
Distribution list is not displayed immediately (even if created in Threema Web)

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#463]
## Steps to Reproduce (for bugs)

1. Connect to Threema Web
2. Create distribution list in Threema Web or in the smartphone app
3. Distribution list is not displayed in Threema Web
4. We have to reconnect to Threema Web

## Your Environment
* Threema Web version: 1.8.2
* Threema for Android version: 3.4
* Browser name and version: Firefox 58.0.2

**Comment by ovalseven8** [comment]
Because it is related and I do not want to create just another issue:

The deletion of a distribution list is also badly synced:
1. Delete distribution list in Threema Web
2. Distribution list is still displayed
3. You can even write a message, however this error occurs then:
![bildschirmfoto_2018-03-02_19-05-16](https://user-images.githubusercontent.com/8258609/36914263-fc32b6fc-1e4c-11e8-9a6f-7dff391c7689.png)

**Comment by dbrgn** [comment]
This should be fixed with the next Android app release. Sorry for the long delay :slightly_smiling_face:
