### ISSUE TITLE
Threema Web cannot handle gifs

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#465]
Use this gif for example: https://media1.giphy.com/media/us8FXd0EtOXXa/giphy.gif

Threema Web can not send .gif files.

When sent as file: It's sent as .png image actually!
When sent as image: It's sent as .img image actually!

:disappointed: 

## Your Environment
* Threema Web version: 1.8.2
* Threema for Android version: 3.4
* Browser name and version: Firefox 58.0.3

**Comment by dbrgn** [comment]
That is actually a video file on that page. How do you send it?

**Comment by dbrgn** [comment]
If you try to copy-paste, you're not actually copying the GIF. You're just copying the current frame of the gif, and that's what ends up being sent (tested with both Chrome and Firefox).

I think if you want to send GIFs, there's no way around sending them as files (via file picker or via drag & drop).

**Comment by ovalseven8** [comment]
You're right, sorry. :smile:
