### ISSUE TITLE
Active .gif image prevents scrolling

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#466]
## Expected Behavior
Just scroll through your chat.

## Current Behavior
When I scroll to the top of the chat history, Threema Web automatically scrolls back to the bottom when the .gif image is active.

## Steps to Reproduce (for bugs)
1. Send a .gif image through the app (it's not possible with Threema Web at the moment)
2. Click on the .gif image
3. Scroll

## Your Environment
* Threema Web version: 1.8.2
* Threema for Android version: 3.4
* Browser name and version: 58.0.2

**Comment by dbrgn** [comment]
This seems to be a special / extreme case of #18. Probably the GIF playback is interfering with the scrolling, maybe something to do with `requestAnimationFrame`. I'll add a note to that thread.

Also, sending GIFs through Threema Web works fine, just send it like a regular image.

**Comment by ovalseven8** [comment]
Also everything is even more laggy when the gif is playing.
