### ISSUE TITLE
Show distribution list members in conversation header

### ISSUE THREAD

**Issue by IndianaDschones** [threema-ch/threema-web#470]
## Expected Behavior

Show distributionlist members in conversation header
## Current Behavior

Members ar not shown
## Possible Solution
I open a PR in a few minutes to solve this issue

**Comment by dbrgn** [comment]
> I open a PR in a few minutes to solve this issue

Cool!

Btw, if you're already working on a pull request, then you don't need to open an issue. Opening issues before doing a PR is primarily meant as a way to prevent work being done that later cannot be used, for example because we're already working on that in parallel, or someting like that :)

**Comment by IndianaDschones** [comment]
Okay, i keep this in mind for my next PRs 😉
