### ISSUE TITLE
Harmonize chat bubbles design

### ISSUE THREAD

**Issue by IndianaDschones** [threema-ch/threema-web#474]
## Expected Behavior

The chat bubble in the web app should look like the Android bubbles, see [Google Play Screenshots](https://play.google.com/store/apps/details?id=ch.threema.app)
## Current Behavior

The web app is using the "old" design
## Possible Solution

Use the same design as in the Android app

## Your Environment

* Threema Web version: 1.8.2
* Threema for Android version: 3.41
* Threema for Android source: Play Store

**Comment by dbrgn** [comment]
The chat bubbles don't need to look the same as on Android (e.g. if you connect from an iOS device you don't have the expectation that it looks like Android).

If someone proposes a design change (as a PR) that we like more than the current styling, we'd consider it though :)
