### ISSUE TITLE
WebRTC whitelist only for Threema Web in FF?

### ISSUE THREAD

**Issue by Cris--** [threema-ch/threema-web#477]
## Expected Behavior
WebRTC IP leak in Firefox
https://restoreprivacy.com/webrtc-leaks/

Hi,
i know its not the perfect place to ask this question, sry!
Is there a way in Firefox to accept WebRTC connections only for https://web.threema.ch/
to prevent other domains to sniff my IP?

e.g.: A VPN or Tor is not ideal!

**Comment by rugk** [comment]
AFAIK no. There are only [add-ons](https://addons.mozilla.org/de/firefox/search/?q=webrtc) where you can enable/disable the setting. So you could enable it only when you need it.

**Comment by joelfischerr** [comment]
The electron app proposed in #52 might be a solution.

**Comment by dbrgn** [comment]
Or using a separate browser or firefox profile for Threema Web.

**Comment by joelfischerr** [comment]
Alternatively are profiles (https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) a solution?

**Comment by lgrahl** [comment]
I'll close this one since this is mainly a browser thing. However, I would definitely upvote a [bug report for Firefox](http://bugzilla.mozilla.org/).
