### ISSUE TITLE
Feature request: Mute app when web client is connected

### ISSUE THREAD

**Issue by suamikim** [threema-ch/threema-web#494]
When I have a web client connected, it gives me notifications of new messages etc.
Therefore I don't need them on my phone as well.

I'd really appreciate a setting within the app which mutes all notification sounds & vibrations temporarily as long as at least 1 web client is connected.

Manually enabling & disabling the notifications in the app when connecting/disconnecting a web client is very cumbersome and "easy to be forgotten".

**Comment by ovalseven8** [comment]
=> #21

**Comment by dbrgn** [comment]
Thanks, @ovalseven8.

@suamikim feel free to copy your comment to the other thread (#21).
