### ISSUE TITLE
Display warning when closing Threema Web with messages still in the queue/outbox

### ISSUE THREAD

**Issue by joelfischerr** [threema-ch/threema-web#504]
## Expected Behavior
If Threema Web is closed while messages are still in the queue/outbox those messages are lost without the user being notified about it. Displaying the usual you have entered text/messages in the outbox popup could help loosing fewer messages.

## Current Behavior
See Expected behaviour.

## Possible Solution
See Expected Behaviour

## Your Environment

* Threema Web version: 2.0.0-beta.1
* Threema for ~Android~ iOS version: iOS 4.0
* Threema for ~Android~ source: App Store
* Browser name and version: All browsers
* Operating system and version: All operating systems

**Comment by dbrgn** [comment]
No messages should be lost. I assume the reason for this behavior was the bug in the reconnect logic (see https://github.com/threema-ch/threema-web/issues/506#issuecomment-394269949).

Please let me know if the problem persists with iOS app build 2310+.

**Comment by joelfischerr** [comment]
By disconnecting the phone from the network and then sending a message in Threema Web without reconnecting the phone before closing Threema Web, messages can still be lost.
I think this could also happen accidentally.

Messages are currently not being lost anymore if the phone is connected to a network, but they are sometimes still sent out of order as described in #505.

**Comment by lgrahl** [comment]
Please ping us if this is still relevant.
