### ISSUE TITLE
Received messages are not always loaded when Threema Web was open for a long time

### ISSUE THREAD

**Issue by joelfischerr** [threema-ch/threema-web#506]
## Expected Behavior
Received messages should always be displayed/loaded.

## Current Behavior
Sometimes the web client is not woken up when new messages arrive.

## Possible Solution
Force reconnect when the web client tab is opened again.

## Steps to Reproduce (for bugs)
1. Force quit the iOS app
2. Receive a message
3. Message is not shown in Threema Web

## Your Environment
* Threema Web version: 2.0.0-beta.1
* Threema App version: 4.0 (2309)
* Browser name and version: Safari 11
* Computer operating system and version: macOS 10.13
* Smartphone operating system and version: iOS 11.4

**Comment by dbrgn** [comment]
@joelfischerr Is this still a problem with build 2310? Build 2309 contained a bug that often prevented the connection from being re-established.

**Comment by joelfischerr** [comment]
I don't think I have seen the problem occur with build 2310.
