### ISSUE TITLE
Still get browser notifications for "do not disturb" chats

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#507]
## Expected Behavior

No browser notifications. (as it also is done correctly in the app, where I get no notification)

## Current Behavior

I still get browser notifications, just without a sound. (as if they were just "muted")

## Steps to Reproduce (for bugs)

1. Mark a (group) chat in Threema as "do not disturb (unless you are @mentioned). And I don't mean the "mute" setting by it – this can stay the default.
2. Get a message in that chat while connected to Threema Web.

## Your Environment

* Threema Web version: 1.8.2-gh 
* Threema App version: 3.41
* Browser name and version: Firefox 60
* Computer operating system and version: Fedora 28 (GNOME)
* Smartphone operating system and version: Android

**Comment by dbrgn** [comment]
This is already implemented in the 2.0.0 beta.
