### ISSUE TITLE
Videos are downloaded without filename extension

### ISSUE THREAD

**Issue by joelfischerr** [threema-ch/threema-web#510]
## Expected Behaviour
Downloading a video results in a file called Unknown.mp4 being downloaded.

## Current Behavior
Downloading a video results in a file called Unknown being downloaded.

## Steps to Reproduce (for bugs)
1. Download a video
2. File will not have a filename extension

## Your Environment
* Threema Web version: 2.0.0-beta.2
* Threema App version: 4.0 (2310)
* Browser name and version: Safari 11
* Computer operating system and version: macOS 13.14
* Smartphone operating system and version: iOS 11.4

**Comment by dbrgn** [comment]
We cannot reproduce this. Maybe you received this video as a file message and the filename is actually "Unknown.mp4"?

**Comment by joelfischerr** [comment]
I have tried it with multiple files and it has happened with all of them.

**Comment by joelfischerr** [comment]
I have tried it with jpg, gif and mp4.

**Comment by dbrgn** [comment]
@joelfischerr in case this problem still persists, can you maybe create a video or post very precise steps-to-reproduce? We still cannot reproduce the issue.

**Comment by joelfischerr** [comment]
Clearing cookies and the cache has somehow solved this problem. I have no idea what could have caused it.
