### ISSUE TITLE
Unusable chat window

### ISSUE THREAD

**Issue by isk0001y** [threema-ch/threema-web#513]
## Expected Behavior
Chatting

## Current Behavior
Using Google Chrome, after the threemaweb connection is established, I cannot make the cursor accept input. Only cmd+v works. If I start to type, the cursor loses focus and chrome starts "search in page"

## Possible Solution
No Idea

## Steps to Reproduce (for bugs)
I just activated my beta threema test, and it is unusable :-(

## Your Environment
* Threema Web version: 2.0.0.beta3
* Threema App version: 4.0 2315
* Browser name and version: Chrome, 66.0.3359.181
* Computer operating system and version: MacOS 10.13.5
* Smartphone operating system and version: IOS 11.4

Thanks in advance!
Yusuf

**Comment by isk0001y** [comment]
I tested Safari. It works in Safari. But not in Chrome.

**Comment by dbrgn** [comment]
Do you by chance use some kind of add-on like vimium that intercepts keypresses?

**Comment by isk0001y** [comment]
That was the solution. I dont have many add-ons. Only 5. One of them is type-ahead-find. Disabling it helped. However, I never had any issue with typing in a webpage except threema-web...

**Comment by dbrgn** [comment]
Thanks, good to know. We also had some issues with Grammarly: #280.

Will have to look into this.

**Comment by dbrgn** [comment]
Closing in favor of #280.
