### ISSUE TITLE
Feedback when "copy to clipboard"

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#517]
## Expected Behavior

As the Threma app does, show a notification somewhere "text copied" or so.

## Current Behavior

The menu just vanishes. I doubt it is enough to signal to the user that the process worked.

## Steps to Reproduce (for bugs)

1. Copy a text.

**Comment by dbrgn** [comment]
Fixed by 19036d85a889d323b848d566811bdc23ac03a9de.
