### ISSUE TITLE
Flashing battery icon is CPU intensive

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#519]
Turns out the pulsating battery icon is very CPU intensive, at least in Firefox. Weirdly...

**Comment by dbrgn** [comment]
It's just this :roll_eyes: https://github.com/threema-ch/threema-web/blob/master/src/sass/components/_battery.scss#L6-L8

How did you measure the CPU load? Can you try this? https://jsfiddle.net/Ly1sgt89/3/

**Comment by lgrahl** [comment]
> How did you measure the CPU load?

System Monitor.

Your fiddle creates ~3% of load (which is still too much) but in the web client it was around 25%.

**Comment by dbrgn** [comment]
> which is still too much

I'm not sure. If you think so, you should probably file a Firefox bug, together with a performance trace.

25% is very high though. I'll have to take a look at that later.

**Comment by lgrahl** [comment]
Yes, my notebook fan didn't like it. :smile_cat:

**Comment by dbrgn** [comment]
Replaced with a non-flashing red icon in the `ios` branch.

**Comment by dbrgn** [comment]
> Yes, my notebook fan didn't like it.

@lgrahl:

![commitstrip comic](http://www.commitstrip.com/en/2018/08/22/profiling/)
