### ISSUE TITLE
Creator of group as some strange undefined/NaN stuff at the end

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#524]
## Current Behavior

> Ersteller (NaN. undefined NaN, aN:aN)

![grafik](https://user-images.githubusercontent.com/11966684/42594840-bb462186-8550-11e8-9298-fe265cf4344c.png)

## Steps to Reproduce (for bugs)

1. Go to the group details of any group.

## Your Environment

* Threema Web version: v 2.0.0-beta.7
* Threema App version: beta
* Browser name and version: Firefox 61

**Comment by dbrgn** [comment]
Cannot reproduce this issue with the provided information.
