### ISSUE TITLE
Various errors trying to connect to https://web.threema.ch

### ISSUE THREAD

**Issue by renao** [threema-ch/threema-web#537]
Hello Threema Web team,

thanks for providing this great possibility to write Threema messages at the desktop :+1:

I don't know if this is an issue with our companies firewall or the Threema web servers I keep on investigating but wanted to let you know, that there was something happening (and perhaps this will be helpful for others googling a similiar problem)

## Expected Behaviour

Threema Web should be displayed.

## Current Behavior

Firefox refuses to connect (Secure connection refused: `SSL_ERROR_RX_RECORD_TOO_LONG`)
Chrome refuses to connect (Website not available: `ERR_TUNNEL_CONNECTION_FAILED`)
Internet Explorer tells me to activate TLS (see attached screenshot)

## Your Environment

Windows 10 OS.

Browser-Versions: 

* `Firefox 61.0.1` 
* `Chrome 67.0.3396.99`
* Internet Explorer `11.2273.14393.0`

Internet Explorer output (sorry, only in German available - honestly I wanted to show that TLS and SSL is activated):

![screenshot 10](https://user-images.githubusercontent.com/3899638/43446254-a7665250-94a8-11e8-8936-2348cd00392f.jpg)

**Comment by rugk** [comment]
As for the shown IE settings, better disable SSL 3.0. It's not secure anymore. (And, AFAIK, it should be disabled by default even in IE)

**Comment by dbrgn** [comment]
Hm, this looks like a misconfigured proxy/firewall to me. Maybe the proxy is trying to intercept the TLS connection somehow?

Did you already contact your sysadmin about this?

**Comment by renao** [comment]
Thanks for the (instant!) replies.

I will get in contact with the sysadmin first 👍

**Comment by lgrahl** [comment]
Any news on this?

**Comment by renao** [comment]
Hey @lgrahl ,

I am sorry for replying this late. I just figured out that one of our DNS is malconfigured and it will (unfortunately) take some time to fix.

So it looks like not being your problem 👍 🥇 

Thanks for keeping up my favorite IM :-)
Renão
