### ISSUE TITLE
Improve build toolchain

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#539]
Currently we're using Browserify + Babel to generate an ES5 bundle.

Since browser support is better nowadays, we can generate ES2015 directly. For that, we should use [Babel Preset Env](https://babeljs.io/docs/en/babel-preset-env) with the browser versions we want to target.

When already looking at the build toolchain, we should also evaluate whether we might gain any advantages from moving to Webpack.

**Comment by lgrahl** [comment]
And then we can try moving the upcoming `Future` class into the TS code again (which currently produces some weird JS errors).
