### ISSUE TITLE
Cancel low battery alert when phone is plugged in 

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#540]
When the phone is plugged in, any existing low battery alerts should clear.

**Comment by SirTyson** [comment]
Mind if I look into this?

**Comment by lgrahl** [comment]
Go for it. :+1:

**Comment by dbrgn** [comment]
@SirTyson go ahead! :slightly_smiling_face: That shouldn't be too hard.

Some pointers:

- The incoming battery status message is processed in the webclient service (`_receiveUpdateBatteryStatus`): https://github.com/threema-ch/threema-web/blob/135a8d411e1b427b03a9cd44af11955ab9821d79/src/services/webclient.ts#L2338
- Handling battery status updates and notifications is done in the battery status service: https://github.com/threema-ch/threema-web/blob/master/src/services/battery.ts

There seems to be code that should clear the notifications, but there's probably something wrong with it. (I have in mind that it used to work, but at least on current Firefox it does not.)

**Comment by SirTyson** [comment]
Thanks for the help @dbrgn. Quick question, I'm having some trouble testing the web app. I have a local host server set up and I can connect to it from a virtual android device, but I can't get past the QR code scan page. Any advice?

**Comment by dbrgn** [comment]
How do you scan the QR code with the emulator?

I don't really have experience with the emulator, I always use a real phone for development :)
