### ISSUE TITLE
Threema Web shows link to media files although it's not really a link to those

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#544]
## Expected Behavior
Do not show a link to media files here because actually it's just for chat switching. Remove link and display it like in the app.

## Current Behavior

Not really a bug, but a __minor__ UI flaw IMHO. 

![bildschirmfoto_2018-08-03_08-08-16](https://user-images.githubusercontent.com/8258609/43627106-2eeb1564-96f5-11e8-9318-8165de7ef18e.png)

## Your Environment
* Threema Web version: 2.0.0
* Threema App version: 3.50
* Browser name and version: Firefox 61.0.1

**Comment by SirTyson** [comment]
I can work on this.

**Comment by dbrgn** [comment]
Hm, for some reason the linkify function thinks `zip` is a TLD. Probably because [it is one](https://ntldstats.com/tld/zip) :slightly_smiling_face: 

Anyways, the linkify function should not be applied to the "last message" preview at all.
