### ISSUE TITLE
BROWSER_NOT_SUPPORTED - not localized

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#57]
![strings](https://cloud.githubusercontent.com/assets/11966684/23037851/2d20f4da-f488-11e6-995d-efeeb6794173.png)

https://twitter.com/NerdingByDoing/status/832266474995736577

/cc @corrupt

**Comment by dbrgn** [comment]
They aren't missing. But in some cases the dialog appears before the strings were loaded. I couldn't reproduce it so far (but didn't spend a lot of time on it yet).

**Comment by corrupt** [comment]
This happens on GNU Icecat every time.

**Comment by dbrgn** [comment]
I just installed Icecat 45.5.1, launched it, unchecked the checkbox to block non-free JS (Threema Web doesn't load otherwise) and loaded Threema Web. There was a short (<1s) flash of untranslated content, but then everything looked fine (even after reloading).

**Comment by lgrahl** [comment]
Maybe you guys can display that popup box as soon as the JS has been loaded to avoid further confusion.
