### ISSUE TITLE
Read messages not marked as read

### ISSUE THREAD

**Issue by luminatedhorizons** [threema-ch/threema-web#577]
## Expected Behavior
A new message is received. Opening Threema Web, reading the message (even answering). The message notification disappears on the "original" smartphone. 

## Current Behavior
On the Android phone, this message is staying as new, notified message. 

## Steps to Reproduce (for bugs)

1. Receive a new message in Threema. 
2. Open Threema Web. 
3. Read the new message. 
4. Check on the smartphone, whether the message notification disappeared. 

## Your Environment

* Threema Web version: 2.0.3
* Threema App version: 3.53.2000436 Google Play 
* Browser name and version: Firefox 61.0.2
* Computer operating system and version: Windows 10 1803
* Smartphone operating system and version: Android 8.0.0

**Comment by dbrgn** [comment]
I cannot reproduce this behavior. On my device (Also with Android 8), the notification is cleared immediately.

@luminatedhorizons in your case, is the message itself marked as read in the app and in Threema Web (meaning that the only problem is the notification), or is it also still unread after opening the conversation in Threema Web?

**Comment by luminatedhorizons** [comment]
Many thanks for checking .. i have to admit, i cannot reproduce on my own anymore. I even didnt notice, since working things are in themselves rarely noticed ;) Sorry, closing the issue by that!

**Comment by dbrgn** [comment]
@luminatedhorizons thanks for the feedback :slightly_smiling_face:
