### ISSUE TITLE
State changes aren't necessarily part of a digest cycle

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#578]
When the peer connection state changes, it seems that the state change isn't always done in an angular digest context.

**Comment by dbrgn** [comment]
Can you elaborate? In what case is that not being done? Do you have a log?

In `src/services/peerconnection.ts`, the only real reaction to state changes I could find (apart from logging) is `this.pc.oniceconnectionstatechange`, which *does* run state changes in the digest loop.

**Comment by lgrahl** [comment]
Was fixed by #551
