### ISSUE TITLE
Report Tool

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#579]
We need a report tool to reduce the effort required to report logs to the support team and aggregate them with the corresponding app log.

**Comment by ovalseven8** [comment]
Just tried it out. But I wonder if it should additionally be present in this menu:
![Bildschirmfoto vom 2019-08-02 13-10-28](https://user-images.githubusercontent.com/8258609/62408534-d7cbf500-b5ca-11e9-98ff-1f51f7428bb7.png)

**Comment by lgrahl** [comment]
Good idea.
