### ISSUE TITLE
iOS Support Request

### ISSUE THREAD

**Issue by djdesign** [threema-ch/threema-web#58]
iOS Support Request Please.

**Comment by rugk** [comment]
As you can read on the website, it is planned.

**Comment by 00SteinsGate00** [comment]
Any updates on this? It's been over half a year since Android users can enjoy Threema Web...

**Comment by ovalseven8** [comment]
Just speculation, but I think at the beginning of 2018 Threema Web for iOS could come true. :) So in a few months.

**Comment by dwickwire** [comment]
Aren't android users supposed to be the ones lagging behind, what are we paying all this money to Apple for?   🦆

**Comment by monouser7dig** [comment]
Any news?

**Comment by dbrgn** [comment]
Work in progress, we haven't forgotten you :)

**Comment by monouser7dig** [comment]
okay, hope to see it soon

**Comment by neok0** [comment]
we really would like to have the web feature also for ios, are there any updates?

**Comment by joelfischerr** [comment]
There is no official estimated time of arrival and there are no comments on the progress from Threema itself.
But you can view the progress of the libraries used to make Threema Web for iOS work here https://github.com/saltyrtc/saltyrtc-task-relayed-data-rs and here https://github.com/saltyrtc/saltyrtc-client-rs

**Comment by neok0** [comment]
it's a bit sad that iOS user need to wait that long..:(

**Comment by monouser7dig** [comment]
https://threema.ch/de/blog/posts/threema-web-ios

iOS Web „Beta Release Mai“

**Comment by dbrgn** [comment]
Here's the english announcement: https://threema.ch/en/blog/posts/threemas-web-client-ios

Work in progress PR: https://github.com/threema-ch/threema-web/pull/475

**Comment by neok0** [comment]
"..until May" interessting... is the beta at least already out? In the mean time publishing a blog post with reasons why we should pay for threema, but beeing the only messager without a desktop client...

**Comment by dbrgn** [comment]
@neok0 the announcement was not "until May", it was "by May" :slightly_smiling_face:

**Comment by neok0** [comment]
@dbrgn fair enough, lets see ;)

**Comment by ovalseven8** [comment]
Threema Web for iOS: Beta test begins:
https://threema.ch/en/blog/posts/threema-web-for-ios-beta

**Comment by skate056** [comment]
Any update on the beta progress and when it will be generally available?

**Comment by dbrgn** [comment]
Hopefully very soon™ :slightly_smiling_face: There is no official ETA though, since it depends on a lot of factors (closed and open beta testing, Apple verification processes, etc).

**Comment by lgrahl** [comment]
Also blocked by #551 (hopefully the last one).

**Comment by skate056** [comment]
Thanks for the update! Eagerly waiting for this 😃

**Comment by blissd** [comment]
Really missing Threema Web since migrating from Android to iOS. Looking forward to this being released soon.

**Comment by monouser7dig** [comment]
the app still crashes every week even though I don't even use it much (using the beta, yeah always send crash reports to you)

**Comment by dbrgn** [comment]
iOS support is well underway. We will release it as soon as we're happy with the stability. 

Sending crash reports definitely helps! Until the release is out, we'll lock this issue to prevent unnecessary noise.
