### ISSUE TITLE
Connection bar is going nuts for iOS

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#580]
The connection bar is showing all sorts of colours before and after having closed a connection due to the hacky way it is being updated when used with an iOS. We should probably refactor this when implementing #498 for Android.

**Comment by dbrgn** [comment]
The "all sort of colours" thing is the bar changing to red and then immediately to yellow, with CSS transitions enabled on the color attribute.

**Comment by lgrahl** [comment]
Nah, it stays at yellow, green or red, depending on the previous connection's state.
