### ISSUE TITLE
Using Synk for dependencies monitoring?

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#582]
Threema Web is using a lot of third-party dependencies.

[Synk](https://snyk.io/features) is a tool that can help to identify security vulnerabilities so that one can update those immediately.

Just wanted to hear your opinion about it and if not it would make sense here.

**Comment by dbrgn** [comment]
`npm audit` already gives a summary on known vulnerabilities of third party dependencies. And Github renders those warnings too :slightly_smiling_face: 

By the way, the largest part of the dependencies that are installed with `npm install` are only used for development and packaging (e.g. typescript, budo, browserify) and don't end up in the released version.
