### ISSUE TITLE
Missing MIME-Type for APK

### ISSUE THREAD

**Issue by simmac** [threema-ch/threema-web#59]
When sending an apk file via the web-client, the mime type of the file is marked as `application/octet-stream` instead of `application/vnd.android.package-archive`.
This is annoying because Android doesn't handle these files as apk-files.

The MIME-Type is set correctly when using the Threema App on Android directly, so it has to be a web-client issue.

Tested on Chrome 56, macOS 10.12

**Comment by simmac** [comment]
Here is an example, first file is sent via the web client, the second one via the Android app directly:
Receiving end on web:
<img width="445" alt="web" src="https://cloud.githubusercontent.com/assets/7317069/23044658/6eaa6d64-f4a1-11e6-8d48-dd1a86c631bd.png">
Receiving end in Android app:
![app](https://cloud.githubusercontent.com/assets/7317069/23044665/7a4a25ce-f4a1-11e6-8e4d-ce5d02d88f34.png)

**Comment by dbrgn** [comment]
Closed in favor of #90.

**Comment by dbrgn** [comment]
Hopefully fixed by #218. At least on Chromium 58 on Linux, the MIME type is set correctly. (It's the browser that does file type detection.)

If it doesn't work for you, let us know. But I'm not sure we could even do something about it.
