### ISSUE TITLE
Don't resize outgoing images

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#591]
Resizing of sent images should be optional.

**Comment by rugk** [comment]
Ref https://threema-forum.de/thread-4067-post-40141.html

**Comment by dbrgn** [comment]
I created a picture file that's 4000x4000px. Then I turned of media compression in the Threema app.

When sending the picture to a contact through Threema Web, it arrives at the same resolution.

As far as I know, Threema Web has never resized any images.
