### ISSUE TITLE
"+1 for priority" policy

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#592]
I think we already kind of follow the ":+1: for priority" policy but perhaps we should add it to the readme so it catches on?

> Express your personal opinion regarding priority by reacting with :+1: in a particular issue, such as [this one](https://github.com/threema-ch/threema-web/issues/58). We will factor this in when scheduling what to do next.

**Comment by dbrgn** [comment]
Yeah, why not :)
