### ISSUE TITLE
Prevent implicit closing of WebRTC data channel

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#594]
In Chrome (and it's derivatives), when the WebRTC data channel's buffering limit is being reached, the data channel implicitly closes when enqueuing more data. IIRC the limit was around 8 MiB.

This is one of the main issues responsible for #184.

https://github.com/saltyrtc/saltyrtc-task-webrtc-js/pull/21 fixes this but we also need to write this for the app side.

**Comment by rugk** [comment]
> In Chrome (and it's derivatives)

Sorry for the nitpick, but there are no (or few?) Chrome derivatives. Most are derivatives of _Chromium_. Sorry, I am into this. :wink:

**Comment by lgrahl** [comment]
Honestly, there's not much of a difference between those two any more... for the worse. But let's keep politics outside of this issue.
