### ISSUE TITLE
Show group members in header

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#6]
Show group members in header, below group name (similar to app).

**Comment by IndianaDschones** [comment]
I´d like to solve this issue.

**Comment by dbrgn** [comment]
@IndianaDschones :+1: go for it :)

**Comment by IndianaDschones** [comment]
@dbrgn It works but the group members string does not truncate. I added the necessary css properties
`        .group-members {
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }` but the text just ends instead of showing ellipsis.
![notruncate](https://cloud.githubusercontent.com/assets/6652142/23697633/cc0c0188-03e8-11e7-90a8-829dc8e642e4.PNG)

Do you have an idea?

**Comment by sillych** [comment]
@IndianaDschones did you try the `max-width:` property on the `group-members` element?

**Comment by IndianaDschones** [comment]
@sillych The `max-width:` property works if i also add `display: inline-block` to `group-members`.

**Comment by IndianaDschones** [comment]
@sillych I finally fixed it 🎉 
I added `overflow: hidden` to the `header-details` element. Creating a PR in a few.
