### ISSUE TITLE
webclient save images all under the same name (keep original filename)

### ISSUE THREAD

**Issue by nurps** [threema-ch/threema-web#61]
If I try so save multiple images from my browser (Chrome) every file is called image.jpg, very annoying to manually rename them. Keeping the original filename intact would be really handy, also in telling the person that send the photos about which photo I am talking.

**Comment by mimiks** [comment]
Image messages, as opposed to files, do not come with a filename, as they're modified from their original form by converting to JPG, stripping EXIF data and scaling. But a random uid could be used as filename instead of just «image.jpg».

**Comment by sillych** [comment]
Thanks! An uid already exist on message models, we will use this uid (string) to generate a "unique" filename
