### ISSUE TITLE
[request] Migrate ThreemaWeb to Electron based Desktop App

### ISSUE THREAD

**Issue by Kurisutian** [threema-ch/threema-web#62]
It would be awesome to port the WebApp to a seperate Electron (http://electron.atom.io/) based Desktop application. This way there would be one app for all systems (Windows, Linux, Mac) and the development does not need to deal with browser specific issues. So resources can be spend for iOS compatibility as well as extension of features or fixing bugs which do not rely on browser specifics.

**Comment by ovalseven8** [comment]
=> #52

**Comment by Kurisutian** [comment]
Sorry, I overlooked the issue #52 
-> Closed
