### ISSUE TITLE
Try to reduce battery drain

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#63]
The battery is one of the most important resources for a mobile phone. Because of that, every approach to reduce the battery drain is worth a try.

I am sure it's possible to optimize Threema Web here.
Further tests/reports welcome.

Noticed that the battery drain caused by Threema and WLAN on my Android phone is a lot higher than normal (used Firefox). Allegedly, it's even worse with Google Chrome.
Well, of course we should accept that Threema Web will drain the battery, but we should also look for optimizations if possible.

WhatsApp Web is doing better here, it works completely different, however.

Further reports:
- https://twitter.com/scampy_joe/status/832637376748924929
- https://twitter.com/DaMoisture/status/832332294241341440

**Comment by dbrgn** [comment]
I think #60 already covers this well enough. I renamed the other issue to clarify.
