### ISSUE TITLE
Messages shown as unread

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#651]
## Expected Behavior

Red unread message number should be hidden when nothing is unread.

## Current Behavior

For some reason a red "unread 1" is shown when I started my Threema web session. In the app, it is not visible. It also does not hide when I send a message.

Log filtered by affected other Threema user id:
```
20:24:27.567 Sending message request for contact **id-of-other-user** with message id null angular.js:15535:16
20:24:31.796 Sending read request for contact **id-of-other-user** (msg **004) angular.js:15535:16
20:24:42.959 Sending read request for contact **id-of-other-user** (msg **004) angular.js:15535:16
20:25:03.931 Sending read request for contact **id-of-other-user** (msg **004) angular.js:15535:16
20:27:21.282 Sending read request for contact **id-of-other-user** (msg **004) angular.js:15535:16
20:27:35.196 Sending high res avatar request for contact **id-of-other-user** angular.js:15535:16
20:27:43.161 Sending read request for contact **id-of-other-user** (msg **004) angular.js:15535:16
20:29:33.094 Sending read request for contact **id-of-other-user** (msg **004) angular.js:15535:16
```

## Steps to Reproduce (for bugs)

don't know, seems random and was the first/only time I noticed this

## Your Environment

* Threema Web version: 2.0.3-gh
* Threema App version: 3.59
* Browser name and version: Firefox
* Computer operating system and version: Fedora 28
* Smartphone operating system and version: LineageOS 14.1

**Comment by dbrgn** [comment]
Can you upgrade to the latest version and see if you can replicate the issue there?

**Comment by rugk** [comment]
Okay have to say it's Firefox Nightly, so could only be affected by that.

**Comment by dbrgn** [comment]
Also a possibility :slightly_smiling_face: 

I'll close this issue for now unless you can confirm that it also happens with Threema Web 2.1.0.

**Comment by rugk** [comment]
Can just confirm it also happens with FF stable, but I'll have to wait for a real release with ZIP for v2.1.0

**Comment by rugk** [comment]
Could not reproduce, even with the old version. :cry:

**Comment by lgrahl** [comment]
I have seen this bug for **incoming** messages occurring more or less frequently (a few times a week), so could it be that you received a message from that contact a while ago?

**Comment by rugk** [comment]
not during that session, but before…

**Comment by rugk** [comment]
May this bug be re-open? I can constantly see it…

It may be due to the fact that you reply to a message in the notification area on Android. If you then open a Threema Web session, this replied message is shown as  unread.

**Comment by dbrgn** [comment]
Great observation, you're right that the "read" status is not updated when replying via the notification!

This is probably a bug in the Android app.

**Comment by rugk** [comment]
Still an issue… (and I recently just installed some beta update…)  :roll_eyes:

**Comment by dbrgn** [comment]
Thanks for the observation. I will investigate further.

**Comment by ovalseven8** [comment]
Is this fix already in v3.62? I have still this problem.

**Comment by dbrgn** [comment]
It should be. The fix concerned this issue:

> It may be due to the fact that you reply to a message in the notification area on Android. If you then open a Threema Web session, the message you've replied too is shown as unread in Threema Web.

Is that what happens in your case?

If not, does the problem disappear if you switch to another conversation and back?

**Comment by ovalseven8** [comment]
I am not sure if it was #695 again. I just noticed yesterday that Threema Web displayed I have an unread message although I had the conversation open.

**Comment by dbrgn** [comment]
If it happens again, please check the following:

> Does the problem disappear if you switch to another conversation and back, or if you scroll up and back down?

That will give us a clue on whether it's a problem with Threema Web not triggering the read notification, or the app not marking the message as read.

**Comment by ovalseven8** [comment]
As far as I remember, the problem disappeared when I switched to another conversation and back again.

**Comment by rugk** [comment]
> As far as I remember, the problem disappeared when I switched to another conversation and back again

Then it's a different issue (likely https://github.com/threema-ch/threema-web/issues/695, as you've already pointed to).

So I close this as it is said to be fixed…
