### ISSUE TITLE
Cryptic background text

### ISSUE THREAD

**Issue by mariomann** [threema-ch/threema-web#658]
## Expected Behavior
no crypto background

## Current Behavior
I want to open my saved session, but get a view with crypto background

## Your Environment
* Threema Web version: 
* Threema App version: 4.0 (2379)
* Browser name and version: Google Chrome - Version 69.0.3497.100 (Official Build) (64-bit)
* Computer operating system and version: macOS Mojave (10.14)
* Smartphone operating system and version: iOS 12.01

See attached file: <img width="1253" alt="screenshot 2018-10-30 at 10 15 28" src="https://user-images.githubusercontent.com/3458678/47708238-efd2aa80-dc2d-11e8-8823-0f1b3c301e6c.png">

**Comment by dbrgn** [comment]
Woah, that looks weird. Can't really be related to Threema Web though, since we don't use Apache (and there's a "Server: Apache" line in there). Maybe check your extensions?
