### ISSUE TITLE
Random toasts "Threema Web session started"

### ISSUE THREAD

**Issue by lapete** [threema-ch/threema-web#662]
Edit: This is probably an android issue, not an web client issue, I think I missposted it. Should I crosspost to the threema board?

## Expected Behavior
No toasts should pop up outside of Threema.

## Current Behavior
I regularly encounter android toasts with the message "Threema Web session started". I indeed am using the web client, and maybe it does some reconnects in the background, but this should not interfere with my usage outside of Threema.

## Steps to Reproduce (for bugs)
Random, but while using a web session on a computer. See attached screenshot (background is a WhatsApp chat, not Threema)
![screenshot_20181031-161550](https://user-images.githubusercontent.com/25743118/47800426-8b4a4500-dd2c-11e8-9824-4d6d4883e38e.png)

## Your Environment
* Threema Web version: Version 2.1.0 Glärnisch
* Threema App version: 3.54.444 (Threema Shop)
* Browser name and version: Firefox x64 63.0
* Computer operating system and version: Ubuntu 18.04
* Smartphone operating system and version: Android 8.1 with Security patch level October 5th
* Threema Web is set up with a password to reconnect without a new scan every time

**Comment by dbrgn** [comment]
This is by design, it happens when a background reconnect happens because the connection was lost.

The reasoning is that you want to be informed when a connection is started or restarted, so that you could stop or delete it if wasn't intended by you (e.g. you forgot to remove a stored session from a computer that is now used by another person).

**Comment by dbrgn** [comment]
> No toasts should pop up outside of Threema.

Note that toasts are not connected to the app or any Android activity, they are triggered by the background service which does not have a UI.

**Comment by lapete** [comment]
Then for me a notification would be more suitable as toasts can easily be overseen, but if this is by design I guess there are reasons why it's a toast. Thanks for your answer.

**Comment by dbrgn** [comment]
There's an ongoing notification in the notification area, but for reconnects you won't notice it because it doesn't change.

Thanks for your feedback though, we'll reconsider it!
