### ISSUE TITLE
Web client and app lose sync

### ISSUE THREAD

**Issue by shanirub** [threema-ch/threema-web#680]
## Expected Behavior
Threema web client and app should be synchronised.

## Current Behavior
In the past last weeks i'm having trouble using my threema-web.
Shortly after scanning the qr-code and starting a new session, the web client and the android app lose synchronization. New messages can be seen in the app, but do not show in the main conversation window in the web client. Oddly enough, the last message under the contact name (in the contacts panel on the left) continues to be updated.

## Possible Solution
As a workaround i started reloading the browser tab and starting a new session with another qr-code scan. Usually that solves the problem for a while.

## Steps to Reproduce (for bugs)
1. Start a new session in the web client (qr-code scanning).
2. Send and receive messages from a contact.
3. Continue working as usual (running other programs and apps on both the smartphone and the computer).
4. Encounter the bug.
5. Be upset.

## Your Environment
* Threema Web version: 2.1.1
* Threema App version: 3.55.447
* Browser name and version: Firefox 63.0.1 (64-Bit), Mozilla Firefox for fedora 1.0
* Computer operating system and version: Linux Fedora 29, GNOME 3.30.2
* Smartphone operating system and version: Android 6.0.1

**Comment by dbrgn** [comment]
This should be fixed with #715.
