### ISSUE TITLE
GeoIP and Season specific background in TreheWeb

### ISSUE THREAD

**Issue by dwickwire** [threema-ch/threema-web#687]
## Expected Behavior
It'd be nice if the blurred background represents the climate you're in.

## Current Behavior
Currently its just a mountain in the summer of, I guess, Switzerland.  I'm in Mexico and live in the US and often visit my family in Germany.  Would just be a nice touch.

## Possible Solution
Use the freely available geoip to choose from a list of flickr images, they're blurred anyway so it doesn't need to be too specific, as long as the season and IP matches the local mood.

**Comment by lgrahl** [comment]
This is an interesting idea but I'd be against implementing it for privacy reasons:

- We don't have a geo IP library and we don't want to use an external service for it.
- Downloading images from an external service would be a big no-no. The alternative is to ship our own set of images.

In any case I'd say we're diving too far into a feature that is more of an easter egg. We only change the background image to make the user more aware of a major release (comparable to Ubuntu's versioning scheme).

**Comment by dbrgn** [comment]
Even though it's a nice idea, I agree with what @lgrahl said :slightly_smiling_face:

**Comment by rugk** [comment]
But it would really be fun. I mean, you probably only need 4 pictures and a lib for a not so detailed geolocation. 

But yeah, just an easter egg… :smile:
