### ISSUE TITLE
Autocomplete for emoji

### ISSUE THREAD

**Issue by JiiB** [threema-ch/threema-web#696]
It would be very handy to have autocompletion for the emoji shortcuts on the web client, the main feature was implemented here: https://github.com/threema-ch/threema-web/pull/390#issuecomment-349898791

Example of the slack's emoji autocomplete:
![grafik](https://user-images.githubusercontent.com/25438442/50491258-afb35c80-0a11-11e9-926d-bb4bee39877d.png)

**Comment by lgrahl** [comment]
Dupliate of #433. Add your thumbs up there. :slightly_smiling_face:
