### ISSUE TITLE
Stricter CSP rules

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#707]
Evaluate whether stricter CSP rules are possible. (When we launched Threema Web, some of our dependencies did not work without `unsafe-inline` and `unsafe-eval`.)

**Comment by ovalseven8** [comment]
As long as the CSP are not as strict as possible, `X-XSS-Protection` header could help a little bit. Not supported by Firefox though. Nevertheless, cannot hurt.

**Comment by trobert2** [comment]
So is anything being done about this?

**Comment by threema-danilo** [comment]
This won't be fixable with AngularJS 1, and since there [will be no update of this codebase anymore](https://github.com/threema-ch/threema-web/pull/996), this issue can be closed. We already have the strictest CSP rules that work for us.
