### ISSUE TITLE
Material Icons aren't shown in Chrome on Linux

### ISSUE THREAD

**Issue by alexanderadam** [threema-ch/threema-web#714]
I probably should have opened this issue earlier. It bothered me for a long time but I never took the time to create the issue before.
The material icons aren't shown in my Chrome Browser (but they are shown in every other browser on the same machine). The network tab of the browser doesn't show any loading of icons. And it isn't related to any browser extension.

## Expected Behavior
Icons would be shown.

## Current Behavior
It just shows the text in Times New Roman (I looked it up in the `Rendered Fonts` tab of the element) and looks like this:
![screenshot_20190116_083333](https://user-images.githubusercontent.com/372620/51233271-bd516780-1969-11e9-8b84-ec84fbbdea6b.png)
![screenshot_20190116_081716](https://user-images.githubusercontent.com/372620/51233275-c0e4ee80-1969-11e9-9cf9-d617205fe27d.png)
![screenshot_20190116_083625](https://user-images.githubusercontent.com/372620/51233294-d65a1880-1969-11e9-9713-d785e41fad0c.png)

## Possible Solution
I have no solution but I saw similar issues before. Threema Web seems to use [Material Design Lite](https://getmdl.io/) with [Material Design Icons](https://github.com/google/material-design-icons). Material Design Icons seems fairly unmaintained and [has currently 500 open issues](https://github.com/google/material-design-icons/issues). The shown behaviour looks pretty similar to [issue 348](https://github.com/google/material-design-icons/issues/348) and [issue 537](https://github.com/google/material-design-icons/issues/537) but
1. I don't have the font installed locally
2. I'm using Chrome 71.0.3578.98 (Official Build) (64-bit)
3. [the demo pages](https://material.io/tools/icons/?style=baseline) are looking flawless

It seems that similar bugs happened with Material Icons on other platforms too (Edge [1](https://github.com/google/material-design-icons/issues/776) [2](https://github.com/google/material-design-icons/issues/752), [IE Mobile](https://github.com/google/material-design-icons/issues/179), [Vivaldi](https://github.com/google/material-design-lite/issues/1404), [Safari](https://github.com/google/material-design-lite/issues/4382), [old Android](https://github.com/google/material-design-icons/issues/336#issuecomment-436605839))

## Steps to Reproduce (for bugs)

1. I just go on the Threema web page and there it is

## Your Environment
* Threema Web version: Version 2.1.3 Glärnisch
* Browser name and version: Google Chrome 71.0.3578.98 (Official Build) (64-bit)
* Computer operating system and version: Ubuntu 18.04.1

**Comment by alexanderadam** [comment]
Wow, thank you for the fast response.

@lgrahl unfortunately not.

@dbrgn as I wrote earlier there's no extension or blocking involved. Even Incognito Session, a fresh Chrome Profile or even a Guest Session don't make any difference.

There are also no warnings about anything that blocks something. Just regular warnings and debug statements in the console.

![screenshot_20190116_101212](https://user-images.githubusercontent.com/372620/51238502-5935a000-1977-11e9-85db-6ec2c1277157.png)

And there's also no attempt to load a font (I wrote that also before).

> You don't need any local MD fonts to be installed.

I know, but _if_ it would have been installed it might cause issues. See [Material Design Icons issue 348] that I linked earlier for more info on that. This is why I mentioned that this won't be the cause in _my_ case.

**Comment by lgrahl** [comment]
@alexanderadam Can you check which fonts are being loaded in the `Inspector -> Network` tab?

**Comment by alexanderadam** [comment]
As I mentioned in my last two comments there aren't any fonts loaded. I just checked it again and so far nothing changed: still no font queries.

**Comment by lgrahl** [comment]
*Material Icons* may be fairly unmaintained but the CSS loading the fonts is dead simple. Can you ensure `material.css` is being loaded? If so, the browser likely believes that the font exists locally. If it only affects Chrome and none of your other browsers, that may be a bug in Chrome.

Anyhow, I've attached a [simple test](https://github.com/threema-ch/threema-web/files/2763869/test.zip). Just open `test.html` and check if the reply button is being displayed.

**Comment by alexanderadam** [comment]
`material.css` is being loaded:

![screenshot_20190116_124508](https://user-images.githubusercontent.com/372620/51247185-a5d7a600-198c-11e9-8fd6-a2236998e512.png)

And font family is properly set to "Material Icons" but it renders as `Times New Roman`.

![screenshot_20190116_124701](https://user-images.githubusercontent.com/372620/51247298-fbac4e00-198c-11e9-8bbb-9286f52cc103.png)

In your test files the reply button is _not_ displayed.

**Comment by alexanderadam** [comment]
Hm okay. I will close it then…

**Comment by lgrahl** [comment]
I mean we would like to help but I don't see how at this point. :slightly_smiling_face:

**Comment by code-n00b** [comment]
same issue,should i delete my local fonts?

**Comment by code-n00b** [comment]
After i removed my fonts-noto-cjk ,it works

**Comment by dbrgn** [comment]
@code-n00b I also have `noto-fonts-cjk` as well as `noto-fonts-emoji` installed, but don't have any issues with the icons showing... Maybe it was just the font cache that was inconsistent, and removing the font triggered an update. (You can manually refresh the font cache with `fc-cache -fv`.)

@lgrahl I wonder if we should remove the local font reference...

**Comment by alexanderadam** [comment]
> @lgrahl I wonder if we should remove the local font reference...

I agree with that. Referencing local fonts is totally fine for "regular" fonts that won't change a lot.
Most of the icon fonts are constantly extending their coverage though and as long as there's no possibility to have a kind of versioning for fonts this will naturally lead to issues like these.

Even traffic wise the only change will usually be the initial request and, as long as you have a proper hash in the font asset and/or respond with `Not Modified` for non modified resources clients will be able to cache for their own anyway.

There's usually no point in referencing local icon fonts.

**Comment by code-n00b** [comment]
@lgrahl i install the noto-fonts back,it's not working again.
my chinese fonts setting is noto-fonts ,after i change to YaHei or the other fonts ,it's works fine.
@alexanderadam edit your anguage config in  '/etc/fonts/conf.d/' and 'fc-cache -fv',relogin your system.

**Comment by lgrahl** [comment]
> I wonder if we should remove the local font reference...

I guess it makes sense.

**Comment by dbrgn** [comment]
Local font references were removed in #759.

@code-n00b if you want you can check out the current master branch to see if it helps in your case.
