### ISSUE TITLE
Recieving a message while typing in the same chat

### ISSUE THREAD

**Issue by RogoTe** [threema-ch/threema-web#717]
## Expected Behavior
When beeing in a chat and typing and recieving a new message while typing on my side in this chat I want to continue typing my message continuously.

## Current Behavior
While typing a message and recieving a message in the same chat
a) side reloads and some of my key presses get lost and
b) coursor is placed at the beginning of the message field so my key presses after the loss of case a) are placed at the beginning of the message.

## Possible Solution
Sorry, I am not into web applications, maybe isolate the type message field into a separate iframe?

## Your Environment
* Threema Web version: 2.1.4
* Threema App version: 4.0.3
* Browser name and version: Firefox 64.0.2
* Computer operating system and version: Windows 10 Build 17763
* Smartphone operating system and version: iOS 12.1.2

**Comment by joelfischerr** [comment]
This is also happening in Electron/Chromium and Safari 12.0.2. Sending a message and then starting to type the next one also triggers this bug.

It is possible to switch back to an earlier version of Threema Web by using it from https://web.threema.ch/archive/2.1.3/. As there were no security issues in the last version it should be fine.

**Comment by dbrgn** [comment]
I cannot currently reproduce this.

Does the problem occur every time, or only from time to time?

**Comment by joelfischerr** [comment]
I could have sworn it happened every time on my desktop yesterday. But I can't reproduce it consistently on my laptop now.

Steps to reproduce it eventually (around every 10 messages sent):
Send message to ECHOECHO
Start typing the next message immediately
Repeat

I have attached the last lines of the console log after the bug occured. The relevant line might be 

ARIA: Attribute " aria-label ", required for accessibility, is missing on node:
<button class="md-icon-button md-button md-ink-ripple" type="button" ng-transclude="" translate-attr="{'aria-label': $ctrl.getLabel(), 'title': $ctrl.getLabel()}" role="button" tabindex="0" ng-click="$ctrl.action()" aria-pressed="{{ $ctrl.flag }}">
angular.js:15536:16


Full console log:

Initializing (keyStore=yes, peerTrustedKey=yes, resume=true) angular.js:15536:16 
Trying to resume previous session (id=73f02db742b982c688af1918235c45ce, sn-out=60) angular.js:15536:16 
[WebClientService] Starting WebClientService... angular.js:15536:16 
[WebClientService] Creating new startup promise angular.js:15536:16 
[WebClientService] start(): Skipping push notification angular.js:15536:16 
[StateService] Signaling connection state: new => new angular.js:15536:16 
[StateService] Signaling connection state: new => ws-connecting angular.js:15536:16 
[StatusController] State change: error -> warning angular.js:15536:16 
[StateService] Signaling connection state: ws-connecting => server-handshake angular.js:15536:16 
[StateService] Signaling connection state: server-handshake => peer-handshake angular.js:15536:16 
Sending create/textMessage message angular.js:15536:16 
[WebClientService] Currently not connected, queueing chunk angular.js:15536:16 
Sending update/typing message angular.js:15536:16 
[WebClientService] Currently not connected, queueing chunk angular.js:15536:16 
[PushService] Sent push angular.js:15536:16 
[WebClientService] Requested app wakeup via apns push angular.js:15536:16 
Sending update/typing message angular.js:15536:16 
[WebClientService] Currently not connected, queueing chunk angular.js:15536:16 
[StateService] Connection buildup state: push => peer_handshake angular.js:15536:16 
[StatusController] Connection buildup advanced:
Object { state: "peer_handshake", prevState: "push" }
angular.js:15536:16 
[WebClientService] Initializing NotificationService... angular.js:15536:16 
[NotificationService] Notification API available: true angular.js:15536:16 
[NotificationService] Initial notificationPermission true angular.js:15536:16 
[NotificationService] Fetching settings... angular.js:15536:16 
[SettingsService] Retrieving settings key: notifications angular.js:15536:16 
[SettingsService] Retrieving settings key: notificationPreview angular.js:15536:16 
[SettingsService] Retrieving settings key: notificationSound angular.js:15536:16 
[NotificationService] Desktop notifications: true angular.js:15536:16 
[NotificationService] Requesting notification permission... angular.js:15536:16 
[NotificationService] Notification preview: true Using default value (true) angular.js:15536:16 
[SettingsService] Storing settings key: notificationPreview angular.js:15536:16 
[NotificationService] Notification sound: false Using default value (false) angular.js:15536:16 
[SettingsService] Storing settings key: notificationSound angular.js:15536:16 
[WebClientService] Sending connection info (resume=yes, sn-in=153) angular.js:15536:16 
Sending update/connectionInfo message angular.js:15536:16 
[StateService] Signaling connection state: peer-handshake => task angular.js:15536:16 
[StateService] Task connection state: new => connected angular.js:15536:16 
[StatusController] State change: warning -> ok angular.js:15536:16 
[SettingsService] Storing settings key: notifications angular.js:15536:16 
[NotificationService] Notification permission true angular.js:15536:16 
New incoming message (108 bytes) angular.js:15536:16 
Received update/connectionInfo message angular.js:15536:16 
Received connectionInfo from device angular.js:15536:16 
[WebClientService] Received connection info (resume=yes, sn-out=60) angular.js:15536:16 
Pruning cache (local-sn=63, remote-sn=60) angular.js:15536:16 
Chunk cache pruned, acknowledged: 0, left: 3, size: 221 -> 221 angular.js:15536:16 
Chunk cache transferred (1 chunks) angular.js:15536:16 
[WebClientService] Sending cached chunks: 1 angular.js:15536:16 
[WebClientService] Session resumed angular.js:15536:16 
[StateService] Connection buildup state: peer_handshake => done angular.js:15536:16 
[WebClientService] Reset initialization steps angular.js:15536:16 
[StateService] Connection buildup state: done => loading angular.js:15536:16 
Sending update/typing message angular.js:15536:16 
[VersionService] Checking for version update... angular.js:15536:16 
ARIA: Attribute " aria-label ", required for accessibility, is missing on node:
<button class="md-icon-button md-button md-ink-ripple" type="button" ng-transclude="" translate-attr="{'aria-label': $ctrl.getLabel(), 'title': $ctrl.getLabel()}" role="button" tabindex="0" ng-click="$ctrl.action()" aria-pressed="{{ $ctrl.flag }}">
angular.js:15536:16 
New incoming message (68 bytes) angular.js:15536:16 
Received update/batteryStatus message angular.js:15536:16 
Received battery status angular.js:15536:16 
[BatteryStatusService] 55%, discharging angular.js:15536:16 
[WebClientService] requestMessages angular.js:15536:16 
Sending message request for contact ECHOECHO with message id UU0FVbWzyZg= angular.js:15536:16 
Sending request/messages message angular.js:15536:16 
New incoming message (464 bytes) angular.js:15536:16 
Received update/conversation message angular.js:15536:16 
Received conversation update angular.js:15536:16 
New incoming message (347 bytes) angular.js:15536:16 
Received update/messages message angular.js:15536:16 
Received messages update angular.js:15536:16 
New incoming message (117 bytes) angular.js:15536:16 
Received create/textMessage message angular.js:15536:16 
Received create message response angular.js:15536:16 
New incoming message (487 bytes) angular.js:15536:16 
Received update/conversation message angular.js:15536:16 
Received conversation update angular.js:15536:16 
New incoming message (365 bytes) angular.js:15536:16 
Received update/messages message angular.js:15536:16 
Received messages update angular.js:15536:16 
New incoming message (365 bytes) angular.js:15536:16 
Received update/messages message angular.js:15536:16 
Received messages update angular.js:15536:16 
New incoming message (344 bytes) angular.js:15536:16 
Received update/messages message angular.js:15536:16 
Received messages update angular.js:15536:16 
New incoming message (365 bytes) angular.js:15536:16 
Received update/messages message angular.js:15536:16 
Received messages update angular.js:15536:16 
New incoming message (10657 bytes) angular.js:15536:16 
Received response/messages message angular.js:15536:16 
Received messages response angular.js:15536:16 
Sending read request for contact ECHOECHO (msg HUpEUnXSeJI=) angular.js:15536:16 
Sending request/read message angular.js:15536:16 
New incoming message (508 bytes) angular.js:15536:16 
Received update/conversation message angular.js:15536:16 
Received conversation update angular.js:15536:16 
New incoming message (508 bytes) angular.js:15536:16 
Received update/conversation message angular.js:15536:16 
Received conversation update angular.js:15536:16 
New incoming message (391 bytes) angular.js:15536:16 
Received update/messages message angular.js:15536:16 
Received messages update angular.js:15536:16 
New incoming message (53 bytes) angular.js:15536:16 
Received update/confirm message angular.js:15536:16 
Received wire message acknowledgement angular.js:15536:16 
Sending update/typing message angular.js:15536:16 
[VersionService] Checking for version update... angular.js:15536:16 
Sending update/connectionAck message angular.js:15536:16 
Sending update/typing message angular.js:15536:16 
[StateService] Task connection state: connected => reconnecting angular.js:15536:16 
[StatusController] State change: ok -> warning angular.js:15536:16 
[StatusController] Connection lost (iOS). Attempting to reconnect... angular.js:15536:16 
[StatusController] Stopping old connection angular.js:15536:16 
[WebClientService] Stopping (reason=stop, send=true, close=false, connectionBuildupState=push) angular.js:15536:16 
[StateService] Reset states angular.js:15536:16 
[WebClientService] Session remains open angular.js:15536:16 
[WebClientService] Closing signaling angular.js:15536:16 
[WebClientService] Peer connection was null angular.js:15536:16 
[StatusController] State change: warning -> error angular.js:15536:16 
Starting new connection without push angular.js:15536:16 
Initializing (keyStore=yes, peerTrustedKey=yes, resume=true) angular.js:15536:16 
Trying to resume previous session (id=ac6795e802e866ee7e8fc82a212d6b3c, sn-out=8) angular.js:15536:16 
[WebClientService] Starting WebClientService... angular.js:15536:16 
[WebClientService] Creating new startup promise angular.js:15536:16 
[WebClientService] start(): Skipping push notification angular.js:15536:16 
[StateService] Signaling connection state: new => new angular.js:15536:16 
[StateService] Signaling connection state: new => ws-connecting angular.js:15536:16 
[StatusController] State change: error -> warning angular.js:15536:16 
[StateService] Signaling connection state: ws-connecting => server-handshake angular.js:15536:16 
[StateService] Signaling connection state: server-handshake => peer-handshake angular.js:15536:16

**Comment by dbrgn** [comment]
Hm, I sent probably about 50 messages to ECHOECHO and could still not reproduce the issue. But I'm using Android, maybe the problem only occurs with iOS. Could be related to reconnecting behavior, which is much more common with iOS than with Android.

@joelfischerr since you mentioned the archive, does the problem not occur on 2.1.3?

**Comment by joelfischerr** [comment]
I can't recall ever having seen this behavior in earlier versions.

Is there a way to force a reconnect?

**Comment by joelfischerr** [comment]
This might be a more reliable way to reproduce the bug:
Send a long message (one that will be split into multiple parts) to ECHOECHO
Start typing
Force quit the app on the iPhone before the last message comes back from ECHOECHO
The next incoming message shows up at the same time as the bug occurs.

**Comment by dbrgn** [comment]
You can see the connection status from the color of the dot in the "ThreemaWeb." logo. Green means "actively connected" while orange means that the iOS app process was stopped. Orange means that a reconnect will happen as soon as some activity happens on the app or Threema Web side.

**Comment by RogoTe** [comment]
Hi, I did the same test @joelfischerr suggested and found, that the problem only occurs when Threema app on iOS is not in forground. When Threema is in backround or phone is in standby initial stated problem happens.


This is what I got in console:

Sending update/typing message angular.js:15536:16
[WebClientService] Currently not connected, queueing chunk angular.js:15536:16
Sending create/textMessage message angular.js:15536:16
[WebClientService] Currently not connected, queueing chunk angular.js:15536:16
Sending update/typing message angular.js:15536:16
[WebClientService] Currently not connected, queueing chunk angular.js:15536:16
[PushService] Sent push angular.js:15536:16
[WebClientService] Requested app wakeup via apns push angular.js:15536:16
[WebClientService] Called requestRead on a message without id angular.js:15536:16
Sending update/typing message angular.js:15536:16
[WebClientService] Currently not connected, queueing chunk angular.js:15536:16
[StateService] Connection buildup state: push => peer_handshake angular.js:15536:16
[StatusController] Connection buildup advanced: <unavailable> angular.js:15536:16
[WebClientService] Initializing NotificationService... angular.js:15536:16
[NotificationService] Notification API available: true angular.js:15536:16
[NotificationService] Initial notificationPermission true angular.js:15536:16
[NotificationService] Fetching settings... angular.js:15536:16
[SettingsService] Retrieving settings key: notifications angular.js:15536:16
[SettingsService] Retrieving settings key: notificationPreview angular.js:15536:16
[SettingsService] Retrieving settings key: notificationSound angular.js:15536:16
[NotificationService] Desktop notifications: true angular.js:15536:16
[NotificationService] Requesting notification permission... angular.js:15536:16
[NotificationService] Notification preview: true Using default value (true) angular.js:15536:16
[SettingsService] Storing settings key: notificationPreview angular.js:15536:16
[NotificationService] Notification sound: true angular.js:15536:16
[WebClientService] Sending connection info (resume=yes, sn-in=17) angular.js:15536:16
Sending update/connectionInfo message angular.js:15536:16
[StateService] Signaling connection state: peer-handshake => task angular.js:15536:16
[StateService] Task connection state: new => connected angular.js:15536:16
[StatusController] State change: warning -> ok angular.js:15536:16
[SettingsService] Storing settings key: notifications angular.js:15536:16
[NotificationService] Notification permission true angular.js:15536:16
New incoming message (108 bytes) angular.js:15536:16
Received update/connectionInfo message angular.js:15536:16
Received connectionInfo from device angular.js:15536:16
[WebClientService] Received connection info (resume=yes, sn-out=16) angular.js:15536:16
Pruning cache (local-sn=20, remote-sn=16) angular.js:15536:16
Chunk cache pruned, acknowledged: 16, left: 4, size: 1618 -> 129 angular.js:15536:16
Chunk cache transferred (1 chunks) angular.js:15536:16
[WebClientService] Sending cached chunks: 1 angular.js:15536:16
[WebClientService] Session resumed angular.js:15536:16
[StateService] Connection buildup state: peer_handshake => done angular.js:15536:16
[WebClientService] Reset initialization steps angular.js:15536:16
[StateService] Connection buildup state: done => loading angular.js:15536:16
Sending update/typing message angular.js:15536:16
[VersionService] Checking for version update... angular.js:15536:16
ARIA: Attribute " aria-label ", required for accessibility, is missing on node: <unavailable> angular.js:15536:16
[WebClientService] requestMessages angular.js:15536:16
[WebClientService] requestMessages: No more messages available angular.js:15536:16
New incoming message (68 bytes) angular.js:15536:16
Received update/batteryStatus message angular.js:15536:16
Received battery status angular.js:15536:16
[BatteryStatusService] 91%, discharging angular.js:15536:16
Sending update/typing message angular.js:15536:16
[WebClientService] Called requestRead on a message without id angular.js:15536:16
New incoming message (158 bytes) angular.js:15536:16
Received update/conversation message angular.js:15536:16
Received conversation update angular.js:15536:16
New incoming message (336 bytes) angular.js:15536:16
Received update/conversation message angular.js:15536:16
Received conversation update angular.js:15536:16
New incoming message (255 bytes) angular.js:15536:16
Received update/messages message angular.js:15536:16
Received messages update angular.js:15536:16
New incoming message (117 bytes) angular.js:15536:16
Received create/textMessage message angular.js:15536:16
Received create message response angular.js:15536:16
New incoming message (374 bytes) angular.js:15536:16
Received update/receiver message angular.js:15536:16
Received receiver update angular.js:15536:16
New incoming message (359 bytes) angular.js:15536:16
Received update/conversation message angular.js:15536:16
Received conversation update angular.js:15536:16
New incoming message (273 bytes) angular.js:15536:16
Received update/messages message angular.js:15536:16
Received messages update angular.js:15536:16
New incoming message (273 bytes) angular.js:15536:16
Received update/messages message angular.js:15536:16
Received messages update angular.js:15536:16
New incoming message (252 bytes) angular.js:15536:16
Received update/messages message angular.js:15536:16
Received messages update angular.js:15536:16
New incoming message (273 bytes) angular.js:15536:16
Received update/messages message angular.js:15536:16
Received messages update angular.js:15536:16
Sending read request for contact ECHOECHO (msg cpfmDl9LBDo=) angular.js:15536:16
Sending request/read message angular.js:15536:16
New incoming message (53 bytes) angular.js:15536:16
Received update/confirm message angular.js:15536:16
Received wire message acknowledgement angular.js:15536:16
Versuch, eine verbotene Kopfzeile zu verwenden, wurde abgelehnt: Connection 308263936-lcs_client_bin.js:134:386
[VersionService] Checking for version update... angular.js:15536:16
Sending update/connectionAck message angular.js:15536:16
Sending update/typing message angular.js:15536:16
[Exception... "Component returned failure code: 0x805e0006 [nsIChannel.asyncOpen2]"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 104"  data: no]
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://avatars2.githubusercontent.com/favicon.ico blockiert ("default-src").

**Comment by dbrgn** [comment]
I can confirm this behavior with an iOS device. This is most probably related to #728.

**Comment by ovalseven8** [comment]
Is this fixed because #728 is alread closed?

**Comment by dbrgn** [comment]
Good catch, yep, this should be fixed.

(If not, feel free to leave a comment.)
