### ISSUE TITLE
Emoji toolbar hides on reconnect

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#728]
## Steps to Reproduce (for bugs)

1. With an iOS device connected, open the emoji picker
2. Wait until background connection is gone (orange dot in logo)
3. Send a message
4. Emoji toolbar disappears

## Your Environment

* Threema Web version: 2.1.4
* Smartphone operating system and version: iOS

**Comment by dbrgn** [comment]
Further problems: When the contacts tab is focussed, apparently the focus jumps back to the conversations tab.

**Comment by lgrahl** [comment]
Further problems: Messages are not being sent. :sweat_smile:
