### ISSUE TITLE
Threema App shows loading circle although already connected

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#73]
## Current Behavior
When I scan the QR code with my smartphone, you can see the loading circle. Thing is, that the loading circle does not get replaced with the green connected-icon although I am already connected with Threema Web.

*I have to go back in the Threema app and open the Threema Web menu again so that the icon is replaced and I can see further information about the session.*
![screenshot](https://cloud.githubusercontent.com/assets/8258609/23168032/fa3f7a24-f846-11e6-895b-edd9a9ee6662.png)

## Expected Behavior
Threema App should replace the loading circle as soon as the app is connected with Threema Web. It shouldn't be needed to open the same page in the Android app again.

## Your Environment
* Threema Web version: 1.0.1
* Threema for Android version: 3.01
* Threema for Android source: Play Store
* Browser name and version: Firefox 51.0.1
* Operating system and version: Lubuntu 16.04

**Comment by ovalseven8** [comment]
I should probably add that sometimes it works as expected, but just sometimes. No idea why.

**Comment by ovalseven8** [comment]
Issue still occurs also with Threema 3.1.

**Comment by dbrgn** [comment]
@ovalseven8 can you post a screenshot, and make sure that you're on 3.1? The loading layout that can be seen in the original post does not exist anymore in the newest app version.

**Comment by ovalseven8** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8258609/23580597/ff29c276-0104-11e7-98f8-f097ab5a0b7d.png)

**Comment by dbrgn** [comment]
Ah. Yes, although the loading circle should disappear after 30 seconds and be replaced with a warning sign, indicating that the session could not be established. Or is the session actually up and working?

**Comment by ovalseven8** [comment]
Well, I was logged in and could use Threema Web. But the loading circle was not replaced with the Firefox icon. However, this bug only occurs sometimes.

**Comment by dbrgn** [comment]
Interesting. And when going to the main screen and then back to the sessions list, does the session display properly?

**Comment by ovalseven8** [comment]
> And when going to the main screen and then back to the sessions list, does the session display properly?

Yes, the last time I checked it was displayed correctly then.

**Comment by rugk** [comment]
BTW is this still an issue?

**Comment by ovalseven8** [comment]
> BTW is this still an issue?
Yes

**Comment by dbrgn** [comment]
I cannot reproduce this anymore. If it still happens, please comment again. It might be a hard-to-reproduce race condition.
