### ISSUE TITLE
Random disconnections

### ISSUE THREAD

**Issue by phlisg** [threema-ch/threema-web#737]
Hello,

Using persistent sessions, on either FF or Chrome, I get randomly disconnected after a few seconds of usage. I tried deleting and re-enabling a web-session on threema, although it does seem to work better, I still get disconnected.

## Current Behavior

- Following the FAQ, I connect the phone on the same network as the computer
- I launch the web app, connect to my persistent session
- Start using the app normally, but instead, randomly lose sync and wait for a lengthy reconnection (30s to 60s) or a pure disconnection back to the login screen.
- If I refresh the app, I either get stuck at 12% or 60%, with message "Connecting seems to take longer than usual …". After a few tries I get reconnected.
- If automatic reconnection fails: I get back to welcome screen

This happens on either of my phones: an old HTC One M9 on Android 8, and my new Huawei P20 Pro, on android 9.

Threema has "high priority" on my phone so it can work in the background properly.

## Possible Solution

- Deleting old session and renewal allowed me talking to a contact for a longer period than usual, then disconnection issues happened again. Since then, I'm trying to connect back and I am stuck at 12%
- `Delete all persistent sessions on threema seems to work, currently testing. Still works after 5 minutes`
UPDATE: no, after 10 minutes I get the same bug, impossible to reconnect, stuck at 12%

Console.log messages:

```log
 [PeerConnectionHelper] ICE connection state change: disconnected angular.js:15536:16
11:08:34.166 [PeerConnectionHelper] Connection state change: disconnected angular.js:15536:16
11:08:35.158 [StateService] Task connection state: connected => connecting angular.js:15536:16
11:08:36.162 [StatusController] State change: ok -> warning angular.js:15536:16
11:08:55.302 [PeerConnectionHelper] ICE connection state change: failed angular.js:15536:16
11:08:55.313 [PeerConnectionHelper] Connection state change: failed angular.js:15536:16
11:08:55.302 ICE failed, add a STUN server and see about:webrtc for more details
11:08:56.304 [StateService] Task connection state: connecting => disconnected angular.js:15536:16
11:08:57.305 [StatusController] State change: warning -> error angular.js:15536:16
11:08:57.307 [StatusController] Connection lost (Android). Attempting to reconnect... angular.js:15536:16
11:08:57.308 [WebClientService] Stopping (reason=stop, send=true, close=false, connectionBuildupState=n/a) angular.js:15536:16
11:08:57.309 [StateService] Reset states angular.js:15536:16
11:08:57.310 [WebClientService] Session remains open angular.js:15536:16
11:08:57.311 [WebClientService] Closing secure datachannel angular.js:15536:16
11:08:57.313 [WebClientService] Closing signaling angular.js:15536:16
11:08:57.317 [WebClientService] Peer connection closed angular.js:15536:16
11:08:57.318 Initializing (keyStore=yes, peerTrustedKey=yes, resume=true) angular.js:15536:16
11:08:57.321 Trying to resume previous session (id=XXX, sn-out=0) angular.js:15536:16
11:08:57.329 [WebClientService] Starting WebClientService... angular.js:15536:16
11:08:57.330 [WebClientService] Creating new startup promise angular.js:15536:16
11:08:58.332 [StateService] Connection buildup state: new => connecting angular.js:15536:16
11:08:58.333 [StateService] Signaling connection state: new => new angular.js:15536:16
11:08:58.547 [PushService] Sent push angular.js:15536:16
11:08:58.578 [WebClientService] Requested app wakeup via gcm push angular.js:15536:16
11:08:58.579 [StateService] Connection buildup state: connecting => push angular.js:15536:16
11:08:59.423 [StateService] Signaling connection state: new => ws-connecting angular.js:15536:16
11:09:00.434 [StateService] Signaling connection state: ws-connecting => server-handshake angular.js:15536:16
11:09:01.463 [StateService] Signaling connection state: server-handshake => peer-handshake angular.js:15536:16
11:09:01.466 [StatusController] State change: error -> warning angular.js:15536:16
11:09:17.533
[StatusController] Reconnect timeout 1. Retrying...
```

## Steps to Reproduce (for bugs)

1. Create a persistent session, on FF or Chrome
2. Use the webapp normally
3. After a few seconds of use, app gets disconnected
4. App tries to reconnect, no success

## Your Environment

* Threema Web version: 2.1.5
* Threema App version: 3.61 Build 2000465
* Browser name and version: Latest FF or Chrome
* Computer operating system and version: Win10
* Smartphone operating system and version: Android 8.0 & 9

**Comment by dbrgn** [comment]
If you're stuck at 12%, that means that delivery of push notifications is not reliable. Unfortunately this is a known issue for both HTC and especially for Huawei (see https://dontkillmyapp.com/).

Your current phone is a Huawei, right? Please check out [this guide](https://dontkillmyapp.com/huawei) to see if it helps. Unfortunately these extensions by Huawei are non-standard, on top of the regular Android mechanisms, and cause a lot of trouble without a way for the developers to avoid them.

This is probably related to #106 and will get a bit better with #498 (although we can't do much if the push messages can't be delivered). I'll close this issue for now, but feel free to comment with further information, in case something changes. It would be good to know if those steps recommended by dontkillmyapp.com help.

**Comment by phlisg** [comment]
@dbrgn Thank you for your answer :-)

I'm currently applying some recommendations from the guide you suggested me. I'll update this post if it worked!

What I did for the moment was doing a "light approach", instead of modifying all my battery plans:
- Settings / Battery / App launch. 
- Find Threema, click on it, then press "ok" at the next prompt
- Enjoy? :D My messages get instantly sent, even on 4G, sounds promising!

So apparently, even if you set Threema as a "high priority" app, it doesn't care.

Cheers man! Will let you know :)
