### ISSUE TITLE
Determine the maximum message size ourselves

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#741]
We currently determine the (WebRTC) maximum message size as described by the negotiation mechanism in the SaltyRTC WebRTC task. However, this is superfluous and we can just use adapter.js for that purpose which will also be more accurate.

See https://github.com/saltyrtc/saltyrtc-meta/issues/130

**Comment by dbrgn** [comment]
@lgrahl you up for this fix? :slightly_smiling_face:

**Comment by lgrahl** [comment]
Will be fixed on the road to #498.
