### ISSUE TITLE
Some pictures/icon parths are wrong

### ISSUE THREAD

**Issue by scotty86** [threema-ch/threema-web#742]
Hallo,

some pictures are statically referring to the server root path (not the relative path) and can't be loaded, if threema web is hosted in a subdirectory:
![image](https://user-images.githubusercontent.com/1110174/51844181-e8966800-2314-11e9-89ba-fb1756bee11b.png)
![image](https://user-images.githubusercontent.com/1110174/51844601-ec76ba00-2315-11e9-989b-27717cca22e0.png)

For example my Threema Web path is /threema/2.1.5/

Till 2.1.3 everything worked fine. (Didn't test 2.1.4)

Regards
scotty86

**Comment by dbrgn** [comment]
Oops, that has been introduced in #729. Fix incoming.
