### ISSUE TITLE
Too long quoted message destroys layout

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#751]
## Expected Behavior

Try to break as few things as possible…

## Current Behavior

It overflows the input field. After switching the chat back and forth, it now bumped all the chat window content to the top (header is invisible e.g.), but I can at least enter text.

Everything is back/okay after sending that message.

## Steps to Reproduce (for bugs)

1. Send a message with many many lines of text…
2. Quote it.

## Your Environment

* Threema Web version: 2.1.7-gh
* Browser name and version: Firefox 67

**Comment by joelfischerr** [comment]
I think have a quick fix ready at: https://github.com/joelfischerr/threema-web/commit/00499118eb3d352d64addaa41092b19f0104a460.
It doesn't show an ellipsis at the end like the iOS version does, but I don't think showing it is possible without a lot more work. If the Android app shows an ellipsis as well it might be worth it though.
