### ISSUE TITLE
Don't show pin icon if you can't pin conversation

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#752]
## Expected Behavior
The pin icon should only be visible for already existing conversations.

## Current Behavior
Pin icon is displayed even if no conversation exists yet. Clicking on it has no effect.

```
TypeError: "conversation is null"

    modifyConversation https://web.threema.ch/dist/app.js?v=2.1.7:26540 pinConversation https://web.threema.ch/dist/app.js?v=2.1.7:20702 fn2Angular

action https://web.threema.ch/dist/app.js?v=2.1.7:10497 fn7Angular
```

![bildschirmfoto_2019-02-17_10-03-30](https://user-images.githubusercontent.com/8258609/52910743-4971ea00-329c-11e9-885f-7c1ad0d5fc10.png)

## Your Environment
* Threema Web version: 2.1.7
* Threema App version: 3.62
* Browser name and version: Firefox 65.0.1
* Smartphone operating system: Android

**Comment by dbrgn** [comment]
Good catch :slightly_smiling_face:
