### ISSUE TITLE
Threema Web disables after app restart

### ISSUE THREAD

**Issue by Febell** [threema-ch/threema-web#755]
## Expected Behavior
If I close the app the settings for enabling/disabling Threema Web should be memorised.

## Current Behavior
If I close the Threema app and reopen it Threema web is disabled.
(Worked for previus Versions)

## Steps to Reproduce (for bugs)
1. Set Threema web to on
2. Close app
3. Open app
Now Threema web is set to off

## Your Environment
* Threema App version: Version 3.62 Build 472 Threema Shop
* Smartphone operating system and version: Android version 8.0.0 (Samsung)
* App rights: All except "telephone"

**Comment by mimiks** [comment]
Thank you for reporting this issue to us.
This was caused by a race condition in Threema Shop-licensed versions of the app.
A bug fix will be available in the next maintenance release, presumably 3.63.
Sorry for the inconvenience.
