### ISSUE TITLE
Group Chat profile picture in app

### ISSUE THREAD

**Issue by SlicedX** [threema-ch/threema-web#757]
## Expected Behavior
No Showing Profile pictures in group chat as is takes a lot of space and name would be enough
By disabling this picture chats would appear much slimmer 

## Current Behavior
Profile pic in group chat

## Possible Solution
Add a disable option

## Your Environment
Threema App on Android

**Comment by lgrahl** [comment]
In the web client or in the app?

**Comment by SlicedX** [comment]
## Your Environment
Threema App on Android ? 

It is the app

**Comment by dbrgn** [comment]
Please contact the Threema support by sending a message to *SUPPORT or by using the contact form at https://threema.ch/en/support. This issue tracker is only about Threema Web.
