### ISSUE TITLE
Smaler text in app

### ISSUE THREAD

**Issue by SlicedX** [threema-ch/threema-web#758]
## Expected Behavior
Smaler text as regular is still to big 

## Your Environment
Threema App on Android

**Comment by lgrahl** [comment]
In the web client or in the app?

**Comment by SlicedX** [comment]
## Your Environment
Threema App on Android

Yep the app on android

**Comment by dbrgn** [comment]
Please contact the Threema support by sending a message to *SUPPORT or by using the contact form at https://threema.ch/en/support. This issue tracker is only about Threema Web.
