### ISSUE TITLE
Threema Web and Android VPN - Internet Not Available

### ISSUE THREAD

**Issue by msh317** [threema-ch/threema-web#774]
## Steps to Reproduce (for bugs)

1. Mobile App reflects no Internet when attempting to scan and connect to the Threema Web
2. A Network review indicates that the Mobile App is attempting to connect to the Web app via the Local Network i.e. Broadcast
3. Google Fi uses a secure VPN when connecting to Broadband and the Internet
4. It appears that there is no other method of allowing the two applications to communicate without removing the VPN.

## Your Environment

* Threema Web version: 2.1.7
* Threema App version: 3.6.3
* Browser name and version: Chrome 72.0.3626.121 (64Bit)
* Computer operating system and version: Windows 10 Pro version 1803 OS Build 17134.590
* Smartphone operating system and version: Android 9
Carrier - Google Fi - Pixel 2

**Comment by msh317** [comment]
Note: removing the VPN allows the two applications to communicate normally.

**Comment by lgrahl** [comment]
Did you close this by accident? Anyhow, this is a matter for the support which you can contact by sending a Threema message to `*SUPPORT`.

**Comment by msh317** [comment]
I was able to determine the issue and found it to be Google's VPN - I have now resolved it and Google has released a fix.   Thank you
