### ISSUE TITLE
Remove licenses for dev only npm modules?

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#779]
I noticed you include licenses for dev-only tools such as babel: (as a transpiler, it likely does not bundle any code in the resulting product). So you may not actually need to include them...

https://github.com/threema-ch/threema-web/blob/6b229405d73284f3ec1a19127507ed43e2a839f1/gather-licenses.sh#L19

---

Altghough I noticed you do not list it as a `devDependencies` in your package.json. So I am a little confused here. 😄

**Comment by dbrgn** [comment]
I'm not 100% sure. When Babel transforms the source JS into the target version, it sometimes adds polyfills and wrapper types to the generated code.

Adding all tools we use to the 3rd party licenses definitely doesn't hurt, and this way we're on the safe side. (We're already excluding transitive dependencies in the list.)
