### ISSUE TITLE
Update Autolinker.js

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#807]
See discussion at https://threema-forum.de/thread-4682-post-45770.html#pid45770.

Update autolinker and add a few test cases with expected URL processing.

**Comment by ovalseven8** [comment]
New URL: https://threema-forum.de/index.php?thread/4682-threema-web-und-app-haben-probleme-mit-klammern-nach-urls-mit-query-string/&postID=45770#post45770
