### ISSUE TITLE
TypeError: this.getPeer(...) is null

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#809]
Using `Version 2.2.0-beta.1 Glärnisch` I encountered the following error while reconnecting. I guess it's related to #802, but I just want to let you know.

## Current Behavior
![Bildschirmfoto vom 2019-05-24 11-38-17](https://user-images.githubusercontent.com/8258609/58318679-8fe56080-7e18-11e9-9ffa-f70df064be26.png)

**Comment by lgrahl** [comment]
Probably https://github.com/saltyrtc/saltyrtc-client-js/issues/114. We'll deploy that on beta in a couple of weeks (see the checkbox) and then feel free to reopen if it happens again.
