### ISSUE TITLE
TypeErrors: Undefined on reload

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#810]
Got same strange errors using `Version 2.2.0-beta.1 Glärnisch`:

![Bildschirmfoto vom 2019-05-24 11-45-53](https://user-images.githubusercontent.com/8258609/58319131-8d373b00-7e19-11e9-85f0-7d50c9c6cfea.png)

**Comment by lgrahl** [comment]
Firefox? Did this happen after a reload?

**Comment by ovalseven8** [comment]
Yep, Firefox. Honestly, I don't remember if I reloaded the page.

**Comment by lgrahl** [comment]
For some reason, events leak into the reloaded page which triggers this behaviour. We have yet to find out why it happens but it does not have an impact on the web client. So, *wontfix* for now, at least until it triggers bugs.
