### ISSUE TITLE
Make emoji picker more accessible

### ISSUE THREAD

**Issue by MarcoZehe** [threema-ch/threema-web#811]
## Steps to Reproduce (for bugs)

1. With a scren reader like VoiceOver on mac or NVDA on Windows (with Chrome or Firefox), open any chat and focus the input area.
2. Shift+Tab once to get to the emoji button. Note that it is spoken, but not indicating whether the emoji panel is currently showing or not.
3. Press Space to show it if it isn't showing already, which by default, it is not.
4. Tab forward to the emoji picker. Notice that you can tab among the different sections, but the screen reader only says "button button button". The emojis themselves canot be focused.

## Current Behavior

1. The emoji picker should indicate whether it is currently showing the emoji picker or not. This can be easily done by adding aria-pressed="true" or "false" depending on whether it is currently pressed (showing) or not.
2. The buttons aren't labeled, and the emojis themselves aren't keyboard focusable, and even for a screen reader exploring them, they only appear as a string of text rather than individual buttons I could click on.

## Expected Behavior

1. The Emoji button indicates its pressed state.
2. The buttons are labeled and the individual emojis somehow focusable and selectable, in addition to being semantically exposed.

## Possible Solution

1. As indicated above, turn the Emoji button into a real toggle button by adding aria-pressed="true"/"false", depending on its state.
2. Label the buttons for the sections, and turn the individual emojis into actionable items, like buttons or selectable options in a list (role listbox for the container, role option for the individual items), and make them keyboard ocusable, Enter to insert.

## Your Environment

* Threema Web version: 2.0-Beta1
* Threema App version: 3.6
* Browser name and version: Chrome 74. Firefox 67.
* Computer operating system and version: Windows 10 19H1 update (18362,116)
* Smartphone operating system and version: Android Pie.

**Comment by lgrahl** [comment]
Thanks for making us aware of it. :+1: Is this an issue that appeared with the current beta or did it occur previously as well?

**Comment by MarcoZehe** [comment]
@lgrahl It may actually already be in 2.1.7, if that portion didn't change with the new Compose area. I normally don't use that emoji panel, on Windows, I press WindowsKey+Period instead, since that emoji picker is very accessible. But I tried it with the new Compose area to see if the inserting of emojis works in principle, and found that the panel doesn't talk nicely with screen readers yet.
