### ISSUE TITLE
Support for Fenced Code Blocks formatting

### ISSUE THREAD

**Issue by apiraino** [threema-ch/threema-web#819]
## Summary

I'm getting more and more used to being able to write `this` (text between backticks) and this:

    ```
     fn main() {
         println!("Hello, world!");
     }
    ```

and have it rendered as:
```
fn main() {
    println!("Hello, world!");
}
```

I wonder how many would find it useful in threema, too :-)

## Detailed Description

Currently the main issue is when I want to send snippets of code or any literal text, the unformatted rendering make it useless.
Basically this means supporting the `backtick` and Fenced Code Blocks (according to [GFM jargon](https://github.com/emn178/markdown#Fenced-Code-Blocks))

**Comment by dbrgn** [comment]
I would personally also like to see a code formatting feature, but it would need to be supported across all apps too.

I will file an internal issue for this feature request.

**Comment by tarfeef101** [comment]
@dbrgn any update on this? code formatting is smth I use daily (yes, even for non-professional use), so I care deeply about it :)

I am not much of an appdev, but if your former statement about full compatibilty could be violated (e.g. would show up correctly on web but just backticks on mobile), then I could try my hand at minimally "seeing if I can figure this problem out"

**Comment by dbrgn** [comment]
It still is on our TODO list 🙂 No concrete date yet, but we discussed the topic quite recently.

Compatibility across all products is definitely an essential aspect though.

**Comment by tarfeef101** [comment]
> It still is on our TODO list 🙂 No concrete date yet, but we discussed the topic quite recently.
> 
> Compatibility across all products is definitely an essential aspect though.

Thanks! Guess I'll "leave it to the pros", then. Tackling anything frontend related is daunting enough for me already, I'm not foolish enough to try and deal with mobile dev as well 😅
