### ISSUE TITLE
Support pasting image data

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#82]
## Expected Behavior

When copying image or gif data through the clipboard and pasting it into the compose area, the image should be sent.

This will *revolutionize* sending of animgifs!

## Current Behavior

Nothing happens.

## Possible Solution

https://stackoverflow.com/questions/490908/paste-an-image-from-clipboard-using-javascript

**Comment by simmac** [comment]
AFAIK WhatsApp Web does this, could be very handy, especially for sending screenshots directly from the clipboard.

**Comment by wschlich** [comment]
Yes, please! Even WhatsApp Web fails on sending animgifs this way, so Threema Web would be on pole position xD
