### ISSUE TITLE
Sending image as file will create empty image view on Android

### ISSUE THREAD

**Issue by joelfischerr** [threema-ch/threema-web#828]
## Bug Description

I"m trying to send an image as a file from an iOS device connected to the web client to an Android device. The Android device shows an empty image view message box.

## Steps to Reproduce (for bugs)

1. Send image as file from the web client
2. Open the conversation on the Android device, it'll show an empty image view message box

## Potential Solution

I don't even know where the issue lies.

## Your Environment

Happens with other Android devices as well and there is at least one internal ticket asking about this.

* Threema Web version: 2.1.7 and 2.2.0-beta.2
* Threema App version: iOS 4.3, Android 3.7
* Browser name and version: Firefox 67.0.4
* Computer operating system and version: macOS 10.14.5 (18F132)
* Smartphone operating system and version: iOS 12.3.1, Android 8.1.0

**Comment by lgrahl** [comment]
Fairly sure this is #485. Please reopen if not.
