### ISSUE TITLE
Can't connect in Firefox Nightly 69 / Windows 10

### ISSUE THREAD

**Issue by caugner** [threema-ch/threema-web#833]
## Bug Description

For a week or two, I am unable to connect in Firefox Nightly under Windows 10.

## Steps to Reproduce (for bugs)

1. Open web.threema.ch.
2. Scan QR code.
3. Progress increases until 60 %, then it shows an error message.

## Potential Solution

Worked in Chrome on the same workstation.

## Your Environment

* Threema Web version: 2.1.7
* Threema App version: 3.7 Build 20000482 Google Play
* Browser name and version: Firefox Nightly 69.0a1
* Computer operating system and version: Firefox Nightly 69.0a1 (2019-07-03) (64-Bit)
* Smartphone operating system and version: Android 9 (LineageOS 190605.003)

Firefox console had the following error message:
![grafik](https://user-images.githubusercontent.com/495429/60615391-4bfa5980-9dcf-11e9-981b-47b8b647aeb0.png)

PS: I tried both normal and private mode, with and without add-ons (a.k.a. safe mode).

**Comment by rugk** [comment]
I have the same problem with Nightly, on Linux with the Threema Beta app.

**Comment by lgrahl** [comment]
Thanks for reporting this. There have been some bugs related to recent changes in data channel code and I'm looking into it. I should use Nightly more often (and review data channel patches :woman_shrugging:).

The error in the console is definitely a false positive though.

**Comment by lgrahl** [comment]
Verified that this is [bug 1562341](https://bugzilla.mozilla.org/show_bug.cgi?id=1562341) and the currently proposed patch works. Wait until that has been merged and reopen if it is still an issue afterwards.

**Comment by caugner** [comment]
Thank you @lgrahl, the proposed patch has been merged and Threema Web works again in FF Nightly now. :-)

**Comment by rugk** [comment]
There seem to be problems again. Stuck at 60% in Nightly with Web-Beta.
```
14:50:23.585 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 web-beta.threema.ch:1:1
14:50:25.643 Bundle loaded, bootstrapping application. bootstrap.ts:3:12
14:50:26.259            [Welcome-C] Initialize session by scanning QR code... logger.ts:60:20
14:50:26.260          [WebClient-S] Stopping (reason=stop, send=false, close=welcome, connectionBuildupState=new) logger.ts:60:20
14:50:26.268          [WebClient-S] Initializing (keyStore=no, peerTrustedKey=no, resume=false) logger.ts:60:20
14:50:26.374 ARIA: Attribute " aria-label ", required for accessibility, is missing on node: 
<input id="input_0" class="ng-pristine ng-untouched…valid md-input ng-empty" type="password" ng-model="ctrl.password" aria-labelledby="aria-label-password-create" translate-attr="{'placeholder': 'welcome…l': 'welcome.PASSWORD'}" autocomplete="new-password" aria-invalid="false" placeholder="Passwort" aria-label="Passwort">
angular.js:15567:41
14:50:26.543            [Version-S] Using Threema Web version 2.2.0-beta.3 logger.ts:60:20
14:50:33.100       [PeerConnection] Initialize WebRTC PeerConnection logger.ts:60:20
14:50:33.102 Using more than two STUN/TURN servers slows down discovery 2.5d6dc97302b27534f255.bundle.js:1
```

![image](https://user-images.githubusercontent.com/11966684/61578958-a3523680-aafe-11e9-8187-9e82413d5321.png)

70.0a1 (2019-07-19) (64-bit)
Fedora 30


### troubleshooting page

shows https://web-beta.threema.ch/troubleshoot/

![image](https://user-images.githubusercontent.com/11966684/61578974-ff1cbf80-aafe-11e9-962b-6f9d1119db92.png)


![image](https://user-images.githubusercontent.com/11966684/61578969-e6aca500-aafe-11e9-924c-01569bef5ceb.png)

**Comment by lgrahl** [comment]
Did a Nightly version in between the first encounter and this encounter work?

**Comment by rugk** [comment]
> Did a Nightly version in between the first encounter and this encounter work?

Yes. Tried again with 70.0a1 (2019-07-20) (64-bit) and it still did not work.

**Comment by lgrahl** [comment]
Tried today's nightly instead of building myself. Works fine.
