### ISSUE TITLE
Enforce CT policy

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#843]
Add `enforce` to your `Expect-CT` header.

> `enforce` (Optional)
> 
> Signals to the user agent that compliance with the Certificate Transparency policy should be enforced (rather than only reporting compliance) and that the user agent should refuse future connections that violate its Certificate Transparency policy.
> 
> When both the enforce directive and the report-uri directive are present, the configuration is referred to as an "enforce-and-report" configuration, signalling to the user agent both that compliance to the Certificate Transparency policy should be enforced and that violations should be reported
> 

https://docs.w3cub.com/http/headers/expect-ct/

**Comment by dbrgn** [comment]
Deployed with `enforce` and a short max-age value. The max-age value will be increased the next time we'll deploy.
