### ISSUE TITLE
Connection lost without reconnection attempt

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#844]
In the current beta:

![image](https://user-images.githubusercontent.com/105168/60877936-0dd1bf80-a23f-11e9-87ca-df67fa2d9175.png)

![img](https://tmp.dbrgn.ch/screenshots/20190709114539-x3m_irb8.png)

That was 10 minutes ago. @lgrahl any idea why the push wasn't triggered?

**Comment by dbrgn** [comment]
This is on Chromium Snapshot (Version 77.0.3844.0), I think that's relevant. Doesn't seem to happen in Firefox.

Maybe they also messed up something with the state machines?

**Comment by lgrahl** [comment]
I'd need to see the full log to evaluate that since most state handling depends on what kind of states we went through previously. I'll try using Chromium Snapshot for a while.

**Comment by dbrgn** [comment]
@lgrahl closed on purpose?

**Comment by lgrahl** [comment]
Yup. But I was just able to reproduce it.

**Comment by lgrahl** [comment]
The issue is that the `iceConnectionState` remains in `disconnected`. We currently rely on it moving into `failed` eventually.

> In Unified Plan, we don't support end-of-candidates, and have chosen to stay in "disconnected".

https://bugs.chromium.org/p/chromium/issues/detail?id=982793
