### ISSUE TITLE
Threema Web is incompatible with new archiving feature

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#847]
## Bug Description

Threema Web is incompatible with the new archiving feature in Android 4.0 for Android.

## Steps to Reproduce (for bugs)

1. Start Threema Web session
Contact list:
![Screenshot_2019-07-09 Threema Web](https://user-images.githubusercontent.com/8258609/60912141-ffa69200-a284-11e9-8cb7-a9ed3bf28f60.png)
2. Start a new chat with `ECHOECHO`
Contact list:
![Screenshot_2019-07-09 Threema Web(1)](https://user-images.githubusercontent.com/8258609/60912157-092ffa00-a285-11e9-9407-18126a7f0192.png)
3. Archive the chat with `ECHOECHO` using the new archiving feature in Threema 4.0. Now, the chat with `ECHOECHO` is gone in Threema Web:
![Screenshot_2019-07-09 Threema Web(2)](https://user-images.githubusercontent.com/8258609/60912189-1e0c8d80-a285-11e9-94f5-35f0ff61d112.png)
4. Now, de-archive the chat with `ECHOECHO` using the app. **The chat is now displayed twice in Threema Web:**
![Screenshot_2019-07-09 Threema Web(3)](https://user-images.githubusercontent.com/8258609/60912266-485e4b00-a285-11e9-923d-73f21826d867.png)

## Your Environment

* Threema Web version: Version 2.2.0-beta.3 Glärnisch
* Threema App version: 4.0-beta2
* Browser name and version: Firefox 67.0.4
* Smartphone operating system and version: Android 6

**Comment by dbrgn** [comment]
You're right, this is a bug in the Android app. It's easy to miss if you have a lot of conversations :slightly_smiling_face: 

Additionally, we should log an error if a conversation for the same receiver is created twice.

**Comment by dbrgn** [comment]
Will be fixed with the next Android app release.
