### ISSUE TITLE
"Avatar icon" barely visible in profile page view

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#851]
## Bug Description

In the chat list the "avatar icon" is shown:
![Screenshot_2019-07-10 Threema Web(1)](https://user-images.githubusercontent.com/8258609/60945428-d10fd200-a2eb-11e9-81d0-7e976f2d338b.png)

In the profile page the "avatar icon" is barely visible, only the background color:
![Screenshot_2019-07-10 Threema Web(2)](https://user-images.githubusercontent.com/8258609/60945434-d4a35900-a2eb-11e9-92eb-d9a5ecf63bc3.png)

## Your Environment

* Threema Web version: Version 2.2.0-beta.3 Glärnisch
* Threema App version: 4.0-beta2 (Android)
* Browser name and version: Firefox 67.0.4

**Comment by lgrahl** [comment]
Related to transparent avatars.

**Comment by dbrgn** [comment]
Should be easy to fix by setting the background color to white.

**Comment by lgrahl** [comment]
Would be cleaner to set no background color.

**Comment by lgrahl** [comment]
There is some weird stuff going on in the avatar directive.
