### ISSUE TITLE
Add contact: When entering an invalid Threema-ID, promise is not resolved

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#852]
## Steps to Reproduce (for bugs)

1. Add a contact through Threema Web
2. Enter an invalid ID (e.g. ASDFASDF)
3. Confirm error message
4. Promise is not resolved, back button does not work

![img](https://tmp.dbrgn.ch/screenshots/20190712111621-vtoqaajr.png)

**Comment by ovalseven8** [comment]
#820 probably related?

**Comment by dbrgn** [comment]
Ah, yes, duplicate :slightly_smiling_face:
