### ISSUE TITLE
Add support for "archive chats"

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#857]
## Summary

Threema v4 for Android introduced the "archive chats" feature.

However, before this is added to Threema Web it makes sense to fix #847 first.

**Comment by dbrgn** [comment]
Right now the chat archival is an Android-only UI feature. If the function is well-received and we decide to implement it on iOS too, it might also make sense to add it to Threema Web. However, for now that has low priority.

I'm closing this feature request for now. We can re-open it in case we're rolling out chat archiving to all platforms. Of course, this would require a protocol update.

(Of course, #847 is a bug and should be fixed!)
