### ISSUE TITLE
When image description input is modified externally (by browser extension) change is discarded

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#860]
## Bug Description

When a browser extension e.g. adds a character to the end of the input field of the description input for image files it is discarded.

## Steps to Reproduce (for bugs)

1. Install [my Awesome Emoji Picker](https://addons.mozilla.org/firefox/addon/awesome-emoji-picker/?src=external-github-issue) for Firefox. ([source code here](https://github.com/rugk/awesome-emoji-picker))
2. Send an image.
3. Enter a description.
4. Use the add-on to add an emoji at the end of the text.

**What happens** text is sent without emoji
**What should happen:** send text with emoji, just as it is displayed to the user

**Workaround:** When you trigger a change of the input field (e.g. add a character at the end and remove it again), it will send it correctly. Thus, some things seem to be improperly cached/triggered.

**Screencast** showing the problem:
![threema-web-emoji-bug](https://user-images.githubusercontent.com/11966684/62158060-e8504700-b30e-11e9-862b-44e11e5d3524.gif)

**Reasoning:** The add-on is especially useful there, as you currently have no (way to input) emoji(s) (picker) there. :smile: 

## Potential Solution

Likely something is only cached/reloaded/… when an input event occurs or so?

The injection code that is used by the add-on can be found at:
https://github.com/rugk/awesome-emoji-picker/blob/c92bfa21fc4da40d93a6e212f5ec8b9ef0ba9413/src/content_scripts/insertIntoPage.js

## Your Environment

* Threema Web version: 2.2.0-beta.3
* Threema App version: Android
* Browser name and version: Firefox 68
* Computer operating system and version: Linux/Fedora 30
* Smartphone operating system and version: LineageOS 14.1

**Comment by dbrgn** [comment]
We're using the standard angularjs "ng-model" approach, where an input field is bound to a variable in the dialog controller. Manually pasting emoji into the caption description works. If your extension modifies the content, then you probably need to manually fire some kind of change event, otherwise other systems will have problems too.

**Comment by dbrgn** [comment]
You can try to reproduce it here: https://plnkr.co/edit/cu4Vn3FnfplkMvyW78Je?p=preview

**Comment by rugk** [comment]
Though I have to say the same works for the usual input field.
Anyway, thanks for the detailed answer and the paste, I'll look into it.
