### ISSUE TITLE
Feature: allow quick connect and disconnect

### ISSUE THREAD

**Issue by nurps** [threema-ch/threema-web#87]
Since ThreemaWeb is keeping the phone awake the whole time its connected it would be great to have the "close session" button available directly and not in a submenu. And the option for trusted connections where you could just connect with one button without the need of entering a password.

This way it would be possible to just quickly establish the connection if I got a message or want to write one. And since this is going to happen quite often in would be very convenient to have "connect/disconnect" just one single click away.

**Comment by dbrgn** [comment]
> And the option for trusted connections where you could just connect with one button without the need of entering a password.

That would mean that the keys necessary to wake up your phone (if the webclient is enabled), to connect to it and to download all past conversations would be in your local browser storage unencrypted. It would make it easy for an attacker to steal the keys in case of a browser vulnerability or a XSS vulnerability in Threema Web is discovered.

The better alternative is probably to store the session password in your browser - or better in a password manager - with auto-fill enabled. Then you don't have to type it in manually either.

**Comment by lgrahl** [comment]
Would that be necessary? You could decrypt local storage once and store the keys until the tab has been closed.

**Comment by dbrgn** [comment]
Most people's expectations are probably that a session closed through "close session" can't be restored through a single click. That's why currently we clear the cached keys when closing the session via that button.

Many people don't know about the F5 key.

**Comment by thigg** [comment]
Maybe there could be a non default option then to allow disconnects during the tab is open. This would maybe allow to wake up the connection every 30 secs and put the phone in sleep mode in between?

**Comment by dbrgn** [comment]
> This would maybe allow to wake up the connection every 30 secs and put the phone in sleep mode in between?

That would require more battery than keeping the connection open, since the connection buildup requires multiple round trips. Also, Google push notifications to wake up the phone are not *that* reliable.
