### ISSUE TITLE
Changing the conversation requests further messages

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#870]
## Bug Description

When changing the conversation in the UI to another and then back again, further messages are being requested, as if one would scroll up to request further messages manually.

## Steps to Reproduce (for bugs)

1. Open a conversation (A).
2. Switch to another (B).
3. Switch back to conversation (A).
4. Look at the log.

* Threema Web version: 2.2.0-beta.4

**Comment by dbrgn** [comment]
For the record: This behavior does not happen with https://web-beta.threema.ch/archive/2.2.0-beta.3/. Changing chats is much smoother there.

**Comment by lgrahl** [comment]
Can't confirm that. But between beta 2 and 3 something changed regarding the *load more messages* behaviour. Beta 2 does not load more messages when switching conversations. Beta 3 does.

**Comment by lgrahl** [comment]
Let's treat this issue and the lagging one separately.

I've revert 898e71692234e081f0818dce456e0889272b6327 locally and that fixes the loading of further messages. Looks like one of the dependencies is the issue.

**Comment by lgrahl** [comment]
Regarding the lagging: I did a profile between beta.4 (with 898e716 reverted) and did not see any notable difference. Thus, cannot confirm.

**Comment by dbrgn** [comment]
:woman_facepalming: history keeps repeating itself.

https://github.com/threema-ch/threema-web/pull/723

Sorry about that. Unfortunately it's not possible to add comments to a JSON file (package.json), but I'll pin the version to an exact version number, then it should be obvious that there's a reason for that.
