### ISSUE TITLE
Time zone incorrect

### ISSUE THREAD

**Issue by florian2833z** [threema-ch/threema-web#895]
## Bug Description

Threema web does not show local time, leading to confusion. I have to add 2 hours to every time stamp to know the real time the message was sent/received.

## Potential Solution

Use the phone's time zone

## Environment

* Threema Web version: 2.2.1

**Comment by dbrgn** [comment]
Threema Web uses Unix time stamps for everything and converts them to local time in the browser. Is the time zone on your computer set correctly?

**Comment by florian2833z** [comment]
Seems like firefox hides the time zone as a measure of privacy protection, issue resolved.

**Comment by rugk** [comment]
Did you change any `about:config` setting? E.g. `resistFingerprinting`? This could cause this…

**Comment by florian2833z** [comment]
Yes
