### ISSUE TITLE
When sending a message, receive "Warning: Received message update for unknown message"

### ISSUE THREAD

**Issue by MarcoZehe** [threema-ch/threema-web#897]
## Bug Description

When sending messages from Threema Web, I often get the above error after the message has been sent. This is observed in both group chats and one-on-one chats. It only started happening after I switched back to iOS from Android. The message is sent and delivered, but Threema Web gets these weird error messages.

## Steps to Reproduce (for bugs)

1. Connect to iOS Threma.
2. In a group or single chat, write some messages. Doesn't always happen, is intermittent.

## Potential Solution

No workaround available, this seems to be a ,iscommunication between Threema and Threema Web.

## Your Environment

* Threema Web version: 2.2.1
* Threema App version: 4.3.2
* Browser name and version: Firefox 69
* Computer operating system and version: Windows 10 19H1
* Smartphone operating system and version: iOS 12.4.1

**Comment by lgrahl** [comment]
The iOS web client code is currently being refactored to resolve this issue. The debug message you're getting should only appear in debug or beta versions. The discussion related to this is in #753.
