### ISSUE TITLE
Click on conversation did not work

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#898]
## Bug Description

Today, I opened Threema Web and wanted to click on a conversation. However, it did not load/display it, I had to click multiply times until it was shown.

Also, I got this error message in the logs:

![Bildschirmfoto vom 2019-09-03 13-48-53](https://user-images.githubusercontent.com/8258609/64171004-d142ce80-ce51-11e9-8a85-725f4b31a717.png)

## Your Environment

* Threema Web version: 2.2.1
* Threema App version: 4.11
* Browser name and version: Firefox 68.0.2

**Comment by lgrahl** [comment]
Any way to reproduce?

**Comment by ovalseven8** [comment]
Unfortunately, I could not find a way so far. :/

**Comment by lgrahl** [comment]
Feel free to reopen if it happens again. Since it's a mere annoyance, we're not going to chase after it. :slightly_smiling_face:

**Comment by ovalseven8** [comment]
Recently, this happened again. But I've still no idea why and cannot reproduce it.
