### ISSUE TITLE
Handle more / unknown MIME-Types

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#90]
## Expected Behavior

- [ ] Text files should have a corresponding icon after download.

- [ ] Unknown files should display a "fallback icon".

Some filetypes should have better labels:

- [ ] .ics (#202)

Sending files should set the correct mime types:

- [ ] .apk (#59)

## Current Behavior

![file](https://cloud.githubusercontent.com/assets/105168/23274564/8087060c-fa03-11e6-8091-c11387862a62.png)

**Comment by simmac** [comment]
See also #59
