### ISSUE TITLE
Add white backdrop to avatar images

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#901]
Default avatars now have an alpha channel on Android. We should add a white backdrop to the image.

**Comment by dbrgn** [comment]
Note: We can't just add white background color, since that would fill out the entire DOM box (making it a white rectangle). We need to keep them transparent outside the circle. Maybe an image with a white circle and transparent background could be used. Or maybe there's some CSS3 trick.

**Comment by lgrahl** [comment]
You're thinking too complicated. Obviously, the background color of an element with a border radius obeys the radius. Try it for yourselves on `.avatar.avatar-low > img`.

**Comment by dbrgn** [comment]
Oh wow :joy:
