### ISSUE TITLE
Group name/membership doesn't refresh after external backup

### ISSUE THREAD

**Issue by Spiegel-Leser** [threema-ch/threema-web#902]
## Bug Description

If the phone is reset to a total backup (externally in recovery), all group members and group names are reset and stay that way. While this is to be expected with groups I set up myself, it's not expected with groups other people set up. Also, I don't know how to easily refresh.

## Potential Solution

I expect, all group originators can remove me from their list (if so) and enter me again to refresh my membership, and all group originators can rename the group twice (dummy, correct name) to refresh the group name.

Does the same problem happen with applying a Threema Backup? Likely not, so the steps done there should also be available for an external backup, i.e. in a manual "refresh groups" setting.

**Comment by lgrahl** [comment]
Hi. This issue tracker is for Threema Web. For the Threema App, please contact `*SUPPORT` or go to https://threema.ch/en/support.

**Comment by ovalseven8** [comment]
@Spiegel-Leser: The group admins have to "synchronize" their groups.
