### ISSUE TITLE
Make Threema Web work on Safari for the Android app

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#913]
## Summary

When you use the iOS app you can use Threema Web on Safari. However, when you use the Android app you can't. IMHO that's unintuitive.

**Comment by lgrahl** [comment]
There's a reason: [Buggy WebRTC data channel implementation](https://bugs.webkit.org/show_bug.cgi?id=184688).

**Comment by ovalseven8** [comment]
> There's a reason: [Buggy WebRTC data channel implementation](https://bugs.webkit.org/show_bug.cgi?id=184688).

Thanks for the link. While Apple should definitely fix that, you could use relaying (what you currently do for iOS), or do I miss something?

**Comment by lgrahl** [comment]
We can't do it at the moment without protocol work but could perhaps in the future.

**Comment by ovalseven8** [comment]
> We can't do it at the moment without protocol work but could perhaps in the future.

I guess a `saltyrtc-task-relayed-data-java` implementation would be necessary? Still, I think it would be a good idea to support Safari for Android apps.

**Comment by lgrahl** [comment]
We have #498 for tracking that.

**Comment by ovalseven8** [comment]
> We have #498 for tracking that.

Is #498 about replacing WebRTC data channels with WebSockets internally?

**Comment by dbrgn** [comment]
We had ideas about a hybrid approach. But we can't say much about future developments right now.
