### ISSUE TITLE
Threema Web disconnects on Firefox, but not Chromium

### ISSUE THREAD

**Issue by saveriomiroddi** [threema-ch/threema-web#914]
## Bug Description

On Firefox, Threema Web disconnects shortly after I connect. Generally I'm able to send a single message, but after, it loses the connection.
Originally I thought it was a network problem, but it turns out that on the same machine, but on Chromium, the connection is not lost.

## Steps to Reproduce (for bugs)

0. Preparation: on the phone, disable the Threema app energy saving
1. Open the Threema Web page on Firefox (I always connect with a password)
2. Connect the mobile phone (I'm on Android)
3. Leave the mobile phone turned on, with the app in foreground
3. Try to write some messages

## Your Environment

* Threema Web version: 2.2.1
* Threema App version: 4.11b3000507
* Browser name and version: Chromium 77.0.x/Firefox 69.0.x
* Computer operating system and version: Ubuntu 18.04.x derivative
* Smartphone operating system and version: Android 8.1.0

**Comment by saveriomiroddi** [comment]
> @saveriomiroddi: In case it's reproducible on Firefox, the browser logs and app logs would be interesting.

Thanks! I've sent both Webapp and app logs. There have been a few disconnections towards the end. This time the disconnections were (I think) later than usual, but the usage pattern was different from usual as well (I usually send few longer messages; the test was performed with many small ones).

**Comment by dbrgn** [comment]
@saveriomiroddi would you be willing to share your threema ID so we can find the support ticket? alternatively send the URL to this issue to the support team (if you haven't done so already), so they can escalate the ticket to one of the developers.

**Comment by saveriomiroddi** [comment]
> @saveriomiroddi would you be willing to share your threema ID so we can find the support ticket? alternatively send the URL to this issue to the support team (if you haven't done so already), so they can escalate the ticket to one of the developers.

Hello! I've sent a link to this issue to the support team via messaging; let me know if this is not sufficient! Thanks.

**Comment by lgrahl** [comment]
We can dispatch the ticket to a developer directly if we can search for it (for example by searching for the Threema ID). Otherwise, it goes through the normal process. :slightly_smiling_face:

**Comment by lgrahl** [comment]
Closing since it's handled in a support ticket. If there's reason to believe that there's a problem with this implementation and Firefox, I'll reopen.
