### ISSUE TITLE
New logo for Firefox 70+

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#915]
## Summary

Today, Firefox 70 was released. With it comes a new logo for Firefox that you may want to integrate into the Threema Web section of the apps.

New logo: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Firefox_logo%2C_2019.svg/1024px-Firefox_logo%2C_2019.svg.png

_[In case this should go to *SUPPORT instead, please just close the issue.]_

**Comment by dbrgn** [comment]
Thanks, will be updated in a future release.
