### ISSUE TITLE
Session stopped due to protocol error

### ISSUE THREAD

**Issue by obs1dium** [threema-ch/threema-web#917]
## Bug Description

When connecting to a new web session, the session gets terminated after a few seconds with the message: "The session was stopped due to a protocol error."
I suspect this is due to a previously sent message. The issue started appearing after having sent a couple of video files to a contact, but that might be a red herring.
Happens on several browsers (Firefox, Chrome, Vivaldi).
I'm attaching the log here:
[web log.txt](https://github.com/threema-ch/threema-web/files/3761376/3ma.web.log.txt)
 Suspicious line in there:
"Error: Remote travelled through time and acknowledged a chunk which is in the future"

## Steps to Reproduce (for bugs)

1. Establish new web session
2. Wait for a few seconds (previous image/video messages loading)

## Your Environment

* Threema Web version: 2.2.1
* Threema App version: 4.3.2
* Browser name and version: Firefox 70 / Chrome Chrome 77
* Computer operating system and version: Windows 10.0.18362.356
* Smartphone operating system and version: iOS 13.1.3

**Comment by lgrahl** [comment]
The upcoming 4.4 release will ship with a major refactoring of the web client code in the iOS app. :slightly_smiling_face:

**Comment by obs1dium** [comment]
Ok, will do. Any word on when the update might be released?

**Comment by lgrahl** [comment]
If we don't encounter any blocking bugs, quite soon.

**Comment by obs1dium** [comment]
Looks like the problem has been resolved with version 4.4
