### ISSUE TITLE
add X to clear search bar

### ISSUE THREAD

**Issue by SimJoSt** [threema-ch/threema-web#92]
## Expected Behavior
Clear search input by click on a clear search-bar button.

## Current Behavior
Cannot find clear search-bar button when done with a search, clear it by hand (marking everything, delete).

## Possible Solution
Add an X button at the end of the search bar, to clear previously entered input.

## Steps to Reproduce (for bugs)
Click on the search icon, input a string, do your thing, be finished.
Want to revert to empty search bar to have all my conversations back in the list, click on clear search-bar button, done.

*I am aware, that clicking on the seach icon again hides and clears the search-bar. But not everybody (myself included, was smart enough to find it at the first try). Also I like the possibility to temporarily deactivate the search filter and activate it again when I need it. To achieve that, the behaviour of the second click on the search icon need to be altered to not clear the input anymore.*

**Comment by Buddabread** [comment]
It would be nice if the Search-bar would be automatically cleared after a contact was found and clicked.
After selection of a contact I would like to have the normal view with recent messages.
In my opinion this would be more intuitive.

**Comment by samuelT2** [comment]
Additionally, it would be nice if pressing ESC is binded to the same function as hiding/showing the search icon.

**Comment by samuelT2** [comment]
Hi @dbrgn - I'd like to start working on this issue, fine for you?

**Comment by dbrgn** [comment]
Hi @samuelT2. Yes, as long as the implementation doesn't get overly complicated, we'll happily review PRs!

**Comment by samuelT2** [comment]
Hi @dbrgn - Got a solution ready which covers all above points, but does not support Firefox (because of the use of [::-webkit-search-cancel-button](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-search-cancel-button)). You want me to create the pull request and review the change or shall I invest some time to implement a proper custom solution?

**Comment by dbrgn** [comment]
It would be worthwhile to at least investigate whether an easy alternative solution would be possible.

If not, as long as the input field can be cleared with ESC, I guess it's OK.

**Comment by samuelT2** [comment]
Created a pull request - bringing the X to non-webkit-supported browsers needs more than a dozen lines of CSS. ESC though, works perfectly fine now on all browsers. Think this should do it.
