### ISSUE TITLE
Don't connect if another session is active

### ISSUE THREAD

**Issue by dbrgn** [threema-ch/threema-web#927]
## Bug Description

We recently made a change in the app so that a push with the same affiliation id will stop and discard any already existing Threema Web session.

Because pushes for an already active session were previously ignored, we detected this (since #369) and show a warning. However, the push is not prevented.

This means that now a second tab with the same session will quickly flash the "already connected" dialog, but will the continue connecting. The other tab will eventually lose the connection.

## Steps to Reproduce (for bugs)

1. With the current `develop` version of the Android app and Threema Web e76643b746a572ba4bf77334c74a85125656e623 (now on staging), establish a stored session
2. Connect to the same session in a second tab

## Potential Solution

- Variant A: Avoid connecting or pushing if another tab is active. This probably requires an ugly hack with a timeout, because the broadcast channel is not synchronous.
- Variant B: Remove duplicate session detection. This will cause "unexplainable connection failures" with older app versions though. Additionally, when a session is "taken over", the old session is not immediately terminated but might try to reconnect, potentially causing a situation where both sessions are continuously reconnecting.

**Comment by lgrahl** [comment]
Any reason we send the broadcast before unlocking?

**Comment by dbrgn** [comment]
That would probably work in many cases, except if the page was already opened (but not unlocked) was already open when the connection in the other tab was established.

**Comment by dbrgn** [comment]
We could schedule regular broadcasts.

**Comment by lgrahl** [comment]
Confused... the first tab wins. I don't get the problem?

**Comment by dbrgn** [comment]
Tab A is opened, checks whether another session is active. There is none.

Tab B is opened, checks whether another session is active. There is none. It connects.

Tab A connects. Because no session was active when the tab was originally opened, it will try to reconnect and sends a push.
