### ISSUE TITLE
[Question] How does Threema deal with different versions ?

### ISSUE THREAD

**Issue by umbri** [threema-ch/threema-web#939]
How does ```Threema``` deal with different versions of Web and App ?

If an older version of App is connecting to a new Web version, how do you deal with this ?
From [qr_code.md](https://github.com/threema-ch/threema-web/blob/master/docs/qr_code.md) I see that App knows about Web version (from QR code), how do you use this ?

Thanks

**Comment by lgrahl** [comment]
Answering that in detail would be a wall of text. We use versions in different places and on different layers (where the one in the QR code is just one). Most of the time, we don't even need a version to detect that something is or is not compatible. I think we only had one major incompatibility which required users to upgrade their app.

Most app versions work with most web versions. Basically, we just have been careful to not introduce breaking changes but we could handle that if we really have to.

**Comment by umbri** [comment]
Thank you for quick answer. We are thinking about this before release, and ```backward compatibility``` can be a real pain, if big changes are required.
