### ISSUE TITLE
Typo `Benachrichtigunstöne`

### ISSUE THREAD

**Issue by NoNoNo** [threema-ch/threema-web#940]
`Benachrichtigunstöne` -> `Benachrichtigungstöne`
https://github.com/threema-ch/threema-web/blob/master/public/i18n/de.json#L294

**Comment by rugk** [comment]
-> https://github.com/threema-ch/threema-web/blob/master/TRANSLATING.md ? :thinking:

**Comment by dbrgn** [comment]
Thanks, fixed on Transifex.

**Comment by ovalseven8** [comment]
@dbrgn:
Whitespace missing: `FAQ-Artikel fürAndroid und iOS`

![grafik](https://user-images.githubusercontent.com/8258609/71086757-ec381500-219a-11ea-810b-6cdc99b3d531.png)

**Comment by dbrgn** [comment]
@ovalseven8 thanks, fixed on Transifex, will land in the next release.
