### ISSUE TITLE
Threema app displays session is still active although already disconnected

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#951]
## Bug Description

Threema session is marked as active although disconnected in Threema Web. It takes ~ 16 seconds on my phone until the right state is displayed.

Not sure if it's only a UI bug or there is a logical implementation error.

![Screenshot_20191223-170321](https://user-images.githubusercontent.com/8258609/71367976-df565f80-25a6-11ea-95e4-55107d68ead4.png)

![Screenshot_20191223-135857](https://user-images.githubusercontent.com/8258609/71359475-cc369600-258c-11ea-8cfb-23f79d4dc2b0.png)

## Steps to Reproduce (for bugs)

1. Go to https://web.threema.ch
2. Connect to session
3. Close session **in the app**
4. Session is marked as inactive on the smartphone :heavy_check_mark: 

---

1. Go to https://web.threema.ch
2. Connect to session
3. Close session **in Threema Web**
4. It takes ~ 16 seconds until marked as inactive on the smartphone ❌

## Your Environment

* Threema Web version: 2.3.1
* Threema App version: 4.22 (Android)
* Browser name and version: Firefox 71
* Computer operating system: Linux
* Smartphone operating system and version: Android 6

**Comment by dbrgn** [comment]
With "Close session in Threema Web" you mean going through the menu and clicking "Close Session", and not just pressing F5, right?

**Comment by ovalseven8** [comment]
> With "Close session in Threema Web" you mean going through the menu and clicking "Close Session", and not just pressing F5, right?

Exactly.

**Comment by lgrahl** [comment]
Should be fixed in the upcoming beta.
