### ISSUE TITLE
Single emojis should be large

### ISSUE THREAD

**Issue by simmac** [threema-ch/threema-web#97]
## Expected Behavior

When sending only one single emoji, the emoji should be displayed largely to be consistent with the App.

## Current Behavior

The emoji is displayed in the normal font size

## Possible Solution

Check if a message only contains a single emoji (watch out for [emoji modifiers](http://unicode.org/reports/tr51/#Emoji_Modifiers_Table) like skin tones and [ZWJ](http://unicode.org/reports/tr51/#Emoji_ZWJ_Sequences)s which could count as multiple symbols, but represent a single emoji) and set the font size to a higher amount.

## Steps to Reproduce (for bugs)

1. Send a single emoji as a message
2. Compare the displayed message on Threema Web and the Android app

## Your Environment

* Threema Web version: 1.0.3
* Threema for Android version: 3.02
* Threema for Android source: Play Store
* Browser name and version: Chrome 56
* Operating system and version: macOS 10.12

**Comment by simmac** [comment]
@dbrgn Just curious: Why would this need an app update?

**Comment by dbrgn** [comment]
> the emoji should be displayed largely to be consistent with the App

This is configurable in the app. I know a few people that disabled it. (I'm not a big fan either :))

**Comment by FloThinksPi** [comment]
@dbrgn could this be also also included in local storage settings as first step like issue #8 or #9 ?

**Comment by dbrgn** [comment]
It could, but in contrast to the notification settings I don't see why people would want large emojis in the app but not in the browser, or vice versa.
