### ISSUE TITLE
Provide information on web to app version incompatibility on failure to connect

### ISSUE THREAD

**Issue by imsodin** [threema-ch/threema-web#984]
I just wrote a bug report that I cannot re-connect to permanent sessions since upgrading to 2.3.7. Then when looking up the app version realised there's an update there too. Now everything is working fine again. It would have saved me some time if there were a notice to potential incompatibilities. In the simplest way just a a bullet point to check for app updates if problems persist, ideally you might even provide the info about which versions are compatible.

**Comment by imsodin** [comment]
Unfortunately still a bug: It now doesn't work again, it probably just worked once because of the upgrade (?). So I'll post the original text of my bug report here, I assume you can retag the issue as appropriate. Please let me know what additional info I can provide.

## Bug Description

Since upgrading to 2.3.7, I cannot reconnect to a permanent session. I can create new ones and they work fine until the page is reloaded, but then it gets stuck at "12% - Waiting for app wakeup". All the while the app is in foreground on the phone (and anyway works for new sessions).

## Steps to Reproduce (for bugs)

1. Create a new session with password
2. Make sure it connects and works.
3. Reload browser and enter your password.

## Your Environment

* Threema Web version: 2.3.7
* Threema App version: 4.31
* Browser name and version: Both firefox 74.0.1 and chromium 80.0.3987.162
* Computer operating system and version: Debian testing
* Smartphone operating system and version: Nokia 5.1, Android 9

<details>
  <summary>Copied from "Troubleshooting" link</summary>
{
  "config": {
    "VERSION": "2.3.7",
    "SELF_HOSTED": false,
    "VERSION_MOUNTAIN": "Säntis",
    "VERSION_MOUNTAIN_URL": "https://en.wikipedia.org/wiki/Säntis",
    "VERSION_MOUNTAIN_IMAGE_URL": "https://en.wikipedia.org/wiki/S%C3%A4ntis#/media/File:S%C3%A4ntis_mountain_by_sunset..JPG",
    "VERSION_MOUNTAIN_IMAGE_COPYRIGHT": "CC BY-SA 3.0 B0rder",
    "VERSION_MOUNTAIN_HEIGHT": 2502,
    "PREV_PROTOCOL_LAST_VERSION": "1.8.2",
    "GIT_BRANCH": "master",
    "SALTYRTC_HOST": "saltyrtc-{prefix}.threema.ch",
    "SALTYRTC_PORT": 443,
    "SALTYRTC_SERVER_KEY": "b1337fc8402f7db8ea639e05ed05d65463e24809792f91eca29e88101b4a2171",
    "ICE_SERVERS": [
      {
        "urls": [
          "turn:ds-turn-{prefix}.threema.ch:443?transport=udp",
          "turn:ds-turn-{prefix}.threema.ch:443?transport=tcp",
          "turns:ds-turn-{prefix}.threema.ch:443"
        ],
        "username": "[String]",
        "credential": "[String]"
      }
    ],
    "PUSH_URL": "https://push-web.threema.ch/push",
    "FONT_CSS_URL": null,
    "LOG_TAG_PADDING": 20,
    "CONSOLE_LOG_LEVEL": "info",
    "REPORT_LOG_LEVEL": "debug",
    "REPORT_LOG_LIMIT": 1000,
    "COMPOSE_AREA_LOG_LEVEL": "warn",
    "SALTYRTC_LOG_LEVEL": "warn",
    "TIMER_LOG_LEVEL": "info",
    "ARP_LOG_LEVEL": "debug",
    "ARP_LOG_TRACE": false,
    "MSGPACK_LOG_TRACE": false,
    "TRANSPORT_LOG_LEVEL": "warn",
    "VISUALIZE_STATE": false
  },
  "browser": "Firefox 74",
  "log": [
    [
      1586245734437,
      "debug",
      "%c[State-S]",
      "color: #fff; background-color: #cc9900",
      "Reset states"
    ],
    [
      1586245734469,
      "debug",
      "%c[Theme-S]",
      "color: #fff; background-color: #cc9900",
      "Initializing with theme threema"
    ],
    [
      1586245734471,
      "debug",
      "%c[AppRemoteProtocol]",
      "color: #fff; background-color: #0099cc",
      "Reset initialization steps"
    ],
    [
      1586245734774,
      "info",
      "[Welcome-C]",
      "Detected browser:",
      "Firefox 74"
    ],
    [
      1586245734778,
      "debug",
      "%c[AppRemoteProtocol]",
      "color: #fff; background-color: #0099cc",
      "Reset initialization steps"
    ],
    [
      1586245734779,
      "debug",
      "%c[State-S]",
      "color: #fff; background-color: #cc9900",
      "Reset states"
    ],
    [
      1586245734779,
      "info",
      "[Welcome-C]",
      "Initialize session by unlocking trusted key..."
    ],
    [
      1586245734937,
      "info",
      "[Version-S]",
      "Using Threema Web version",
      "2.3.7"
    ],
    [
      1586245779242,
      "debug",
      "[Welcome-C]",
      "Checking if the session is already open in another tab or window"
    ],
    [
      1586245779344,
      "debug",
      "[Welcome-C]",
      "No broadcast received indicating that a session is already open"
    ],
    [
      1586245779347,
      "info",
      "%c[WebClient-S]",
      "color: #fff; background-color: #0066cc",
      "Stopping (reason=stop, send=false, close=welcome, connectionBuildupState=new)"
    ],
    [
      1586245779348,
      "debug",
      "%c[WebClient-S]",
      "color: #fff; background-color: #0066cc",
      "Timer stopped"
    ],
    [
      1586245779348,
      "debug",
      "%c[State-S]",
      "color: #fff; background-color: #cc9900",
      "Reset states"
    ],
    [
      1586245779348,
      "debug",
      "%c[AppRemoteProtocol]",
      "color: #fff; background-color: #0099cc",
      "Reset initialization steps"
    ],
    [
      1586245779350,
      "debug",
      "%c[AppRemoteProtocol]",
      "color: #fff; background-color: #0099cc",
      "Session closed (cannot be resumed)"
    ],
    [
      1586245779350,
      "debug",
      "%c[AppRemoteProtocol]",
      "color: #fff; background-color: #0099cc",
      "Peer connection was null"
    ],
    [
      1586245779361,
      "info",
      "%c[Push-S]",
      "color: #fff; background-color: #9900ff",
      "Initialized with",
      "gcm",
      "token"
    ],
    [
      1586245779362,
      "info",
      "%c[WebClient-S]",
      "color: #fff; background-color: #0066cc",
      "Initializing (keyStore=yes, peerTrustedKey=yes, resume=false)"
    ],
    [
      1586245779362,
      "debug",
      "%c[AppRemoteProtocol]",
      "color: #fff; background-color: #0099cc",
      "Reset initialization steps"
    ],
    [
      1586245779362,
      "debug",
      "%c[AppRemoteProtocol]",
      "color: #fff; background-color: #0099cc",
      "Discarded previous session"
    ],
    [
      1586245779367,
      "info",
      "%c[AppRemoteProtocol]",
      "color: #fff; background-color: #0099cc",
      "Public key:",
      "edd02519f734e7fc0ded4f1875f8416ef4852df93a380a48ecc2cbce8a19fd4e"
    ],
    [
      1586245779368,
      "debug",
      "%c[WebClient-S]",
      "color: #fff; background-color: #0066cc",
      "Starting WebClientService..."
    ],
    [
      1586245779368,
      "debug",
      "%c[WebClient-S]",
      "color: #fff; background-color: #0066cc",
      "Creating new startup promise"
    ],
    [
      1586245779368,
      "debug",
      "%c[State-S]",
      "color: #fff; background-color: #cc9900",
      "Connection buildup state:",
      "new",
      "=>",
      "connecting"
    ],
    [
      1586245779368,
      "debug",
      "%c[State-S]",
      "color: #fff; background-color: #cc9900",
      "Signaling connection state:",
      "new",
      "=>",
      "new"
    ],
    [
      1586245779370,
      "debug",
      "%c[State-S]",
      "color: #fff; background-color: #cc9900",
      "Signaling connection state:",
      "new",
      "=>",
      "ws-connecting"
    ],
    [
      1586245779372,
      "debug",
      "%c[State-S]",
      "color: #fff; background-color: #cc9900",
      "Connection buildup state:",
      "connecting",
      "=>",
      "push"
    ],
    [
      1586245779425,
      "debug",
      "%c[Status-C]",
      "color: #000; background-color: #ffff99",
      "State change:",
      "error",
      "->",
      "warning"
    ],
    [
      1586245779432,
      "debug",
      "%c[Push.gNyDsY]",
      "color: #fff; background-color: #9900cc",
      "Sending push 1/1 (ttl=90)"
    ],
    [
      1586245779434,
      "debug",
      "%c[State-S]",
      "color: #fff; background-color: #cc9900",
      "Signaling connection state:",
      "ws-connecting",
      "=>",
      "server-handshake"
    ],
    [
      1586245779481,
      "debug",
      "%c[State-S]",
      "color: #fff; background-color: #cc9900",
      "Signaling connection state:",
      "server-handshake",
      "=>",
      "peer-handshake"
    ],
    [
      1586245779546,
      "debug",
      "%c[Push.gNyDsY]",
      "color: #fff; background-color: #9900cc",
      "Push sent successfully"
    ]
  ]
}
</details>

**Comment by dbrgn** [comment]
> It would have saved me some time if there were a notice to potential incompatibilities.

There should be no incompatibilities, as long as you use a reasonably recent version of Threema and Threema Web.

If the connection gets stuck at 12%, that indicates problems with the delivery of push notifications to your device. Did you make sure that Threema is excluded from battery optimization?

If the problem persists, please contact the Threema Support through https://threema.id/*SUPPORT, they should be able to help you.
