### ISSUE TITLE
Textcode as alternative to QR-Code

### ISSUE THREAD

**Issue by gordon-shumway-net** [threema-ch/threema-web#993]
Hey together. :)

Here a very short feature Request.
What do you think?

## Summary

Also offer the option to type in an Textcode in the Threema App, in addition to the scan the QR-Code option to connect.

## Additional context

Also if the Code might be very long, it would be cool for people who maybe have a camera which is not working, or don't wanna use it for security/privacy reasons.

**Comment by dbrgn** [comment]
Hi, thanks for your suggestion!

The QR code contains quite some information! Even when using base64 encoding, it still looks somewhat like this:

> AAIAcOOUtRNr5bsDKAdzxnpQor/YiNtWxCQDRU7G+zY0RBs/SlQ6Ke76YYzzACZKnEHKyixwxqlH87HDn/gmvcMvr7Ezf8hAL3246mOeBe0F1lRj4kgJeS+R7KKeiBAbSiFxAbtzYWx0eXJ0Yy1iZXRhLnRocmVlbWEuY2g=

I don't think anyone would want to type that.

For now, I'll close this issue, but feel free to add further comments.
